from __future__ import annotations
# ruff: noqa
def _render_audit_function_gap_stub(result: Any, item: Any) -> str:
    """Render a draft review stub from function-level audit evidence."""
    import inspect

    from ordeal.audit import _func_sig_for_codegen
    from ordeal.auto import _resolve_module

    function_name = str(getattr(item, "name", "")).strip()
    target_name = f"{result.module}.{function_name}"
    status = str(getattr(item, "status", "exploratory"))
    epistemic = str(getattr(item, "epistemic", "inferred"))
    covered_body_lines = int(getattr(item, "covered_body_lines", 0) or 0)
    total_body_lines = int(getattr(item, "total_body_lines", 0) or 0)
    evidence = list(getattr(item, "evidence", []))

    reviewed_signature = f"{function_name}(...)"
    call_expr = f"_ordeal_target.{function_name}(...)"
    try:
        mod = _resolve_module(result.module)
        func = mod
        owner_name = None
        method_name = function_name
        if "." in function_name:
            owner_name, method_name = function_name.rsplit(".", 1)
            for part in owner_name.split("."):
                func = getattr(func, part)
            target_owner = func
            func = getattr(target_owner, method_name)
            if inspect.isclass(target_owner):
                descriptor = inspect.getattr_static(target_owner, method_name)
                if isinstance(descriptor, (staticmethod, classmethod)):
                    call_expr = f"_ordeal_target.{owner_name}.{method_name}(...)"
                else:
                    try:
                        target_owner()
                        call_expr = f"_ordeal_target.{owner_name}().{method_name}(...)"
                    except Exception:
                        call_expr = f"_ordeal_target.{owner_name}.{method_name}(...)"
            else:
                call_expr = f"_ordeal_target.{owner_name}.{method_name}(...)"
        else:
            func = getattr(mod, function_name)
        sig_info = _func_sig_for_codegen(func)
        if sig_info is not None:
            param_names, decls, _call_args, _imports = sig_info
            reviewed_signature = f"{function_name}({', '.join(decls)})"
            placeholders = ", ".join("..." for _ in param_names)
            if "." not in function_name:
                call_expr = (
                    f"_ordeal_target.{function_name}({placeholders})"
                    if placeholders
                    else f"_ordeal_target.{function_name}()"
                )
        else:
            signature = inspect.signature(func)
            reviewed_signature = f"{function_name}{signature}"
            if "." not in function_name:
                call_expr = (
                    f"_ordeal_target.{function_name}()"
                    if len(signature.parameters) == 0
                    else f"_ordeal_target.{function_name}(...)"
                )
    except Exception:
        pass

    lines = [
        f'"""Draft review stubs for audit gaps in {target_name}.',
        "",
        "Generated by ordeal.",
        "These are review notes, not runnable regressions yet.",
        f"Epistemic status: {status} [{epistemic}]",
        f"Reviewed signature: {reviewed_signature}",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f"import {result.module} as _ordeal_target",
        "",
        "# Evidence summary:",
    ]
    if total_body_lines > 0:
        lines.append(f"# - covered body lines: {covered_body_lines}/{total_body_lines}")
    if evidence:
        for entry in evidence[:5]:
            kind = entry.get("kind", "evidence")
            epistemic_note = entry.get("epistemic")
            detail = entry.get("detail", "")
            suffix = f" [{epistemic_note}]" if epistemic_note else ""
            detail = f"# - {kind}{suffix}: {detail}"
            lines.append(detail.rstrip())
    else:
        lines.append("# - no direct evidence recorded")
    lines.extend(
        [
            "",
            "# Why this exists:",
            (
                f"# - write a direct regression for {target_name}"
                if status == "uncovered"
                else "# - replace indirect coverage with a direct regression"
            ),
            (
                "# - the current tests only reach this behavior indirectly"
                if status == "exploratory"
                else "# - there is no effective test coverage yet"
            ),
            "# - keep the assertion small, specific, and reviewable",
            "",
            "# Suggested starting point:",
            f"# def test_{target_name.replace('.', '_')}_gap() -> None:",
            (
                f"#     # TODO: call {reviewed_signature} with a concrete input "
                "that matches the evidence."
            ),
            f"#     result = {call_expr}",
            "#     # TODO: assert the intended contract, not just that the call succeeds.",
            "#     assert ...",
            "",
        ]
    )
    return "\n".join(lines)
def _function_gap_detail_items(
    result: Any,
    *,
    include_exploratory_function_gaps: bool,
) -> list[dict[str, Any]]:
    """Normalize function audits into finding-style detail items."""
    fixture_completeness = float(getattr(result, "fixture_completeness", 0.0))
    function_audits = [
        item
        for item in getattr(result, "function_audits", [])
        if getattr(item, "status", "") != "exercised"
    ]
    function_audits.sort(
        key=lambda item: (
            _function_gap_status_rank(str(getattr(item, "status", ""))),
            -int(getattr(item, "covered_body_lines", 0) or 0),
            str(getattr(item, "name", "")),
        )
    )
    details: list[dict[str, Any]] = []
    for item in function_audits:
        status = str(getattr(item, "status", ""))
        if status == "exploratory" and not include_exploratory_function_gaps:
            continue
        summary = (
            f"{item.name} is only indirectly exercised by current tests"
            if status == "exploratory"
            else f"{item.name} has no effective tests yet"
        )
        details.append(
            {
                "kind": "function_gap",
                "category": "test_strength_gap",
                "summary": summary,
                "module": result.module,
                "function": item.name,
                "qualname": f"{result.module}.{item.name}",
                "details": {
                    "status": status,
                    "priority": _function_gap_status_rank(status),
                    "fixture_completeness": fixture_completeness,
                    "epistemic": getattr(item, "epistemic", ""),
                    "covered_body_lines": getattr(item, "covered_body_lines", 0),
                    "total_body_lines": getattr(item, "total_body_lines", 0),
                    "evidence": list(getattr(item, "evidence", [])),
                },
            }
        )
    return details
def _direct_test_gate_payload(results: Sequence[Any]) -> dict[str, Any]:
    """Summarize direct-test gate status from function-level audit evidence."""
    exploratory: list[str] = []
    uncovered: list[str] = []
    for result in results:
        direct_gaps = getattr(result, "direct_test_gaps", None)
        items = (
            list(direct_gaps)
            if direct_gaps is not None
            else [
                item
                for item in getattr(result, "function_audits", [])
                if getattr(item, "status", "") != "exercised"
            ]
        )
        for item in items:
            qualname = f"{result.module}.{getattr(item, 'name', '')}".rstrip(".")
            status = str(getattr(item, "status", ""))
            if status == "exploratory":
                exploratory.append(qualname)
            elif status == "uncovered":
                uncovered.append(qualname)
    return {
        "passed": not exploratory and not uncovered,
        "exploratory": exploratory,
        "uncovered": uncovered,
    }
def _direct_test_gate_summary(gate: Mapping[str, Any]) -> str:
    """Render a compact direct-test gate summary."""
    exploratory = list(gate.get("exploratory", []))
    uncovered = list(gate.get("uncovered", []))
    if not exploratory and not uncovered:
        return "Direct test gate: PASS"
    parts: list[str] = []
    if exploratory:
        parts.append(f"{len(exploratory)} exploratory")
    if uncovered:
        parts.append(f"{len(uncovered)} uncovered")
    return f"Direct test gate: FAIL ({', '.join(parts)})"
def _write_audit_gap_stubs(
    audit_results: Sequence[Any],
    *,
    output_dir: str,
    include_exploratory_function_gaps: bool = False,
) -> list[dict[str, Any]]:
    """Write draft audit gap stubs from mutation gaps and function evidence."""
    written: list[dict[str, Any]] = []
    written_targets: set[str] = set()
    for result in audit_results:
        for item in result.mutation_gap_stubs:
            content = str(item.get("content", "")).strip()
            target_name = str(item.get("target", "")).strip()
            if not content or not target_name:
                continue
            path = _audit_gap_stub_path(output_dir, target_name)
            path.parent.mkdir(parents=True, exist_ok=True)
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content + "\n":
                path.write_text(content + "\n", encoding="utf-8")
            written_targets.add(target_name)
            written.append(
                {
                    "module": result.module,
                    "target": target_name,
                    "path": _display_path(path),
                    "source": "mutation_gap",
                }
            )
        function_audits = [
            item
            for item in getattr(result, "function_audits", [])
            if getattr(item, "status", "") != "exercised"
        ]
        function_audits.sort(
            key=lambda item: (
                _function_gap_status_rank(str(getattr(item, "status", ""))),
                -int(getattr(item, "covered_body_lines", 0) or 0),
                str(getattr(item, "name", "")),
            )
        )
        for item in function_audits:
            status = str(getattr(item, "status", ""))
            if status not in {"exploratory", "uncovered"}:
                continue
            if status == "exploratory" and not include_exploratory_function_gaps:
                continue
            target_name = f"{result.module}.{getattr(item, 'name', '')}".strip()
            if not target_name or target_name in written_targets:
                continue
            content = _render_audit_function_gap_stub(result, item).strip()
            path = _audit_gap_stub_path(output_dir, target_name)
            path.parent.mkdir(parents=True, exist_ok=True)
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != content + "\n":
                path.write_text(content + "\n", encoding="utf-8")
            written_targets.add(target_name)
            written.append(
                {
                    "module": result.module,
                    "target": target_name,
                    "path": _display_path(path),
                    "source": "function_audit",
                    "status": status,
                    "epistemic": str(getattr(item, "epistemic", "")),
                }
            )
    return written
def _parse_named_override_spec(raw: str) -> tuple[str, list[str]]:
    """Parse a repeatable ``NAME=value1,value2`` override spec."""
    if "=" not in raw:
        raise argparse.ArgumentTypeError("Expected NAME=value1,value2")
    name, values = raw.split("=", 1)
    name = name.strip()
    items = [item.strip() for item in values.split(",") if item.strip()]
    if not name or not items:
        raise argparse.ArgumentTypeError("Expected NAME=value1,value2")
    return name, items
def _merge_unique_strings(*groups: Sequence[str] | None) -> list[str]:
    """Merge string sequences while preserving order and uniqueness."""
    merged: list[str] = []
    seen: set[str] = set()
    for group in groups:
        if not group:
            continue
        for item in group:
            if item in seen:
                continue
            seen.add(item)
            merged.append(item)
    return merged
def _named_override_specs_to_map(
    specs: Sequence[tuple[str, Sequence[str]]] | None,
) -> dict[str, list[str]]:
    """Convert repeatable CLI override specs to a mapping."""
    merged: dict[str, list[str]] = {}
    for name, values in specs or ():
        bucket = merged.setdefault(name, [])
        for value in values:
            if value not in bucket:
                bucket.append(value)
    return merged
def _merge_named_overrides(
    *groups: Mapping[str, Sequence[str]] | None,
) -> dict[str, list[str]]:
    """Merge named override mappings while preserving order and uniqueness."""
    merged: dict[str, list[str]] = {}
    for group in groups:
        if not group:
            continue
        for name, values in group.items():
            bucket = merged.setdefault(str(name), [])
            for value in values:
                if value not in bucket:
                    bucket.append(value)
    return merged
def _config_object_specs_for_module(cfg: OrdealConfig, module_name: str) -> list[Any]:
    """Return shared object configs that belong to *module_name*."""
    return [spec for spec in cfg.objects if _target_module_name(spec.target) == module_name]
def _object_runtime_maps(
    object_specs: Sequence[Any],
    *,
    resolve_imports: bool = True,
) -> tuple[
    dict[str, Any],
    dict[str, Any],
    dict[str, Any],
    dict[str, Any],
    dict[str, Any],
    dict[str, str],
]:
    """Resolve configured object factories, state hooks, and scenarios."""
    factories: dict[str, Any] = {}
    setups: dict[str, Any] = {}
    scenarios: dict[str, Any] = {}
    state_factories: dict[str, Any] = {}
    teardowns: dict[str, Any] = {}
    harnesses: dict[str, str] = {}

    def _resolve_scenario_item(item: object) -> object:
        if isinstance(item, Mapping):
            return dict(item)
        if isinstance(item, (str, bytes)):
            text = item.decode() if isinstance(item, bytes) else item
            if not resolve_imports:
                return _metadata_only_hook("scenario", text)
            from ordeal.auto import _builtin_object_scenario_hook

            builtin = _builtin_object_scenario_hook(text)
            if builtin is not None:
                return builtin
            return _resolve_symbol_path(text)
        if not resolve_imports:
            return _metadata_only_hook("scenario", str(item))
        return _resolve_symbol_path(str(item))

    for spec in object_specs:
        target = str(getattr(spec, "target"))
        factory_path = getattr(spec, "factory", None)
        setup_path = getattr(spec, "setup", None)
        state_factory_path = getattr(spec, "state_factory", None)
        teardown_path = getattr(spec, "teardown", None)
        harness = str(getattr(spec, "harness", "fresh") or "fresh").strip().lower()
        scenario_paths = list(getattr(spec, "scenarios", []) or [])
        if factory_path:
            factories[target] = (
                _resolve_symbol_path(str(factory_path))
                if resolve_imports
                else _metadata_only_hook("factory", str(factory_path))
            )
        if setup_path:
            setups[target] = (
                _resolve_symbol_path(str(setup_path))
                if resolve_imports
                else _metadata_only_hook("setup", str(setup_path))
            )
        if state_factory_path:
            state_factories[target] = (
                _resolve_symbol_path(str(state_factory_path))
                if resolve_imports
                else _metadata_only_hook("state_factory", str(state_factory_path))
            )
        if teardown_path:
            teardowns[target] = (
                _resolve_symbol_path(str(teardown_path))
                if resolve_imports
                else _metadata_only_hook("teardown", str(teardown_path))
            )
        harnesses[target] = harness if harness in {"fresh", "stateful"} else "fresh"
        if scenario_paths:
            resolved_hooks = tuple(_resolve_scenario_item(path) for path in scenario_paths)
            hook: object = resolved_hooks[0] if len(resolved_hooks) == 1 else resolved_hooks
            with contextlib.suppress(Exception):
                setattr(hook, "__ordeal_scenario_count__", len(resolved_hooks))
            scenarios[target] = hook
    return factories, setups, scenarios, state_factories, teardowns, harnesses
def _config_contract_checks_for_module(
    cfg: OrdealConfig,
    module_name: str,
    *,
    resolve_imports: bool = True,
) -> dict[str, list[Any]]:
    """Resolve configured semantic contract probes for *module_name*."""
    from ordeal.auto import (
        ContractCheck,
        _expand_contract_names_ordered,
        builtin_contract_check,
    )

    checks: dict[str, list[Any]] = {}
    for spec in cfg.contracts:
        target = str(spec.target)
        if _target_module_name(target) != module_name:
            continue
        display_name = _scan_display_name(module_name, target)
        bucket = checks.setdefault(display_name, [])
        for check_name in _expand_contract_names_ordered(spec.checks):
            resolved_name = str(check_name)
            if not resolve_imports:
                bucket.append(
                    SimpleNamespace(
                        name=resolved_name.rsplit(":", 1)[-1].rsplit(".", 1)[-1],
                    )
                )
                continue
            try:
                builtin_kwargs = dict(spec.kwargs)
                lifecycle_phase = (
                    str(getattr(spec, "phase", None) or builtin_kwargs.pop("phase", "")) or None
                )
                followup_phases = [
                    str(item)
                    for item in (
                        list(getattr(spec, "followup_phases", []) or [])
                        or list(builtin_kwargs.pop("followup_phases", []) or [])
                    )
                    if str(item).strip()
                ] or None
                fault = str(
                    getattr(spec, "fault", None) or builtin_kwargs.pop("fault", "raise") or "raise"
                )
                handler_name = (
                    str(
                        getattr(spec, "handler_name", None)
                        or builtin_kwargs.pop("handler_name", "")
                    )
                    or None
                )
                bucket.append(
                    builtin_contract_check(
                        resolved_name,
                        kwargs=builtin_kwargs,
                        tracked_params=list(spec.tracked_params),
                        protected_keys=list(spec.protected_keys),
                        env_param=spec.env_param,
                        phase=lifecycle_phase,
                        followup_phases=followup_phases,
                        fault=fault,
                        handler_name=handler_name,
                    )
                )
            except ValueError:
                predicate = _resolve_symbol_path(resolved_name)
                summary = inspect.getdoc(predicate)
                bucket.append(
                    ContractCheck(
                        name=resolved_name.rsplit(":", 1)[-1].rsplit(".", 1)[-1],
                        predicate=predicate,
                        kwargs=dict(spec.kwargs),
                        summary=summary.splitlines()[0] if summary else None,
                    )
                )
    return checks
