from __future__ import annotations
# ruff: noqa
def _render_scan_regression_file(state: Any) -> str | None:
    """Render a pytest file from concrete scan findings."""
    stubs, _ = _scan_regression_stubs(state)
    if not stubs:
        return None
    return _render_regression_file(
        [
            '"""Generated by `ordeal scan --write-regression`.',
            "",
            f"Target: {state.module}",
            '"""',
            "",
        ],
        stubs,
    )
def _mine_regression_stubs(
    *,
    target: str,
    module: str,
    results: list[tuple[str, Any]],
    skipped: list[tuple[str, str]],
    suspicious_count: int,
) -> tuple[list[str], list[str]]:
    """Build runnable regression stubs from replayable mine findings."""
    report = _build_mine_report(
        target=target,
        module=module,
        results=results,
        skipped=skipped,
        include_scan_hint=False,
        suspicious_count=suspicious_count,
    )
    return _regression_stubs_from_details(module=module, details=report["details"])
def _render_mine_regression_file(
    *,
    target: str,
    module: str,
    results: list[tuple[str, Any]],
    skipped: list[tuple[str, str]],
    suspicious_count: int,
) -> str | None:
    """Render a pytest file from concrete mine findings."""
    stubs, _ = _mine_regression_stubs(
        target=target,
        module=module,
        results=results,
        skipped=skipped,
        suspicious_count=suspicious_count,
    )
    if not stubs:
        return None
    return _render_regression_file(
        [
            '"""Generated by `ordeal mine --write-regression`.',
            "",
            f"Target: {target}",
            '"""',
            "",
        ],
        stubs,
    )
def _build_mine_report(
    *,
    target: str,
    module: str,
    results: list[tuple[str, Any]],
    skipped: list[tuple[str, str]],
    include_scan_hint: bool,
    suspicious_count: int,
) -> dict[str, Any]:
    """Normalize mine output into the shared finding report shape."""
    from ordeal.mine import _is_suspicious_property

    details: list[dict[str, Any]] = []
    blind_spots: list[str] = []
    for name, result in results:
        blind_spots.extend(result.not_checked)
        suspicious = sorted(
            [prop for prop in result.properties if _is_suspicious_property(prop)],
            key=lambda prop: (-prop.confidence, prop.name),
        )
        for prop in suspicious:
            details.append(
                {
                    "kind": "property",
                    "module": module,
                    "function": name,
                    "qualname": f"{module}.{name}",
                    "name": prop.name,
                    "summary": f"{prop.name} ({prop.confidence:.0%})",
                    "confidence": prop.confidence,
                    "holds": prop.holds,
                    "total": prop.total,
                    "counterexample": prop.counterexample,
                }
            )

    suggested = [f"ordeal mine {target} -n 200", f"ordeal mutate {target}"]
    if include_scan_hint:
        suggested.insert(1, f"ordeal scan {module}")

    return {
        "target": target,
        "tool": "mine",
        "status": "findings found" if details else "no suspicious findings",
        "summary": [
            f"Checked: {len(results)} function(s)",
            f"Suspicious findings: {suspicious_count}",
            f"Skipped: {len(skipped)} function(s)",
        ],
        "details": details,
        "extra_sections": [
            ("What Mine Did Not Check", list(dict.fromkeys(blind_spots))),
            ("Skipped Functions", [f"`{module}.{name}`: {reason}" for name, reason in skipped]),
        ],
        "suggested_commands": suggested,
    }
def _detail_confidence(detail: Mapping[str, Any]) -> float | None:
    """Extract a numeric confidence-like score when one exists naturally."""
    value = detail.get("confidence")
    if value is not None:
        try:
            return float(value)
        except (TypeError, ValueError):
            return None
    value = detail.get("mutation_score")
    if value is not None:
        try:
            return float(value)
        except (TypeError, ValueError):
            return None
    value = detail.get("contract_fit")
    if value is not None:
        try:
            return float(value)
        except (TypeError, ValueError):
            return None
    return None
def _scan_crash_summary(qualname: str, category: str, replayable: bool | None) -> str:
    """Return the CLI summary string for one scan crash."""
    if category == "likely_bug":
        return f"{qualname}: strong candidate issue on contract-valid inputs"
    if category == "coverage_gap":
        return f"{qualname}: crash evidence still looks like a coverage gap"
    if category == "beyond_declared_contract_robustness":
        return f"{qualname}: robustness issue just beyond the declared contract"
    if category == "invalid_input_crash":
        return f"{qualname}: robustness issue currently looks driven by invalid input"
    if replayable:
        return f"{qualname}: replayable crash on semi-valid inputs, still exploratory"
    return f"{qualname}: unreplayed crash on random inputs"
def _detail_location(detail: Mapping[str, Any]) -> str | None:
    """Normalize common location fields into a stable string."""
    if detail.get("location") is not None:
        return str(detail["location"])
    line = detail.get("line")
    col = detail.get("col")
    if line is None:
        return None
    if col is None:
        return f"L{line}"
    return f"L{line}:{col}"
def _detail_target(detail: Mapping[str, Any], fallback: str) -> str:
    """Pick the most specific target name available for a detail."""
    qualname = detail.get("qualname")
    if qualname is not None:
        return str(qualname)
    function = detail.get("function")
    module = detail.get("module")
    if function is not None and module is not None:
        return f"{module}.{function}"
    if function is not None:
        return str(function)
    return fallback
def _agent_finding_from_detail(detail: Mapping[str, Any], fallback_target: str) -> Any:
    """Convert a shared report detail into an agent-schema finding."""
    from ordeal.agent_schema import AgentFinding

    target = _detail_target(detail, fallback_target)
    summary = str(detail.get("summary") or detail.get("name") or detail.get("kind", "finding"))
    extras = {
        key: value
        for key, value in detail.items()
        if key
        not in {
            "kind",
            "summary",
            "confidence",
            "target",
            "location",
            "qualname",
        }
    }
    nested_details = detail.get("details")
    if isinstance(nested_details, Mapping):
        extras.update(dict(nested_details))
    return AgentFinding(
        kind=str(detail.get("kind", "finding")),
        summary=summary,
        confidence=_detail_confidence(detail),
        target=target,
        location=_detail_location(detail),
        details=extras,
    )
def _agent_artifact(kind: str, uri: str | Path, description: str, **metadata: Any) -> Any:
    """Build an agent-schema artifact."""
    from ordeal.agent_schema import AgentArtifact

    return AgentArtifact(
        kind=kind,
        uri=Path(uri).as_posix() if isinstance(uri, Path) else str(uri),
        description=description,
        metadata=metadata,
    )
def _report_summary_text(report: Mapping[str, Any]) -> str:
    """Collapse the shared report summary list into one agent-facing sentence."""
    items = [str(item) for item in report.get("summary", []) if item]
    if not items:
        return str(report.get("status", "completed"))
    return f"{report.get('status', 'completed')}: {' | '.join(items)}"
def _recommended_action_for_report(report: Mapping[str, Any]) -> str:
    """Return the highest-value next action for an agent consumer."""
    details = list(report.get("details", []))
    target = str(report.get("target", ""))
    tool = str(report.get("tool", "ordeal"))
    if details:
        first = details[0]
        qualname = _detail_target(first, target)
        kind = str(first.get("kind", "finding"))
        if kind == "property":
            return f"Write a regression test for {qualname} from the recorded counterexample."
        if kind == "crash":
            evidence = first.get("evidence")
            replay = evidence.get("replay") if isinstance(evidence, Mapping) else None
            if isinstance(replay, Mapping) and replay.get("status") == "verified":
                return (
                    f"Turn the exact witness for {qualname} into a regression, "
                    "fix the defect, then require the same witness to pass."
                )
            return f"Reproduce the crash in a regression test for {qualname}."
        if kind == "mutation":
            return f"Strengthen tests for {qualname} until the surviving mutant is killed."
        if kind == "coverage_gap":
            return f"Add a targeted test to cover the uncovered behavior in {qualname}."
        if kind == "fixture_gap":
            return f"Provide fixtures or constructors so ordeal can verify {qualname}."
        if kind == "blocked":
            reason = str(first.get("blocking_reason") or first.get("error") or "").strip()
            return (
                f"Provide a supported type, fixture, or object harness for {qualname}; "
                f"Ordeal did not observe target behavior{f': {reason}' if reason else '.'}"
            )
        if kind == "function_gap":
            status_detail = str(first.get("details", {}).get("status", "gap"))
            if status_detail == "exploratory":
                return f"Add a direct test for {qualname} instead of relying on inferred coverage."
            return f"Write the first effective test for {qualname}."
        if kind == "mutation_gap":
            return f"Strengthen tests or mined properties for {qualname}."
        if kind == "warning":
            return (
                f"Resolve the verification warning for {qualname}"
                f" before trusting this {tool} result."
            )
    suggested = list(report.get("suggested_commands", []))
    if suggested:
        return f"Run `{suggested[0]}` next."
    return f"No immediate follow-up required for {target}."
def _build_agent_envelope_from_report(
    report: Mapping[str, Any],
    *,
    status: str,
    confidence: float | None = None,
    confidence_basis: Sequence[str] = (),
    blocking_reason: str | None = None,
    artifacts: Sequence[Any] = (),
    raw_details: Mapping[str, Any] | None = None,
    suggested_test_file: str | None = None,
) -> Any:
    """Wrap a shared report dict in the stable agent envelope."""
    from ordeal.agent_schema import build_agent_envelope

    target = str(report.get("target", ""))
    details = list(report.get("details", []))
    findings = [_agent_finding_from_detail(detail, target) for detail in details]
    merged_raw_details = dict(raw_details or {})
    if "config_suggestions" not in merged_raw_details and report.get("config_suggestions"):
        merged_raw_details["config_suggestions"] = [
            dict(item) for item in report.get("config_suggestions", [])
        ]
    return build_agent_envelope(
        tool=str(report.get("tool", "ordeal")),
        target=target,
        status=status,
        summary=_report_summary_text(report),
        recommended_action=str(
            report.get("recommended_action") or _recommended_action_for_report(report)
        ),
        suggested_commands=tuple(str(item) for item in report.get("suggested_commands", [])),
        suggested_test_file=suggested_test_file,
        confidence=confidence,
        confidence_basis=tuple(str(item) for item in confidence_basis),
        blocking_reason=blocking_reason,
        findings=findings,
        artifacts=artifacts,
        raw_details=merged_raw_details,
    )
def _scan_state_payload(state: Any) -> dict[str, Any]:
    """Serialize scan state for agent consumers without assuming a concrete type."""
    to_dict = getattr(state, "to_dict", None)
    if callable(to_dict):
        payload = dict(to_dict())
    else:
        to_json = getattr(state, "to_json", None)
        if callable(to_json):
            payload = dict(json.loads(to_json()))
        else:
            payload = {
                "module": getattr(state, "module", None),
                "confidence": getattr(state, "confidence", None),
                "findings": list(getattr(state, "findings", [])),
                "finding_details": _scan_report_details(state),
                "frontier": dict(getattr(state, "frontier", {})),
                "skipped": list(getattr(state, "skipped", [])),
                "supervisor_info": dict(getattr(state, "supervisor_info", {})),
            }
    supervisor_info = payload.get("supervisor_info")
    if isinstance(supervisor_info, Mapping):
        payload["supervisor_info"] = {
            key: value for key, value in supervisor_info.items() if key != "reliability_map"
        }
    return payload
def _build_scan_agent_envelope(
    state: Any,
    *,
    written_report_path: Path | None = None,
    written_regression_path: Path | None = None,
    written_regression_manifest_path: Path | None = None,
    written_config_path: Path | None = None,
    written_support_path: Path | None = None,
    written_proofs_path: Path | None = None,
    written_replay_path: Path | None = None,
    written_scenario_library_path: Path | None = None,
    written_reliability_map_path: Path | None = None,
    index_path: Path | None = None,
) -> Any:
    """Build the agent-facing JSON envelope for `ordeal scan`."""
    report = _build_scan_report(state, regression_path=written_regression_path)
    evidence = _scan_evidence_dimensions(state)
    reliability_map = report.get("reliability_map", {})
    compact_reliability_map = (
        {
            key: reliability_map.get(key)
            for key in (
                "schema",
                "module",
                "base_ref",
                "service_faults_enabled",
                "summary",
                "next_experiment",
                "continuity",
                "deepening",
            )
            if key in reliability_map
        }
        if isinstance(reliability_map, Mapping)
        else {}
    )
    compact_report = {**report, "reliability_map": compact_reliability_map}
    detail_categories = {detail.get("category") for detail in report.get("details", [])}
    artifacts: list[Any] = []
    if written_report_path is not None:
        artifacts.append(
            _agent_artifact("report", written_report_path, "shareable finding report")
        )
    if written_regression_path is not None:
        artifacts.append(
            _agent_artifact("regression", written_regression_path, "generated pytest regressions")
        )
    if written_regression_manifest_path is not None:
        artifacts.append(
            _agent_artifact(
                "regression-manifest",
                written_regression_manifest_path,
                "portable CI bindings for generated regressions",
            )
        )
    if written_config_path is not None:
        artifacts.append(
            _agent_artifact(
                "config-suggestion",
                written_config_path,
                "review-only ordeal.toml snippets",
            )
        )
    if written_support_path is not None:
        artifacts.append(
            _agent_artifact(
                "support-scaffold",
                written_support_path,
                "review-only support scaffold",
            )
        )
    if written_proofs_path is not None:
        artifacts.append(
            _agent_artifact("proof-bundle", written_proofs_path, "machine-readable proof bundles")
        )
    if written_replay_path is not None:
        artifacts.append(
            _agent_artifact("replay-notes", written_replay_path, "minimal replay notes")
        )
    if written_scenario_library_path is not None:
        artifacts.append(
            _agent_artifact(
                "scenario-library",
                written_scenario_library_path,
                "reusable collaborator scenario libraries",
            )
        )
    if written_reliability_map_path is not None:
        artifacts.append(
            _agent_artifact(
                "reliability-map",
                written_reliability_map_path,
                "source-backed operation, fault, and property evidence plan",
            )
        )
    if index_path is not None:
        artifacts.append(_agent_artifact("index", index_path, "artifact index"))
    return _build_agent_envelope_from_report(
        report,
        status=(
            "findings"
            if state.findings
            else (
                "exploratory"
                if detail_categories & _SPECULATIVE_SCAN_CATEGORIES
                else "blocked"
                if any(detail.get("kind") == "blocked" for detail in report.get("details", []))
                else "ok"
            )
        ),
        confidence=_calibrated_scan_confidence(state),
        confidence_basis=(
            (
                "search depth: "
                f"{evidence['search_depth']['functions']} functions, "
                f"{evidence['search_depth']['transitions']} transitions, "
                f"{evidence['search_depth']['checkpoints']} checkpoints"
            ),
            (
                "replayability: "
                f"{evidence['replayability']['replayable_findings']}/"
                f"{evidence['replayability']['total_findings']} findings"
            ),
            (
                "mutation strength: "
                + (
                    f"{evidence['mutation_strength']:.0%}"
                    if evidence["mutation_strength"] is not None
                    else "not measured"
                )
            ),
            f"fixture completeness: {evidence['fixture_completeness']:.0%}",
            f"surface coverage: {evidence['surface_coverage']:.0%}",
            f"blocked targets: {evidence['blocked_functions']}",
        ),
        artifacts=artifacts,
        raw_details={
            "report": compact_report,
            "state": _scan_state_payload(state),
            "seed": getattr(state, "supervisor_info", {}).get("seed"),
            "finding_count": len(report.get("details", [])),
            "gap_count": len(report.get("gaps", [])),
            "evidence_dimensions": evidence,
            "reliability_map": reliability_map,
            "reliability_observations": list(
                getattr(state, "supervisor_info", {}).get("reliability_observations", ())
            ),
        },
        suggested_test_file=(
            _DEFAULT_REGRESSION_PATH
            if any(
                detail.get("kind") not in {"blocked", "precondition"}
                for detail in report.get("details", [])
            )
            else None
        ),
    )
