from __future__ import annotations
# ruff: noqa
# ============================================================================
# Test generation from traces
# ============================================================================


def generate_tests(
    traces: list[Trace],
    *,
    class_path: str | None = None,
) -> str:
    """Generate pytest test functions from exploration traces.

    Turns the most valuable traces into standalone, replayable tests.
    Each test recreates the exact rule/fault sequence that the explorer
    found.

    Args:
        traces: Traces to convert (typically from ``ExplorationResult``).
        class_path: Override the test class import path.

    Returns:
        Python source code for a test module.
    """
    if not traces:
        return ""

    # Use class path from first trace
    cp = class_path or traces[0].test_class
    if ":" not in cp:
        return ""
    module_path, class_name = cp.rsplit(":", 1)

    lines = [
        '"""Generated by ordeal explorer. Do not edit — re-run ordeal explore to regenerate."""',
        "",
        f"from {module_path} import {class_name}",
        "",
    ]

    for trace in traces:
        fn_name = _test_fn_name(trace)
        doc = _test_docstring(trace)
        body = _test_body(trace)
        lines.append("")
        lines.append(f"def {fn_name}():")
        lines.append(f'    """{doc}"""')
        lines.append(f"    machine = {class_name}()")
        lines.append("    try:")
        for stmt in body:
            lines.append(f"        {stmt}")
        lines.append("    finally:")
        lines.append("        machine.teardown()")
        lines.append("")

    return "\n".join(lines)
def _test_fn_name(trace: Trace) -> str:
    """Generate a descriptive test function name."""
    prefix = "test_fail" if trace.failure else "test_path"
    return f"{prefix}_r{trace.run_id}"
def _test_docstring(trace: Trace) -> str:
    """One-line docstring from trace metadata."""
    parts = [f"Run {trace.run_id}"]
    if trace.failure:
        parts.append(f"{trace.failure.error_type}: {trace.failure.error_message[:80]}")
    parts.append(f"{len(trace.steps)} steps")
    if trace.edges_discovered > 0:
        parts.append(f"{trace.edges_discovered} new edges")
    return ", ".join(parts)
def _test_body(trace: Trace) -> list[str]:
    """Convert trace steps to Python statements."""
    stmts: list[str] = []
    for step in trace.steps:
        if step.kind == "fault_toggle":
            if step.name.startswith("+"):
                fault_name = step.name[1:]
                stmts.append(f"# activate fault: {fault_name}")
                stmts.append("for f in machine._faults:")
                stmts.append(f"    if f.name == {fault_name!r}: f.activate()")
            elif step.name.startswith("-"):
                fault_name = step.name[1:]
                stmts.append(f"# deactivate fault: {fault_name}")
                stmts.append("for f in machine._faults:")
                stmts.append(f"    if f.name == {fault_name!r}: f.deactivate()")
        elif step.kind == "rule":
            params = {k: v for k, v in step.params.items() if k != "data"}
            if params:
                param_str = ", ".join(f"{k}={v!r}" for k, v in params.items())
                stmts.append(f"machine.{step.name}({param_str})")
            else:
                stmts.append(f"machine.{step.name}()")
    return stmts
