# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from dataclasses import dataclass
from typing import Any
from . import Fault, PatchFault

"\nThis type stub file was generated by pyright.\n"

def error_on_call(target: str, error: type[Exception] = ..., message: str = ...) -> PatchFault:
    """Make *target* raise *error* on every call — simulates database/cache/service failure."""
    ...

def return_empty(target: str) -> PatchFault:
    """Make *target* return ``None`` on every call while active."""
    ...

def corrupt_output(target: str) -> PatchFault:
    """Replace the output of *target* with random bytes (same length)."""
    ...

def truncate_output(target: str, fraction: float = ...) -> PatchFault:
    """Truncate the output of *target* to *fraction* of its length."""
    ...

class _DiskFullFault(Fault):
    """Simulates disk full by making write-mode ``open()`` and ``os.write()`` fail."""

    def __init__(self) -> None: ...

class _PermissionDeniedFault(Fault):
    """Simulates permission denied on write-mode ``open()``."""

    def __init__(self) -> None: ...

def disk_full() -> Fault:
    """Simulate disk full — all write-mode open() and os.write() fail with ENOSPC.

    **Warning**: patches ``builtins.open`` and ``os.write`` globally.
    """
    ...

def permission_denied() -> Fault:
    """Simulate permission-denied errors on write operations.

    **Warning**: patches ``builtins.open`` globally.
    """
    ...

@dataclass
class _SyntheticSubprocess:
    """Minimal subprocess object used for synthetic child-process failures."""

    args: Any
    returncode: int
    stdout: bytes | str | None
    stderr: bytes | str | None
    _stdout_pipe: bool
    _stderr_pipe: bool

    def __enter__(self) -> _SyntheticSubprocess: ...
    def __exit__(self, *exc: object) -> None: ...
    def poll(self) -> int: ...
    def wait(self, timeout: float | None = ...) -> int: ...
    def communicate(
        self, input: object = ..., timeout: float | None = ...
    ) -> tuple[bytes | str | None, bytes | str | None]: ...
    def kill(self) -> None: ...
    def terminate(self) -> None: ...
    def send_signal(self, sig: int) -> None: ...

class _SubprocessTimeoutFault(PatchFault):
    """Patch ``subprocess.run`` while keeping hit state on the active instance."""

    def __init__(self, target: str, timeout_sec: float) -> None: ...

def subprocess_timeout(target: str, *, timeout_sec: float = ...) -> PatchFault:
    """Make ``subprocess.run``/``subprocess.check_output`` calls matching *target* time out.

    Patches ``subprocess.run`` — when the command string contains *target*,
    raises ``subprocess.TimeoutExpired`` instead of running the process.
    Useful for testing Python↔Rust/C/Go bridges under chaos.

    Works in ChaosTest (nemesis toggles the fault) or as a context manager::

        # In ChaosTest — nemesis toggles automatically
        class KernelChaos(ChaosTest):
            faults = [subprocess_timeout("cargo run")]

            @rule()
            def run_episode(self):
                result = run_kernel(steps=10)  # calls subprocess.run
                always(result.exit_code == 0, "clean exit")

        # As context manager — scoped activation
        with subprocess_timeout("cargo run"):
            result = run_kernel()

    Args:
        target: Substring to match in the command (e.g. ``"cargo run"``).
        timeout_sec: Fake timeout duration for the error.
    """
    ...

def subprocess_exit(
    target: str,
    *,
    returncode: int = ...,
    stdout: bytes | str | None = ...,
    stderr: bytes | str | None = ...,
) -> PatchFault:
    """Make matching subprocesses exit with *returncode*.

    Patches ``subprocess.Popen`` so the child never starts.  This makes
    ``subprocess.run()``, ``subprocess.check_output()``, and direct
    ``Popen`` callers observe a nonzero exit as if the child had failed.

    Args:
        target: Substring to match in the command string.
        returncode: Exit status to report.  Use a negative value only if
            you want to model signal-style death directly.
        stdout: Optional synthetic stdout for the completed process.
        stderr: Optional synthetic stderr for the completed process.
    """
    ...

def subprocess_signal(
    target: str,
    *,
    signum: int = ...,
    stdout: bytes | str | None = ...,
    stderr: bytes | str | None = ...,
) -> PatchFault:
    """Make matching subprocesses die from *signum*.

    The synthetic process reports ``returncode == -signum``, matching
    Python's standard subprocess convention for signal death.

    Args:
        target: Substring to match in the command string.
        signum: Signal number to report as the death cause.
        stdout: Optional synthetic stdout for the completed process.
        stderr: Optional synthetic stderr for the completed process.
    """
    ...

def subprocess_truncate_stdout(target: str, fraction: float = ...) -> PatchFault:
    """Truncate matching subprocess stdout to *fraction* of its length.

    Patches ``subprocess.run`` so the child process still executes, but
    the captured stdout is shortened after the fact.  Useful for testing
    parsers that assume the child always returns a full payload.
    """
    ...

def subprocess_truncate_stderr(target: str, fraction: float = ...) -> PatchFault:
    """Truncate matching subprocess stderr to *fraction* of its length.

    Patches ``subprocess.run`` so the child process still executes, but
    the captured stderr is shortened after the fact.
    """
    ...

def corrupt_stdout(target: str) -> PatchFault:
    """Replace the stdout of subprocess calls matching *target* with random bytes.

    Replaces ``stdout`` in the ``CompletedProcess`` with random bytes,
    simulating garbled FFI output.

    Works in ChaosTest (nemesis toggles the fault) or as a context manager::

        # In ChaosTest
        faults = [corrupt_stdout("my_binary")]

        # As context manager
        with corrupt_stdout("my_binary"):
            result = parse_binary_output()

    Args:
        target: Substring to match in the command.
    """
    ...

def subprocess_delay(target: str, *, delay: float = ...) -> PatchFault:
    """Add *delay* seconds to subprocess calls matching *target*.

    Simulates slow FFI responses — tests timeout handling and
    progress reporting in Python↔Rust/C/Go bridges.

    Works in ChaosTest (nemesis toggles the fault) or as a context manager::

        # In ChaosTest
        faults = [subprocess_delay("cargo run", delay=5.0)]

        # As context manager
        with subprocess_delay("cargo run", delay=5.0):
            result = run_kernel()

    Args:
        target: Substring to match in the command.
        delay: Seconds to sleep before returning the real result.
    """
    ...
