# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from dataclasses import dataclass
from typing import Any, Callable
from ordeal.faults import Fault

__all__ = ["ChaosAPIResult", "auto_faults", "with_chaos", "chaos_api_test"]
_log = ...
_MAX_REF_DEPTH = ...

@dataclass
class _Response:
    """Minimal HTTP response wrapper."""

    status_code: int
    headers: dict[str, str]
    body: bytes

    def json(self) -> Any: ...

@dataclass(frozen=True)
class ChaosAPIResult:
    """Structured result of a chaos API test run.

    Attributes:
        total_requests: Number of API requests executed.
        failures: List of failure dicts with ``type`` and ``error`` keys.
            May also include ``endpoint``, ``method``, ``status_code``,
            and ``active_faults`` when available.
        fault_activations: Mapping of fault name to total activation count.
        duration_seconds: Wall-clock time for the test run.
        deferred_ok: Whether all deferred assertions (``sometimes``,
            ``reachable``) passed.
    """

    total_requests: int
    failures: list[dict[str, Any]]
    fault_activations: dict[str, int]
    duration_seconds: float
    deferred_ok: bool
    traces: tuple = ...
    _used_swarm: bool = ...
    _used_auto_discover: bool = ...
    _used_mutation_targets: bool = ...
    _had_app: bool = ...
    _requested_stateful: bool = ...
    _stateful_links_available: bool = ...
    _used_stateful: bool = ...

    @builtins.property
    def passed(self) -> bool:
        """True if no failures occurred and all deferred assertions passed."""
        ...

    @builtins.property
    def config_used(self) -> dict[str, bool]:
        """Which capabilities were active for this run.

        Compare against the full parameter list of :func:`chaos_api_test`
        to see what's available but wasn't used.
        """
        ...

    def summary(self) -> str:
        """Structured summary with failure categorization.

        Groups failures by type so the output shows what was checked:
        application errors (5xx), protocol violations (Content-Length,
        Transfer-Encoding, body on 204), content errors (invalid JSON,
        missing Content-Type), security (CORS), and cross-request patterns.
        """
        ...

    def __repr__(self) -> str: ...

class _FaultScheduler:
    """Manages fault toggling with optional swarm mode and activation tracking.

    Centralises the fault-management logic shared by :func:`with_chaos`,
    :func:`chaos_api_test`.

    .. note:: Not thread-safe.  Each concurrent context should use its own
       scheduler instance.
    """

    def __init__(
        self,
        faults: list[Fault],
        fault_probability: float = ...,
        seed: int | None = ...,
        swarm: bool = ...,
    ) -> None: ...
    def before_request(self) -> list[str]:
        """Randomly activate faults for one request.

        Returns the names of faults that were activated.
        """
        ...

    def after_request(self) -> None:
        """Reset all faults after a request."""
        ...

class _TraceCollector:
    """Records API calls as TraceStep entries during a test run."""

    def __init__(self) -> None: ...
    def before(self, active_faults: list[str]) -> None:
        """Stash active faults until after_call provides the response."""
        ...

    def after(self, method: str, path: str, status_code: int | None) -> None:
        """Record a completed API call."""
        ...

    def to_trace(self, *, seed: int, label: str, failure: Any = ...) -> Any:
        """Build a Trace object from collected steps."""
        ...

_SEMANTIC_RETURNS: dict[str, list[tuple[str, Any]]] = ...

def auto_faults(
    targets: list[str], *, operators: list[str] | None = ..., include_semantic: bool = ...
) -> list[Fault]:
    """Generate faults from source code: mutations + semantic + dependency.

    1. **Mutation** — AST mutations (flip comparisons, negate conditions).
    2. **Semantic** — type-aware: returns_none, raises, stale, type sentinels.
    3. **Dependency** — error_on_call for same-module callees.
    """
    ...

@dataclass
class _Endpoint:
    """Parsed representation of a single API endpoint."""

    method: str
    path: str
    path_params: list[dict[str, Any]] = ...
    query_params: list[dict[str, Any]] = ...
    header_params: list[dict[str, Any]] = ...
    request_body: dict | None = ...
    response_codes: set[int] = ...
    response_schemas: dict[int, dict] = ...
    operation_id: str | None = ...
    response_links: dict[int, list[_Link]] = ...

@dataclass(frozen=True)
class _Link:
    """Supported subset of the OpenAPI Link Object."""

    operation_id: str | None = ...
    operation_ref: str | None = ...
    parameters: dict[str, Any] = ...
    request_body: Any = ...

_PATH_PARAM_RE = ...

@dataclass
class _APICase:
    """Generated test case for one API call."""

    method: str
    path: str
    headers: dict[str, str]
    query_params: dict[str, str]
    body: Any
    endpoint_path: str
    path_params: dict[str, Any] = ...

_MISSING = ...

class _ASGIClient:
    """Minimal ASGI test client (no framework dependency)."""

    def __init__(self, app: Any) -> None: ...
    def request(
        self,
        method: str,
        path: str,
        headers: dict[str, str] | None = ...,
        body: bytes | None = ...,
    ) -> _Response: ...
    def get_schema(self, schema_path: str = ...) -> dict:
        """Fetch and parse the OpenAPI schema from the app."""
        ...

class _WSGIClient:
    """Minimal WSGI test client (PEP 3333)."""

    def __init__(self, app: Any) -> None: ...
    def request(
        self,
        method: str,
        path: str,
        headers: dict[str, str] | None = ...,
        body: bytes | None = ...,
    ) -> _Response: ...
    def get_schema(self, schema_path: str = ...) -> dict:
        """Fetch and parse the OpenAPI schema from the app."""
        ...

class _URLClient:
    """HTTP client for remote servers via urllib (stdlib)."""

    def __init__(self, base_url: str) -> None: ...
    def request(
        self,
        method: str,
        path: str,
        headers: dict[str, str] | None = ...,
        body: bytes | None = ...,
    ) -> _Response: ...
    def get_schema(self, schema_url: str = ...) -> dict:
        """Fetch and parse the OpenAPI schema from a URL."""
        ...

def with_chaos(
    faults: list[Fault],
    *,
    fault_probability: float = ...,
    seed: int | None = ...,
    swarm: bool = ...,
) -> Callable:
    """Decorator that wraps a test function with fault injection.

    Before each call, randomly activates/deactivates faults.
    After the call, resets all faults to avoid cross-request interference.

    Args:
        faults: Fault instances to inject.
        fault_probability: Probability of each fault being active per request.
        seed: Random seed for reproducibility.
        swarm: Use swarm mode -- pick a random subset of faults once, then
            toggle only those for the lifetime of the wrapper.
    """
    ...

def chaos_api_test(
    schema_url: str | None = ...,
    *,
    app: Any = ...,
    wsgi: bool = ...,
    schema_path: str = ...,
    faults: list[Fault] | None = ...,
    fault_probability: float = ...,
    seed: int | None = ...,
    swarm: bool = ...,
    base_url: str | None = ...,
    auth: Any = ...,
    headers: dict[str, str] | None = ...,
    stateful: bool = ...,
    max_examples: int = ...,
    record_traces: bool = ...,
    mutation_targets: list[str] | None = ...,
    auto_discover: bool = ...,
) -> ChaosAPIResult:
    """Run OpenAPI chaos testing against an API with fault injection.

    Loads the OpenAPI schema, generates test cases via Hypothesis, and
    randomly injects faults while exercising every API endpoint.

    **What it validates automatically (no configuration needed):**

    Every response is checked for HTTP protocol violations that cause
    real production failures but are invisible at the application layer:

    - **5xx status codes** — application errors under fault injection
    - **Content-Length mismatch** — middleware modifies body after headers
      (causes uvicorn RuntimeError)
    - **Content-Length + Transfer-Encoding** — RFC 7230 §3.3.3 violation
      (proxies drop the connection)
    - **Body on 204/304** — RFC violation, proxy misframing
    - **JSON Content-Type with non-JSON body** — clients crash on .json()
    - **Missing Content-Type** — MIME sniffing, XSS risk
    - **CORS headers lost under faults** — error handlers bypass middleware

    - **Schema violation** — response body doesn't match declared OpenAPI schema
      (missing required fields, wrong types)

    After all requests, cross-request analysis detects:

    - **Inconsistent error format** — same endpoint returns JSON and HTML
    - **CORS present normally, missing under faults** — middleware bypass
    - **Latency spike under faults** — 5x+ slower under faults, missing timeout

    Supports three schema sources (exactly one of *schema_url* or *app*
    must be provided):

    - **URL**: pass *schema_url* (requires a running server).
    - **ASGI**: pass *app* (in-process, no server needed).
    - **WSGI**: pass *app* and ``wsgi=True`` (in-process, no server needed).

    Args:
        schema_url: URL to an OpenAPI schema (e.g.
            ``"http://localhost:8080/openapi.json"``).
        app: An ASGI or WSGI application instance for in-process testing.
        wsgi: Set ``True`` when *app* is a WSGI application (default assumes
            ASGI).
        schema_path: Path to the schema endpoint within *app* (default
            ``"/openapi.json"``).  Only used with *app*.
        faults: Fault instances to inject server-side.
        fault_probability: Probability of each fault being active per request.
        seed: Random seed for reproducibility.
        swarm: Use swarm mode -- random fault subset per run for better
            aggregate coverage.
        base_url: Override base URL for API calls (URL mode only).
        auth: String auth header value (e.g. ``"Bearer ..."``) or use
            *headers* for full control.
        headers: Extra headers to include in every request.
        stateful: If ``True``, follow supported OpenAPI response links
            (``operationId`` and local ``operationRef``) to turn a single
            request into a short stateful sequence. Falls back to independent
            endpoint sampling when the schema has no supported links.
        max_examples: Maximum test cases to generate.
        record_traces: If ``True``, record API calls as ordeal traces.
        mutation_targets: Dotted paths to functions for auto-fault generation
            via AST mutations, semantic faults, and dependency faults.
        auto_discover: If ``True`` and *app* is provided, BFS app routes to
            auto-discover fault targets.

    Returns:
        :class:`ChaosAPIResult` with request counts, failures, fault
        activation stats, and deferred assertion results.
    """
    ...

def catalog() -> list[dict[str, str]]:
    """Discover public entry points in this integration module.

    Fully automatic — scans all public functions defined in this module.
    """
    ...
