# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from dataclasses import dataclass
from typing import Any

"\nThis type stub file was generated by pyright.\n"
_SCHEMA = ...

class ObservationError(RuntimeError):
    """Signal that a value cannot be isolated or represented losslessly."""

    ...

@dataclass(frozen=True)
class CanonicalObservation:
    """One typed structural graph and its deterministic replay signature."""

    payload: dict[str, Any]
    signature: str
    public_value: Any
    json_value: Any
    _mutable_ids: frozenset[int] = ...

class _SnapshotBuilder:
    """Encode one Python value as a typed object graph without equality or repr."""

    def __init__(self, *, label: str) -> None: ...
    def build(self, value: Any) -> dict[str, Any]:
        """Return the complete canonical graph payload."""
        ...

def observe(value: Any, *, label: str = ...) -> CanonicalObservation:
    """Structurally snapshot one value or raise when no lossless encoding exists."""
    ...

def observations_equal(left: CanonicalObservation, right: CanonicalObservation) -> bool:
    """Compare structural observations without candidate equality methods."""
    ...

def exact_replay_match(
    expected: CanonicalObservation,
    observed: CanonicalObservation,
    *,
    recorded_expected_signature: str,
) -> bool:
    """Require the recorded, expected, and observed signatures to agree exactly."""
    ...

def isolated_deepcopy(value: Any, *, label: str, disjoint_from: tuple[Any, ...] = ...) -> Any:
    """Deep-copy one value and reject structural drift or retained mutable aliases."""
    ...
