# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import os
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

"\nThis type stub file was generated by pyright.\n"
RevisionDiffStatus = Literal["divergent", "no_divergence_observed", "inconclusive"]

class RevisionDiffError(RuntimeError):
    """Raised when an isolated revision comparison cannot be executed."""

    ...

@dataclass(frozen=True)
class RevisionRuntime:
    """Execution evidence for one side of a revision diff."""

    ref: str
    commit: str
    pid: int
    worktree: str

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe runtime record."""
        ...

@dataclass(frozen=True)
class RevisionMismatch:
    """One same-input behavior mismatch across two revisions."""

    args: Any
    canonical_args: dict[str, Any]
    replay_args: object
    base: dict[str, Any]
    candidate: dict[str, Any]
    artifact: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe mismatch record."""
        ...

@dataclass(frozen=True)
class RevisionFunctionDiff:
    """Measured comparison for one function shared by both revisions."""

    name: str
    base_signature: str
    candidate_signature: str
    total: int
    mismatch_count: int
    mismatches: tuple[RevisionMismatch, ...] = ...
    blocked_reason: str | None = ...

    @builtins.property
    def signature_changed(self) -> bool:
        """Whether the callable signature changed across revisions."""
        ...

    @builtins.property
    def supported_mismatch_count(self) -> int:
        """Return mismatches whose full replay and source bindings verified."""
        ...

    @builtins.property
    def status(self) -> RevisionDiffStatus:
        """Return the claim-scoped status for this function."""
        ...

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-safe function result."""
        ...

@dataclass(frozen=True)
class RevisionDiffResult:
    """Result of comparing one target across two isolated Git revisions."""

    target: str
    base: RevisionRuntime
    candidate: RevisionRuntime
    functions: tuple[RevisionFunctionDiff, ...]
    added_functions: tuple[str, ...] = ...
    removed_functions: tuple[str, ...] = ...
    candidate_resolution_error: str | None = ...
    max_examples: int = ...
    seed: int = ...
    rtol: float | None = ...
    atol: float | None = ...
    replay_attempts: int = ...
    mode: Literal["function", "system"] = ...
    system_sequence: tuple[dict[str, Any], ...] = ...
    include_private: bool = ...
    fixture_registries: tuple[str, ...] = ...

    @builtins.property
    def total(self) -> int:
        """Return the number of same-input examples evaluated."""
        ...

    @builtins.property
    def mismatch_count(self) -> int:
        """Return the number of observed behavior mismatches."""
        ...

    @builtins.property
    def supported_mismatch_count(self) -> int:
        """Return the number of source-bound, fully replayed mismatches."""
        ...

    @builtins.property
    def isolated(self) -> bool:
        """Whether the two workers ran from distinct worktrees."""
        ...

    @builtins.property
    def status(self) -> RevisionDiffStatus:
        """Return a bounded claim; sampled agreement is never equivalence."""
        ...

    @builtins.property
    def no_divergence_found(self) -> bool:
        """Whether no divergence was observed within the measured scope."""
        ...

    @builtins.property
    def artifacts(self) -> tuple[dict[str, Any], ...]:
        """Return every source-bound runtime divergence artifact."""
        ...

    def summary(self) -> str:
        """Return a concise human-readable revision comparison."""
        ...

    def to_dict(self) -> dict[str, Any]:
        """Return the stable JSON artifact payload."""
        ...

def default_base_ref(repo: str | os.PathLike[str] | None = ...) -> str:
    """Choose the remote default branch, main branch, or commit parent."""
    ...

_REVISION_REGRESSION_TEST = ...

def replay_revision_regression_case(case: Mapping[str, Any]) -> None:
    """Re-run one pinned base-to-current revision witness in CI."""
    ...

def persist_revision_regression(
    result: RevisionDiffResult, *, evidence_path: Path, regression_path: Path, manifest_path: Path
) -> tuple[Path | None, str | None, str | None]:
    """Persist and register a replay of one divergent Git-revision result."""
    ...

def run_revision_diff(
    target: str,
    *,
    base_ref: str | None = ...,
    candidate_ref: str = ...,
    repo: str | os.PathLike[str] | None = ...,
    max_examples: int = ...,
    seed: int = ...,
    rtol: float | None = ...,
    atol: float | None = ...,
    include_private: bool = ...,
    fixture_registries: Sequence[str] = ...,
    replay_attempts: int = ...,
    sequence: Sequence[Mapping[str, Any]] | None = ...,
    exact_cases: Mapping[str, Sequence[object]] | None = ...,
) -> RevisionDiffResult:
    """Compare one target across two detached worktrees and subprocesses.

    Pass a JSON-safe operation/fault ``sequence`` to treat *target* as a
    zero-argument system factory. Fault events call ``system.apply_fault(event)``.
    """
    ...
