# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from collections.abc import Callable, Iterable, Mapping
from dataclasses import dataclass
from typing import Any

"\nThis type stub file was generated by pyright.\n"

@dataclass
class Property:
    """A tracked property and its accumulated results."""

    name: str
    type: str
    hits: int = ...
    passes: int = ...
    failures: int = ...
    first_failure_details: dict[str, Any] | None = ...

    @builtins.property
    def passed(self) -> bool:
        """Whether this property passed, according to its type's semantics."""
        ...

    @builtins.property
    def summary(self) -> str:
        """Human-readable one-line summary: ``PASS name (type: N hits)`` or ``FAIL ...``."""
        ...

    @builtins.property
    def evidence_status(self) -> str:
        """Return ``observed``, ``violated``, or ``unexercised`` evidence status."""
        ...

@dataclass
class ReliabilityCell:
    """One operation × fault × property reliability-coverage cell.

    Status is always derived from assertion type and observation counters.
    Zero hits means ``NOT EXERCISED``; observed cells become ``PASS`` or
    ``FAIL`` according to the normal assertion semantics.
    """

    operation: str
    fault: str
    property: str
    type: str
    hits: int = ...
    passes: int = ...
    failures: int = ...
    first_failure_details: dict[str, Any] | None = ...

    @builtins.property
    def status(self) -> str:
        """Return ``PASS``, ``FAIL``, or ``NOT EXERCISED`` from observations."""
        ...

    def as_dict(self) -> dict[str, Any]:
        """Return a stable, JSON-serializable representation of this cell."""
        ...

class PropertyTracker:
    """Thread-safe accumulator for property assertion results.

    All access to ``active``, properties, and reliability cells is guarded by
    a lock, making this safe for free-threaded Python 3.13+.
    """

    def __init__(self) -> None: ...
    @builtins.property
    def active(self) -> bool: ...
    @active.setter
    def active(self, value: bool) -> None: ...
    def reset(self) -> None: ...
    def snapshot(
        self,
    ) -> tuple[bool, dict[str, Property], dict[tuple[str, str, str], ReliabilityCell]]:
        """Return a deep-copied snapshot for temporary lifecycle overrides."""
        ...

    def restore(
        self,
        snapshot: tuple[bool, dict[str, Property], dict[tuple[str, str, str], ReliabilityCell]],
    ) -> None:
        """Restore a snapshot previously returned by ``snapshot()``."""
        ...

    def declare_reliability(
        self,
        name: str,
        prop_type: str,
        *,
        operation: str,
        fault: str,
        details: dict[str, Any] | None = ...,
    ) -> bool:
        """Declare an expected matrix cell without claiming it was exercised."""
        ...

    def merge_reliability(self, rows: Iterable[Mapping[str, Any]]) -> None:
        """Merge JSON-safe reliability rows produced by another test worker."""
        ...

    def record(
        self,
        name: str,
        prop_type: str,
        condition: bool,
        details: dict[str, Any] | None = ...,
        *,
        operation: str | None = ...,
        fault: str | None = ...,
    ) -> bool:
        """Record a property observation. Returns True if tracker was active."""
        ...

    def record_hit(
        self, name: str, prop_type: str, *, operation: str | None = ..., fault: str | None = ...
    ) -> bool:
        """Record a code-path hit. Returns True if tracker was active."""
        ...

    def counter_snapshot(self) -> dict[str, tuple[str, int, int, int]]:
        """Return compact property counters for a later event delta.

        This avoids allocating ``Property`` result lists when a hot caller
        only needs to know which properties changed since one rule step.
        """
        ...

    def counter_delta(
        self, before: dict[str, tuple[str, int, int, int]]
    ) -> list[dict[str, int | str]]:
        """Return counter changes since :meth:`counter_snapshot`.

        The event-shaped result lets Explorer update behavior telemetry
        without constructing a second full counter snapshot.
        """
        ...

    @builtins.property
    def results(self) -> list[Property]:
        """All tracked properties (both passed and failed)."""
        ...

    @builtins.property
    def failures(self) -> list[Property]:
        """Only the properties that have not passed."""
        ...

    @builtins.property
    def reliability_results(self) -> list[ReliabilityCell]:
        """Reliability cells sorted by operation, fault, then property."""
        ...

tracker = ...
_DEFERRED_PROPERTY_TYPES = ...

def report() -> dict[str, Any]:
    """Structured summary of all tracked property assertions.

    Returns a dict with ``passed`` and ``failed`` lists.  When reliability
    dimensions were supplied, the result also has ``reliability_coverage``
    with JSON-serializable rows, explicit dimensions, and status counts.  The
    optional key is absent when no dimensional cells were declared or observed.

    Reliability rows are sorted by operation, fault, then property.  Each row
    includes the assertion type, derived status, and hit/pass/failure counters.
    Under pytest-xdist, worker rows are merged before the controller renders
    its terminal summary.

    Call at the end of a test session for a preflight checklist::

        from ordeal.assertions import report
        r = report()
        for p in r["failed"]:
            print(p["summary"])
    """
    ...

def declare(
    name: str,
    prop_type: str,
    *,
    operation: str | None = ...,
    fault: str | None = ...,
    **details: Any,
) -> None:
    """Register a deferred property or reliability expectation before observations.

    ``sometimes()`` and ``reachable()`` are observational by default: if the
    call site is never reached, there is nothing to track.  ``declare()``
    makes the expectation explicit so the property can fail at session end
    even when it was never observed.  With ``operation`` and ``fault``, all
    four property types can be declared as reliability cells; an unseen cell
    reports ``NOT EXERCISED`` rather than pretending it passed or failed.

    Typical use::

        declare("timeout handler runs", "reachable")
        declare("cache warms up", "sometimes")
        declare(
            "eventual_commit",
            "always",
            operation="create_order",
            fault="worker_restart",
        )

    Then, elsewhere in the code under test::

        reachable("timeout handler runs")
        sometimes(cache_hit, "cache warms up")

    Args:
        name: Human-readable property label.
        prop_type: ``"reachable"`` or ``"sometimes"`` for a plain
            declaration; any assertion type for a reliability cell.
        operation: Operation dimension for reliability coverage.
        fault: Fault dimension for reliability coverage. Must be provided
            together with ``operation``.
        **details: Optional metadata stored with the property.
    """
    ...

def always(
    condition: bool,
    name: str,
    *,
    mute: bool = ...,
    operation: str | None = ...,
    fault: str | None = ...,
    **details: Any,
) -> None:
    """Assert *condition* every time — raises immediately on violation.

    Raises ``AssertionError`` immediately on violation — whether or not
    the tracker is active.  Violations are never silent by default.

    Pass ``mute=True`` to record the violation without raising.  The
    violation still appears in the property report (when ``--chaos`` is
    active) — it is tracked, not hidden.  Use this when a known issue
    is too loud and you need to focus on something else::

        always(not math.isnan(x), "no NaN", mute=True)  # tracked, not fatal

    When the tracker IS active (``--chaos``), the result is also recorded
    for the property report regardless of ``mute``.

    Args:
        condition: The boolean condition that must hold.
        name: Human-readable label for this assertion.
        mute: If ``True``, record violation without raising.
        operation: Optional operation dimension for reliability coverage.
        fault: Optional fault dimension. Must be provided with ``operation``.
        **details: Extra context included in the error message.
    """
    ...

def sometimes(
    condition: bool | Callable[[], bool],
    name: str,
    *,
    attempts: int | None = ...,
    warn: bool = ...,
    operation: str | None = ...,
    fault: str | None = ...,
    **details: Any,
) -> None:
    """Assert *condition* at least once — deferred, checked at session end.

    Simple — deferred, checked at session end::

        sometimes(score > 0.5, "high scores exist")

    With ``warn=True`` — visible in normal pytest (no --chaos needed)::

        sometimes(score > 0.5, "high scores exist", warn=True)

    With ``attempts`` — immediate, standalone, no tracker needed::

        sometimes(lambda: cache.hit_rate() > 0, "cache warms up", attempts=100)

    Args:
        condition: Boolean or callable condition that should eventually hold.
        name: Human-readable label for this assertion.
        attempts: Polling attempts for immediate standalone use.
        warn: If True, print to stderr even when tracker is inactive.
            Useful for pre-flight checklists where findings should be
            visible in normal test runs.
        operation: Optional operation dimension for reliability coverage.
        fault: Optional fault dimension. Must be provided with ``operation``.
        **details: Extra context stored with a first failure.
    """
    ...

def reachable(
    name: str, *, operation: str | None = ..., fault: str | None = ..., **details: Any
) -> None:
    """Assert this code path executes at least once — deferred, checked at session end.

    Args:
        name: Human-readable label for this reachability assertion.
        operation: Optional operation dimension for reliability coverage.
        fault: Optional fault dimension. Must be provided with ``operation``.
        **details: Extra context for the property report.
    """
    ...

def unreachable(
    name: str,
    *,
    mute: bool = ...,
    operation: str | None = ...,
    fault: str | None = ...,
    **details: Any,
) -> None:
    """Assert this code path never executes — raises immediately if reached.

    Raises ``AssertionError`` immediately — whether or not the tracker
    is active.  Violations are never silent by default.

    Pass ``mute=True`` to record the hit without raising.  The hit
    still appears in the property report — it is tracked, not hidden.

    Args:
        name: Human-readable label for this assertion.
        mute: If ``True``, record the hit without raising.
        operation: Optional operation dimension for reliability coverage.
        fault: Optional fault dimension. Must be provided with ``operation``.
        **details: Extra context included in the error message.
    """
    ...

def catalog() -> list[dict[str, str]]:
    """Discover all assertion functions via runtime introspection.

    Returns a list of dicts with ``name``, ``signature``, and ``doc``.
    Fully automatic — scans all public functions in this module.
    New assertion functions appear without registration.
    """
    ...
