# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import enum
from dataclasses import dataclass
from typing import Any, Literal, Mapping, Sequence

"\nThis type stub file was generated by pyright.\n"
SUBPROCESS_TIMEOUT_SECONDS: int = ...
COVERAGE_TOLERANCE_PCT: float = ...
MAX_SUGGESTIONS: int = ...
MINE_EXAMPLES_FOR_GENERATED_TEST: int = ...
MIN_SAMPLES_FOR_PROPERTY: int = ...
LINE_BLOCK_GAP: int = ...
DISPLAY_CAP: int = ...
SOURCE_TRUNCATION: int = ...
AuditValidationMode = Literal["fast", "deep"]
FunctionAuditStatus = Literal["exercised", "exploratory", "uncovered"]
EvidenceLabel = Literal["verified", "inferred", "none"]

@dataclass(slots=True)
class FunctionAudit:
    """Function-level audit evidence and status."""

    name: str
    status: FunctionAuditStatus
    epistemic: EvidenceLabel
    covered_body_lines: int = ...
    total_body_lines: int = ...
    evidence: list[dict[str, str]] = ...

    def summary_label(self) -> str:
        """Return a compact label suitable for audit summaries."""
        ...

@dataclass(slots=True)
class TestFileEvidence:
    """Evidence that a test file belongs to the target module."""

    path: str
    basis: Literal["filename", "import", "pytest_collection"]
    epistemic: EvidenceLabel
    nodeids: list[str] = ...

_MUTATION_SCORE_RE = ...

class Status(enum.Enum):
    """Epistemic status of a measurement.

    Every number the audit produces MUST be one of these.  The consumer
    MUST check status before using the value.
    """

    VERIFIED = ...
    FAILED = ...

@dataclass(frozen=True, slots=True)
class CoverageResult:
    """Structured coverage data from a reliable source.

    Fields match the coverage.py JSON schema (v7+).
    The ``source`` field documents HOW this was measured.
    """

    percent: float
    total_statements: int
    missing_count: int
    missing_lines: frozenset[int]
    source: str
    ...

@dataclass(frozen=True, slots=True)
class CoverageMeasurement:
    """A coverage measurement with epistemic status.

    Check ``.status`` before using ``.result``.  If status is FAILED,
    ``.result`` is None and ``.error`` explains why.
    """

    status: Status
    result: CoverageResult | None = ...
    error: str | None = ...

    @builtins.property
    def percent(self) -> float:
        """Coverage percentage, or 0.0 if measurement failed."""
        ...

    @builtins.property
    def missing_lines(self) -> frozenset[int]:
        """Set of uncovered line numbers, or empty if measurement failed."""
        ...

def wilson_lower(successes: int, total: int, z: float = ...) -> float:
    """Lower bound of the Wilson score confidence interval.

    For a property that held in ``successes`` out of ``total`` samples,
    this returns the lower bound at the confidence level determined by
    ``z`` (default 1.96 = 95% confidence).

    Example: 500/500 at 95% CI → lower bound ≈ 0.994.
    This means "holds with ≥99.4% probability", not "always holds".

    **Why Wilson:** The normal approximation breaks near 0% and 100%.
    Wilson is accurate for all sample sizes and hit rates.

    Reference: Wilson, E.B. (1927). "Probable inference, the law of
    succession, and statistical inference". JASA 22(158):209-212.
    """
    ...

_PROPERTY_TO_RELATION: dict[str, dict[str, str]] = ...

@dataclass
class ModuleAudit:
    """Audit result for one module.

    Every numeric field is accompanied by a status indicator.
    If a measurement failed, the corresponding field is 0 and the
    ``warnings`` list explains why.
    """

    module: str
    current_test_count: int = ...
    current_test_lines: int = ...
    current_coverage: CoverageMeasurement = ...
    migrated_test_count: int = ...
    migrated_lines: int = ...
    migrated_coverage: CoverageMeasurement = ...
    mined_properties: list[str] = ...
    mutation_score: str = ...
    validation_mode: AuditValidationMode = ...
    gap_functions: list[str] = ...
    total_functions: int = ...
    function_audits: list[FunctionAudit] = ...
    suggestions: list[str] = ...
    suggested_relations: list[dict[str, str]] = ...
    mutation_gaps: list[dict[str, str]] = ...
    weakest_tests: list[dict[str, int | str]] = ...
    mutation_gap_stubs: list[dict[str, str]] = ...
    mutation_targets: list[dict[str, Any]] = ...
    contract_findings: list[dict[str, Any]] = ...
    blocking_reason: str | None = ...
    harness_hints: list[dict[str, Any]] = ...
    surface: list[dict[str, Any]] = ...
    not_checked: list[str] = ...
    warnings: list[str] = ...
    generated_test: str = ...

    @builtins.property
    def coverage_preserved(self) -> bool:
        """True if migrated coverage >= current coverage - tolerance.

        Returns False if either measurement failed.
        """
        ...

    def summary(self) -> str:
        """Human-readable one-module report with epistemic labels."""
        ...

    def mutation_validation_view(self) -> dict[str, object]:
        """Return a compact mutation-validation view for audit consumers."""
        ...

    def test_protection_view(self) -> dict[str, object]:
        """Decide whether the resulting checks protect the measured module behavior.

        Mutation survival is decisive even at 100% line coverage. Coverage and
        property evidence expose what was not exercised or did not discriminate,
        while failed measurements remain inconclusive instead of becoming zeroes.

        This module-level view describes the generated/migrated checks: their
        verified line coverage plus aggregated mined-property mutation results.
        Use ``mutate()`` and ``MutationResult.test_protection_view()`` to judge
        the selected existing test suite directly.
        """
        ...

    def evidence_views(self) -> dict[str, dict[str, object]]:
        """Return normalized current/generated/combined audit evidence views."""
        ...

    @builtins.property
    def mutation_score_counts(self) -> tuple[int, int] | None:
        """Exact ``(killed, total)`` counts parsed from ``mutation_score``."""
        ...

    @builtins.property
    def mutation_score_fraction(self) -> float | None:
        """Exact mutation score as a fraction, or ``None`` when unavailable."""
        ...

    @builtins.property
    def function_audit_counts(self) -> dict[str, int]:
        """Count function audits by epistemic status."""
        ...

    @builtins.property
    def direct_test_gap_counts(self) -> dict[str, int]:
        """Count function audits that do not satisfy the direct-test gate."""
        ...

    @builtins.property
    def direct_test_gaps(self) -> list[FunctionAudit]:
        """Return functions that still lack direct verified tests."""
        ...

    @builtins.property
    def has_direct_test_gaps(self) -> bool:
        """True when any function is only exploratory or fully uncovered."""
        ...

    @builtins.property
    def fixture_completeness(self) -> float:
        """Fraction of discovered functions that ordeal could execute directly."""
        ...

@dataclass(frozen=True, slots=True)
class _AuditValidationTask:
    """Serializable, immutable input for one isolated validation target."""

    target_path: str
    max_examples: int
    validation_mode: AuditValidationMode
    seed: int
    disk_mutation: bool
    payload: bytes
    ...

@dataclass(frozen=True, slots=True)
class _AuditMutantEvidence:
    """Immutable evidence for one mutant returned by a validation worker."""

    mutant_id: str
    description: str
    location: str
    source_line: str
    remediation: str
    killed: bool
    killers: tuple[str, ...]
    ...

@dataclass(frozen=True, slots=True)
class _AuditValidationEvidence:
    """Immutable worker output merged into ``ModuleAudit`` by the parent."""

    target_path: str
    seed: int
    killed: int
    total: int
    view_json: str
    mutants: tuple[_AuditMutantEvidence, ...]
    stub: str
    ...

_AUDIT_VALIDATION_SOURCE_LOCK: Any | None = ...

def audit(
    module: str,
    *,
    targets: Sequence[Any] | None = ...,
    test_dir: str = ...,
    max_examples: int = ...,
    workers: int = ...,
    validation_mode: AuditValidationMode = ...,
    contract_checks: Mapping[str, Sequence[Any]] | None = ...,
    min_fixture_completeness: float = ...,
) -> ModuleAudit:
    """Audit a module: measure current tests vs ordeal-migrated tests.

    Runs BOTH test suites and MEASURES coverage.  Every number in the
    result is either ``[verified]`` or ``FAILED: reason``.

    The "migrated" test combines ordeal ``fuzz()`` (crash safety) with
    mined property descriptions.  The generated file is written to
    ``.ordeal/test_<mod>_migrated.py`` for inspection and debugging.

    Args:
        module: Dotted module path (e.g., ``"myapp.scoring"``).
        test_dir: Directory containing existing tests.
        max_examples: Hypothesis examples per function.
        workers: Isolated processes for mutation validation. ``1`` (default)
            keeps validation serial; higher values preserve target order and
            use deterministic per-target seeds without promising a speedup.
        validation_mode: ``"fast"`` replays mined inputs against mutants.
            ``"deep"`` replays mined inputs, then re-mines each mutant.
        contract_checks: Explicit semantic contract probes keyed by callable name.
        min_fixture_completeness: Minimum runnable-target fraction required before
            audit spends time on migrated-test generation and mutation checks.

    Returns:
        A ``ModuleAudit`` with verified or explicitly-failed measurements.
    """
    ...

def audit_report(
    modules: list[str],
    *,
    test_dir: str = ...,
    max_examples: int = ...,
    workers: int = ...,
    validation_mode: AuditValidationMode = ...,
) -> str:
    """Audit multiple modules and produce a summary report.

    Returns a formatted string suitable for terminal output.
    Every number is labeled ``[verified]`` or ``FAILED``::

        from ordeal.audit import audit_report

        print(audit_report(["myapp.scoring", "myapp.utils"]))
        # ordeal audit
        #   myapp.scoring
        #     current:  33 tests | 343 lines | 98% coverage [verified]
        #     migrated: 12 tests | 130 lines | 96% coverage [verified]
        #     saving:   64% fewer tests | 62% less code | same coverage
        #   total:
        #     current:  55 tests | 500 lines
        #     migrated: 20 tests | 200 lines

    Args:
        modules: Dotted module paths to audit (e.g. ``["myapp.scoring"]``).
        test_dir: Directory containing test files (default ``"tests"``).
        max_examples: Hypothesis examples for property mining per function.
        workers: Parallel workers for mutation validation in each module audit.
        validation_mode: ``"fast"`` replay or ``"deep"`` replay + re-mining.
    """
    ...
