# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import ast
import hypothesis.strategies as st
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any, Callable, Literal
from ordeal.faults import Fault
from ordeal.invariants import Invariant

"\nThis type stub file was generated by pyright.\n"

@dataclass
class FunctionResult:
    """Result of testing a single function."""

    name: str
    passed: bool
    execution_ok: bool = ...
    verdict: str = ...
    error: str | None = ...
    error_type: str | None = ...
    failing_args: dict[str, Any] | None = ...
    crash_category: str | None = ...
    property_violations: list[str] = ...
    property_violation_details: list[dict[str, Any]] = ...
    contract_violations: list[str] = ...
    contract_violation_details: list[dict[str, Any]] = ...
    replayable: bool | None = ...
    replay_attempts: int = ...
    replay_matches: int = ...
    minimization: dict[str, Any] | None = ...
    contract_fit: float | None = ...
    reachability: float | None = ...
    realism: float | None = ...
    sink_signal: float | None = ...
    sink_categories: list[str] = ...
    input_sources: list[dict[str, str]] = ...
    input_source: str | None = ...
    proof_bundle: dict[str, Any] | None = ...
    source_sha256: str | None = ...
    limitation_kind: str | None = ...
    blocking_reason: str | None = ...

    def __post_init__(self) -> None:
        """Normalize legacy manual constructions onto the verdict model."""
        ...

    @builtins.property
    def promoted(self) -> bool:
        """Whether this result should count as a promoted failure/finding."""
        ...

    @builtins.property
    def exploratory(self) -> bool:
        """Whether this result is exploratory instead of promoted."""
        ...

    def __str__(self) -> str: ...

ScanMode = Literal["coverage_gap", "evidence", "real_bug", "candidate"]
_SCAN_MODE_ALIASES: dict[str, Literal["coverage_gap", "real_bug"]] = ...
_PROMOTED_SCAN_VERDICTS = ...
_REPLAY_MATCH_BASIS = ...
_CONTRACT_GROUP_ALIASES: dict[str, tuple[str, ...]] = ...
_SECURITY_SINK_WEIGHTS: dict[str, float] = ...
_SECURITY_BUCKET_TO_SINKS: dict[str, tuple[str, ...]] = ...
_SECURITY_PROBE_VALUES: dict[str, tuple[Any, ...]] = ...
_SECURITY_ARTIFACT_MUTATION_VALUES: dict[str, tuple[Any, ...]] = ...
_SHELL_INJECTION_PROBE_VALUE = ...
_SHELL_INJECTION_META_CHARS = ...
_SHELL_TAINT_CLEAN = ...
_SHELL_TAINT_SAFE = ...
_SHELL_TAINT_UNSAFE = ...
_DEFAULT_SHELL_INJECTION_SINK_SPECS: tuple[dict[str, Any], ...] = ...
_SECURITY_SHAPER_TOKENS = ...
_SECURITY_SIDE_EFFECT_TOKENS = ...

@dataclass(frozen=True)
class ContractCheck:
    """Explicit semantic contract probe for a scanned callable."""

    name: str
    predicate: Callable[[Any], bool] = ...
    kwargs: dict[str, Any] = ...
    summary: str | None = ...
    metadata: dict[str, Any] = ...

@dataclass(frozen=True)
class _ShellInjectionFlow:
    """One static shell-injection path from input to sink."""

    sink: str
    line: int | None = ...
    parameter: str | int | None = ...
    call_path: tuple[str, ...] = ...
    source_params: tuple[str, ...] = ...

class ContractNotApplicable(RuntimeError):
    """Signal that a semantic contract does not apply to one observed output."""

    ...

@dataclass
class ScanResult:
    """Result of scanning a module."""

    module: str
    functions: list[FunctionResult] = ...
    skipped: list[tuple[str, str]] = ...
    expected_failure_names: list[str] = ...

    @builtins.property
    def results(self) -> list[FunctionResult]:
        """Deprecated alias for ``.functions``."""
        ...

    @builtins.property
    def expected_failures(self) -> list[FunctionResult]:
        """Functions that failed but were listed in *expected_failures*."""
        ...

    @builtins.property
    def passed(self) -> bool:
        """True if every tested function passed or is an expected failure."""
        ...

    @builtins.property
    def total(self) -> int: ...
    @builtins.property
    def failed(self) -> int: ...
    @builtins.property
    def verdict_counts(self) -> dict[str, int]:
        """Count scan results by their primary verdict."""
        ...

    def summary(self) -> str: ...

@dataclass
class FuzzResult:
    """Result of fuzzing a single function."""

    function: str
    examples: int
    failures: list[Exception] = ...
    failing_args: dict[str, Any] | None = ...

    @builtins.property
    def passed(self) -> bool: ...
    def summary(self) -> str: ...

COMMON_NAME_STRATEGIES: dict[str, st.SearchStrategy[Any]] = ...
_SUFFIX_STRATEGIES: dict[str, st.SearchStrategy[Any]] = ...
_REGISTERED_STRATEGIES: dict[str, st.SearchStrategy[Any]] = ...
_REGISTERED_OBJECT_FACTORIES: dict[str, Any] = ...
_REGISTERED_OBJECT_SETUPS: dict[str, Any] = ...
_REGISTERED_OBJECT_SCENARIOS: dict[str, Any] = ...
_REGISTERED_OBJECT_STATE_FACTORIES: dict[str, Any] = ...
_REGISTERED_OBJECT_TEARDOWNS: dict[str, Any] = ...
_REGISTERED_OBJECT_HARNESSES: dict[str, str] = ...
_BOUNDARY_SMOKE_VALUES: dict[object, tuple[object, ...]] = ...
_VALID_SCAN_MODES: set[str] = ...
_WEAK_CONTRACT_FIT = ...
_SECURITY_FOCUS_MIN_FIXTURE_COMPLETENESS = ...
_SEMANTIC_CONTRACT_MIN_FIXTURE_COMPLETENESS = ...
_SEMANTIC_CONTRACT_STRONG_REALISM = ...

@dataclass(frozen=True)
class SeedExample:
    """One concrete input shape derived from existing code or tests."""

    kwargs: dict[str, Any]
    source: str
    evidence: str
    ...

@dataclass(frozen=True)
class CandidateInput:
    """One deterministic input candidate with provenance metadata."""

    kwargs: dict[str, Any]
    origin: str
    rationale: tuple[str, ...] = ...

@dataclass(frozen=True)
class HarnessHint:
    """One mined suggestion for configuring a stateful object target."""

    kind: str
    suggestion: str
    evidence: str
    confidence: float = ...
    score: float = ...
    signals: tuple[str, ...] = ...
    config: dict[str, Any] = ...

@dataclass(frozen=True)
class AutoObjectRuntime:
    """One conservative runtime assembled from mined harness hints."""

    factory: Any | None = ...
    factory_source: str | None = ...
    setup: Any | None = ...
    setup_source: str | None = ...
    state_factory: Any | None = ...
    state_factory_source: str | None = ...
    teardown: Any | None = ...
    teardown_source: str | None = ...
    scenarios: tuple[Any, ...] = ...
    scenario_source: str | None = ...
    harness: str | None = ...
    harness_source: str | None = ...
    hints: tuple[HarnessHint, ...] = ...

_DEFAULT_AUTO_CONTRACTS = ...
_HARNESS_HINT_SIGNAL_WEIGHTS: dict[str, float] = ...
_MISSING = ...

@dataclass(frozen=True)
class _IndexedEvidenceScope:
    """One scope with literal bindings and call sites indexed by leaf name."""

    node: ast.AST
    parametrized: tuple[dict[str, Any], ...]
    calls: dict[str, tuple[ast.Call, ...]]
    ...

@dataclass(frozen=True)
class _IndexedEvidenceFile:
    """Reusable structural evidence for one version of a Python file."""

    cache_key: tuple[str, int, int]
    scopes: tuple[_IndexedEvidenceScope, ...]
    functions: tuple[ast.FunctionDef | ast.AsyncFunctionDef, ...]
    imports: tuple[tuple[str, str | None], ...]
    from_imports: tuple[tuple[str, str, str | None], ...]
    documentation_tokens: frozenset[str]
    ...

class ProjectEvidenceIndex:
    """Parse and index project evidence once for all callables in one scan."""

    def __init__(
        self,
        module_name: str,
        *,
        test_files: Sequence[Path] | None = ...,
        project_files: Sequence[Path] | None = ...,
    ) -> None:
        """Build the test, fixture, and project call-site index."""
        ...

    def invalidate(self, path: Path | None = ...) -> None:
        """Explicitly rebuild one changed file, or the complete index."""
        ...

    def cached_seed_examples(self, key: tuple[Any, ...]) -> tuple[SeedExample, ...] | None:
        """Return combined seed examples cached for one callable and option set."""
        ...

    def store_seed_examples(self, key: tuple[Any, ...], examples: Sequence[SeedExample]) -> None:
        """Cache combined seed examples for reuse throughout this scan."""
        ...

    def cached_contract_profile(self, key: tuple[Any, ...]) -> dict[str, Any] | None:
        """Return a contract profile cached for one callable and option set."""
        ...

    def store_contract_profile(self, key: tuple[Any, ...], profile: dict[str, Any]) -> None:
        """Cache one contract profile for reuse throughout this scan."""
        ...

    def fixture_literals(
        self, param_names: set[str], files: Sequence[Path]
    ) -> dict[str, list[Any]]:
        """Return pre-indexed literal fixture values for matching parameters."""
        ...

    def call_seed_examples(
        self, func: Any, files: Sequence[Path], *, source: str
    ) -> list[SeedExample]:
        """Return literal call examples by querying the pre-indexed call sites."""
        ...

def register_fixture(name: str, strategy: st.SearchStrategy[Any]) -> None:
    """Register a named fixture strategy for auto-scan.

    Registered strategies have highest priority after explicit fixtures.
    Call this in ``conftest.py`` to teach ordeal about project-specific
    types::

        from ordeal.auto import register_fixture
        import hypothesis.strategies as st

        register_fixture("model", st.builds(make_mock_model))
        register_fixture("direction", st.builds(make_unit_vector))

    After registration, ``scan_module`` and ``fuzz`` will auto-resolve
    parameters named ``model`` or ``direction`` without explicit fixtures.
    """
    ...

def register_object_factory(name: str, factory: Any) -> None:
    """Register an object factory for class-method targets.

    Use this for methods that need a prebuilt instance or collaborators.
    The factory can be sync or async and may return the instance directly.
    """
    ...

def register_object_setup(name: str, setup: Any) -> None:
    """Register a per-instance setup hook for class-method targets."""
    ...

def register_object_scenario(name: str, scenario: Any) -> None:
    """Register one or more collaborator scenario hooks for class-method targets."""
    ...

def register_object_state_factory(name: str, state_factory: Any) -> None:
    """Register a per-method state factory for class-method targets."""
    ...

def register_object_teardown(name: str, teardown: Any) -> None:
    """Register a per-instance teardown hook for class-method targets."""
    ...

def register_object_harness(name: str, harness: str) -> None:
    """Register how ordeal should exercise a class target.

    Valid values are ``"fresh"`` and ``"stateful"``.
    """
    ...

_BUILTIN_OBJECT_SCENARIO_LIBRARY_SPECS: dict[str, dict[str, Any]] = ...
_BUILTIN_OBJECT_SCENARIO_LIBRARY_ALIASES = ...

def available_object_scenario_libraries() -> tuple[dict[str, Any], ...]:
    """Return the canonical built-in collaborator scenario library catalog."""
    ...

_DISCOVERY_IGNORED_PATH_PARTS = ...
_DISCOVERY_IGNORED_ROOT_NAMES = ...

def shell_safe_contract(
    *, kwargs: dict[str, Any], tracked_params: Sequence[str] | None = ...
) -> ContractCheck:
    """Build a shell-safety probe for command construction helpers."""
    ...

def shell_injection_contract(
    *, kwargs: dict[str, Any], tracked_params: Sequence[str] | None = ...
) -> ContractCheck:
    """Build a static shell-injection oracle for command-executing helpers."""
    ...

def quoted_paths_contract(
    *, kwargs: dict[str, Any], tracked_params: Sequence[str] | None = ...
) -> ContractCheck:
    """Build a path-quoting probe for command builders."""
    ...

def command_arg_stability_contract(
    *, kwargs: dict[str, Any], tracked_params: Sequence[str] | None = ...
) -> ContractCheck:
    """Build a probe that ensures tracked args survive command construction."""
    ...

def protected_env_keys_contract(
    *, kwargs: dict[str, Any], protected_keys: Sequence[str], env_param: str | None = ...
) -> ContractCheck:
    """Build a probe that checks protected env keys survive updates."""
    ...

def json_roundtrip_contract(*, kwargs: dict[str, Any]) -> ContractCheck:
    """Build a probe that checks returned values survive JSON normalization."""
    ...

def http_shape_contract(*, kwargs: dict[str, Any]) -> ContractCheck:
    """Build a probe that checks HTTP-like payloads keep string-shaped headers and body."""
    ...

def subprocess_argv_contract(
    *, kwargs: dict[str, Any], tracked_params: Sequence[str] | None = ...
) -> ContractCheck:
    """Build a probe that checks subprocess argv tokens stay intact."""
    ...

def lifecycle_attempts_all_contract(
    *,
    kwargs: dict[str, Any],
    phase: str,
    fault: str = ...,
    handler_name: str | None = ...,
    contract_name: str = ...,
) -> ContractCheck:
    """Build a lifecycle probe that requires best-effort handler attempts."""
    ...

def lifecycle_followup_contract(
    *,
    kwargs: dict[str, Any],
    phase: str,
    followup_phases: Sequence[str],
    fault: str = ...,
    handler_name: str | None = ...,
    contract_name: str = ...,
) -> ContractCheck:
    """Build a lifecycle probe that requires follow-up phases after a fault."""
    ...

def builtin_contract_check(
    name: str,
    *,
    kwargs: dict[str, Any],
    tracked_params: Sequence[str] | None = ...,
    protected_keys: Sequence[str] | None = ...,
    env_param: str | None = ...,
    phase: str | None = ...,
    followup_phases: Sequence[str] | None = ...,
    fault: str = ...,
    handler_name: str | None = ...,
) -> ContractCheck:
    """Build one built-in semantic contract probe by *name*."""
    ...

_FIXTURE_REGISTRY_MODULES: set[str] = ...

def load_fixture_registry_modules(modules: list[str]) -> list[str]:
    """Import explicit registry modules so ``register_fixture()`` takes effect."""
    ...

def load_project_fixture_registries(
    *, root: Path | None = ..., extra_modules: list[str] | None = ...
) -> list[str]:
    """Import local registries so ``register_fixture()`` takes effect."""
    ...

_SCENARIO_PACK_ATTR_ALIASES: dict[str, str] = ...
_DOC_STOPWORDS = ...

def scan_module(
    module: str | ModuleType,
    *,
    max_examples: int | dict[str, int] = ...,
    check_return_type: bool = ...,
    targets: Sequence[str] | None = ...,
    include_private: bool = ...,
    fixtures: dict[str, st.SearchStrategy] | None = ...,
    object_factories: dict[str, Any] | None = ...,
    object_setups: dict[str, Any] | None = ...,
    object_scenarios: dict[str, Any] | None = ...,
    object_state_factories: dict[str, Any] | None = ...,
    object_teardowns: dict[str, Any] | None = ...,
    object_harnesses: dict[str, str] | None = ...,
    expected_failures: list[str] | None = ...,
    expected_preconditions: dict[str, list[str]] | None = ...,
    ignore_properties: list[str] | None = ...,
    ignore_relations: list[str] | None = ...,
    property_overrides: dict[str, list[str]] | None = ...,
    relation_overrides: dict[str, list[str]] | None = ...,
    expected_properties: dict[str, list[str]] | None = ...,
    expected_relations: dict[str, list[str]] | None = ...,
    contract_checks: dict[str, list[ContractCheck]] | None = ...,
    ignore_contracts: list[str] | None = ...,
    contract_overrides: dict[str, list[str]] | None = ...,
    mode: ScanMode = ...,
    seed_from_tests: bool = ...,
    seed_from_fixtures: bool = ...,
    seed_from_docstrings: bool = ...,
    seed_from_code: bool = ...,
    seed_from_call_sites: bool = ...,
    treat_any_as_weak: bool = ...,
    proof_bundles: bool = ...,
    auto_contracts: Sequence[str] | None = ...,
    shell_injection_check: bool = ...,
    require_replayable: bool = ...,
    min_contract_fit: float = ...,
    min_reachability: float = ...,
    min_realism: float = ...,
    security_focus: bool = ...,
    minimize_findings: bool = ...,
) -> ScanResult:
    """Smoke-test every public callable in *module*.

    For each callable with type hints, generates random inputs and checks:

    - **No crash**: calling with valid inputs doesn't raise
    - **Return type**: if annotated, the return value matches (optional)

    Simple::

        result = scan_module("myapp.scoring")
        assert result.passed

    With fixtures for params that can't be inferred::

        result = scan_module("myapp", fixtures={"model": model_strategy})

    With per-function example budgets::

        result = scan_module("myapp", max_examples={
            "compute": 200,    # fuzz this one harder
            "__default__": 50, # everything else
        })

    With expected failures for known-broken functions::

        result = scan_module("myapp", expected_failures=["broken_func"])
        assert result.passed  # broken_func failure won't count

    Args:
        module: Module path or object to scan.
        max_examples: Hypothesis examples per function. Either a single int
            (same budget for all functions) or a dict mapping function names
            to budgets, with ``"__default__"`` as fallback (default: 50).
        check_return_type: Verify return type annotations.
        targets: Optional explicit callable targets within the module. Accepts
            local names like ``"Env.build_env_vars"`` or explicit targets like
            ``"pkg.mod:Env.build_env_vars"``.
        include_private: Also include single-underscore names.
        fixtures: Strategy overrides for specific parameter names.
        object_factories: Factory overrides for class targets.
        object_setups: Optional per-class setup hooks run after factory creation.
        object_scenarios: Optional per-class collaborator scenarios run after setup.
        object_state_factories: Optional per-class state factories for methods that take
            a runtime ``state`` parameter.
        object_teardowns: Optional per-class teardown hooks for stateful harnesses.
        object_harnesses: Per-class harness mode (``fresh`` or ``stateful``).
        expected_failures: Function names that are expected to fail.
            Failures from these functions are tracked separately and
            do not cause ``result.passed`` to be ``False``.
        expected_preconditions: Per-function exception/docstring tokens that
            should count as expected contract preconditions instead of bugs.
        ignore_properties: Property names to suppress in mined warnings.
        ignore_relations: Relation names to suppress in mined warnings.
        property_overrides: Per-function property suppressions.
        relation_overrides: Per-function relation suppressions.
        expected_properties: Per-function expected property annotations. These
            are merged into ``property_overrides`` as suppressions.
        expected_relations: Per-function expected relation annotations. These
            are merged into ``relation_overrides`` as suppressions.
        contract_checks: Explicit semantic contract probes keyed by
            callable name. Each probe runs with explicit ``kwargs`` and
            reports a contract violation when its predicate fails.
        ignore_contracts: Auto-inferred contract probes to suppress globally.
        contract_overrides: Per-function auto-contract suppressions.
        mode: ``"evidence"`` surfaces broad exploratory findings;
            ``"candidate"`` keeps only stricter high-fit candidates.
            ``"coverage_gap"`` and ``"real_bug"`` remain compatibility aliases.
        seed_from_tests: Learn valid input shapes from adjacent pytest files.
        seed_from_fixtures: Mine literal pytest fixture returns as seed inputs.
        seed_from_docstrings: Mine doctest-like examples from docstrings.
        seed_from_code: Mine boundary values from code patterns.
        seed_from_call_sites: Mine literal examples from adjacent call sites.
        treat_any_as_weak: Penalize broad or missing hints instead of trusting them.
        proof_bundles: Attach structured proof payloads to crash findings.
        auto_contracts: Auto-enable sink-aware semantic checks for shell/path/env/json/http.
        shell_injection_check: Run a static shell-injection oracle before execution.
        require_replayable: Require replayability before promoting a bug candidate.
        min_contract_fit: Minimum inferred contract-fit score to promote.
        min_reachability: Minimum reachability score to promote.
        min_realism: Minimum semantic realism score to promote.
        security_focus: Opt into trust-boundary-biased sink detection, scoring,
            and deterministic low-side-effect security probes.
        minimize_findings: Shrink and replay suspicious property witnesses.
    """
    ...

def fuzz(
    fn: Any,
    *,
    max_examples: int = ...,
    check_return_type: bool = ...,
    object_factories: dict[str, Any] | None = ...,
    object_setups: dict[str, Any] | None = ...,
    object_scenarios: dict[str, Any] | None = ...,
    object_state_factories: dict[str, Any] | None = ...,
    **fixtures: st.SearchStrategy[Any] | Any,
) -> FuzzResult:
    """Deep-fuzz a single function with auto-inferred strategies.

    Simple::

        result = fuzz(myapp.scoring.compute)
        assert result.passed

    With fixture overrides (strategies or plain values)::

        result = fuzz(myapp.scoring.compute, model=model_strategy)
        result = fuzz(myapp.scoring.compute, max_tokens=5)  # auto-wrapped

    Args:
        fn: The function to fuzz.
        max_examples: Number of random inputs to try.
        check_return_type: Verify return type annotation.
        object_factories: Factory overrides for class targets.
        object_setups: Optional per-class setup hooks run after factory creation.
        object_scenarios: Optional per-class collaborator scenarios run after setup.
        object_state_factories: Optional per-class state factories for methods that take
            a runtime ``state`` parameter.
        **fixtures: Strategy overrides or plain values (auto-wrapped in st.just).
    """
    ...

_FAULT_PATTERNS: dict[str, list[tuple[str, str, dict[str, Any]]]] = ...

def chaos_for(
    module: str | ModuleType,
    *,
    fixtures: dict[str, st.SearchStrategy] | None = ...,
    object_factories: dict[str, Any] | None = ...,
    object_setups: dict[str, Any] | None = ...,
    object_scenarios: dict[str, Any] | None = ...,
    object_state_factories: dict[str, Any] | None = ...,
    object_teardowns: dict[str, Any] | None = ...,
    object_harnesses: dict[str, str] | None = ...,
    invariants: list[Invariant] | dict[str, Invariant] | None = ...,
    faults: list[Fault] | None = ...,
    max_examples: int = ...,
    stateful_step_count: int = ...,
    rule_timeout: float = ...,
) -> type:
    """Auto-generate a ChaosTest from a module's public API.

    Each public function becomes a ``@rule``.  The nemesis toggles
    *faults*.  After each step, *invariants* are checked on every
    return value.

    Zero-config — discovers everything automatically::

        TestScoring = chaos_for("myapp.scoring")
        # Scans code for subprocess/file/network calls → generates faults
        # Mines each function with random inputs → generates invariants

    With explicit overrides::

        TestScoring = chaos_for(
            "myapp.scoring",
            faults=[timing.timeout("myapp.db.query")],
            invariants={"compute": bounded(0, 1)},
        )

    Pass ``faults=[]`` or ``invariants=[]`` to disable auto-discovery.

    Returns a pytest-discoverable ``TestCase`` class.

    Args:
        module: Module path or object.
        fixtures: Strategy overrides for parameter names.
        object_factories: Factory overrides for class targets.
        object_setups: Optional per-class setup hooks run after factory creation.
        object_state_factories: Optional per-class state factories for methods that take
            a runtime ``state`` parameter.
        object_teardowns: Optional per-class teardown hooks run during ChaosTest teardown.
        object_harnesses: Per-class harness mode (``fresh`` or ``stateful``).
        invariants: ``None`` = auto-mine, list = global, dict = per-function.
        faults: ``None`` = auto-infer from code, list = explicit.
        max_examples: Hypothesis examples.
        stateful_step_count: Max rules per test case.
        rule_timeout: Per-rule timeout in seconds (default 30, 0 to disable).
    """
    ...
