# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from contextlib import contextmanager
from typing import Any, ClassVar, TYPE_CHECKING
from hypothesis.stateful import RuleBasedStateMachine
from ordeal.faults import Fault

"\nThis type stub file was generated by pyright.\n"
if TYPE_CHECKING: ...

class RuleTimeoutError(Exception):
    """A ChaosTest rule exceeded its ``rule_timeout``.

    This usually means a fault (buggify / PatchFault) caused the code
    under test to block indefinitely — a real resilience finding.
    """

    ...

_rule_timeout_context_depth = ...
_active_rule_timeout: tuple[str, float] | None = ...

@contextmanager
def rule_timeout_context() -> Any:
    """Install SIGALRM once while Explorer executes a batch of rules.

    Individual wrapped rules still arm and disarm their timers. Standalone
    Hypothesis runs retain their per-rule handler setup for compatibility.
    """
    ...

_FAULT_ENERGY_REWARD: float = ...
_FAULT_ENERGY_DECAY: float = ...
_FAULT_ENERGY_MIN: float = ...

class ChaosTest(RuleBasedStateMachine):
    """Base class for stateful chaos tests.

    Quick start::

        class MyServiceChaos(ChaosTest):
            faults = [timing.timeout("myapp.db.query")]

            @rule()
            def call_service(self):
                result = my_service.process("input")
                always(result is not None, "never None")

        TestMyService = MyServiceChaos.TestCase  # run with: pytest

    Class attributes:
        faults: Fault instances to inject.  A nemesis rule auto-toggles
            them during exploration — you just declare, ordeal explores.
        swarm:  ``True`` = each test case picks a random *subset* of
            faults via a bitmask (Hypothesis explores which subsets
            matter). Different runs explore different combinations,
            giving better aggregate coverage than always-all-faults.
            Use when you have 3+ faults.

    Adaptive scheduling:
        When a ``CoverageCollector`` is attached (via ``_coverage_collector``),
        the nemesis uses **adaptive fault scheduling** — the equivalent of
        AFL++'s MOpt technique applied to fault selection.  Each fault
        carries an *energy* score.  After toggling a fault, the nemesis
        snapshots coverage; on the next invocation it checks whether new
        edges appeared:

        - **New edges found**: the last-toggled fault's energy is multiplied
          by ``_FAULT_ENERGY_REWARD`` (1.5x).  This fault gets selected
          more often in future steps.
        - **No new edges**: the fault's energy decays by
          ``_FAULT_ENERGY_DECAY`` (0.9x), reducing its selection weight.
        - **Minimum floor**: energy never drops below ``_FAULT_ENERGY_MIN``
          (0.1) so every fault retains a chance of being selected.

        When no collector is attached (normal ``pytest`` path), selection
        falls back to uniform random — no overhead.

    Key methods to override:
        state_hash(): Return a hash of qualitatively different states to
            enable state-aware exploration.  The explorer checkpoints new
            state hashes and branches from them.  Default returns 0
            (disabled).  Example::

                def state_hash(self):
                    return hash((self.service.state, self.balance > 0))

    Deeper testing:
        - ``pytest --chaos`` enables buggify() + property tracking
        - ``ordeal explore`` runs coverage-guided exploration with
          checkpointing and energy scheduling (reads ordeal.toml)
        - ``swarm = True`` tests random fault subsets per run

    Subprocess / FFI testing:
        Subprocess faults (``subprocess_timeout``, ``subprocess_delay``,
        ``corrupt_stdout``) work in ChaosTest — they patch
        ``subprocess.run`` and the nemesis toggles them like any fault.
        The code under test should call ``subprocess.run`` per rule
        invocation (not start a long-lived ``Popen`` in ``__init__``).
        Wrap the full subprocess lifecycle in a function and call that
        from rules::

            class KernelChaos(ChaosTest):
                faults = [subprocess_timeout("cargo run")]

                @rule()
                def run_episode(self):
                    result = run_kernel(steps=10)  # calls subprocess.run
                    always(result.exit_code == 0, "clean exit")
    """

    faults: ClassVar[list[Fault]] = ...
    swarm: ClassVar[bool] = ...
    rule_timeout: ClassVar[float] = ...
    _INTERNAL_RULES: ClassVar[frozenset[str]] = ...

    def __init_subclass__(cls, **kwargs: Any) -> None: ...
    def __init__(self) -> None: ...
    @builtins.property
    def active_faults(self) -> list[Fault]:
        """Currently active faults (useful for debugging / logging)."""
        ...

    def state_hash(self) -> int:
        """Override to enable state-aware coverage.

        Return a hash of the *qualitatively* different states — not every
        possible value, but categories that matter for bug-finding.
        The explorer treats a new state hash as a discovery (saves a
        checkpoint, resets saturation counter).

        Example::

            def state_hash(self):
                return hash((
                    self.service.state,        # enum-like: "idle", "active"
                    self.balance > 0,           # sign matters, not exact value
                    len(self.pending) > 10,     # "many" vs "few"
                ))

        Return 0 (default) to disable state-aware coverage.
        """
        ...

    def checkpoint_snapshot_filter(self, name: str, value: Any) -> bool:
        """Return whether *name* should be included in Explorer checkpoints.

        Override this to skip ephemeral resources such as temp dirs,
        open file handles, subprocess clients, or sockets that should be
        rebuilt when a checkpoint is restored.

        The default keeps user state and skips ChaosTest internals that
        are always reinitialized on a fresh machine instance.
        """
        ...

    def clone_checkpoint_state(self) -> dict[str, Any]:
        """Return an isolated Explorer checkpoint snapshot of this machine.

        Override this together with :meth:`restore_checkpoint_state` for a
        faster state-specific checkpoint protocol. The returned value must
        not share mutable state with the live machine, and the restore hook
        must not retain mutable references into the supplied snapshot.
        """
        ...

    def restore_checkpoint_state(self, snapshot: dict[str, Any]) -> None:
        """Restore Explorer checkpoint state onto this machine instance.

        Override this when the raw snapshot needs post-processing, such as
        recreating temporary directories or reconnecting clients before
        the saved state is written back.
        """
        ...

    def __repr__(self) -> str: ...
    def teardown(self) -> None:
        """Deactivate all faults (including those not in the swarm subset)."""
        ...

def chaos_test(cls: type | None = ..., *, faults: list | None = ...):
    """Decorator that turns a ChaosTest subclass into a pytest-runnable test.

    Removes the need for the ``TestCase = MyChaos.TestCase`` boilerplate::

        @chaos_test
        class MyServiceChaos(ChaosTest):
            faults = [timing.timeout("myapp.api")]

            @rule()
            def call_service(self):
                ...

    Also works as a factory for inline declaration::

        @chaos_test(faults=[timing.timeout("myapp.api")])
        class MyServiceChaos(ChaosTest):
            @rule()
            def call_service(self):
                ...

    The returned object is the ``TestCase`` class, directly discoverable
    by pytest without any extra wiring.

    Args:
        cls: The ChaosTest subclass (passed automatically when used as
            ``@chaos_test`` without parentheses).
        faults: Optional list of fault instances to inject.  Overrides
            the class-level ``faults`` attribute.
    """
    ...
