# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping
from ordeal.config import ComposeConfig

"\nThis type stub file was generated by pyright.\n"
REPLAY_BOUNDARY = ...
_DURABLE_FAILURE_KINDS = ...
_ENV_REFERENCE = ...
_SAFE_CREDENTIAL_TEMPLATE = ...
_SENSITIVE_KEY_PARTS = ...
_REDACTED = ...

class ComposeCommandError(RuntimeError):
    """Raised when a Docker Compose lifecycle command cannot complete."""

    ...

class ServiceRequestError(RuntimeError):
    """Raised when an HTTP request cannot produce a response."""

    ...

@dataclass
class HttpResponse:
    """HTTP response observed by the service harness."""

    status: int
    headers: dict[str, str]
    body: bytes
    elapsed: float
    ...

@dataclass
class ComposeTraceAction:
    """One exact lifecycle, request, or fault action in a service trace."""

    index: int
    kind: str
    name: str
    params: dict[str, object] = ...
    result: dict[str, object] = ...
    timestamp_offset: float = ...

@dataclass
class ComposeFailure:
    """Stable failure observation used for exact replay matching."""

    kind: str
    message: str
    action_index: int
    action_name: str

    @builtins.property
    def signature(self) -> str:
        """Return a hash of the exact failure kind, location, action, and message."""
        ...

@dataclass
class ComposeReplayReport:
    """Probabilistic reproduction result for one exact Compose trace."""

    attempted: int
    reproduced: int
    expected_signature: str | None
    observed_signatures: list[str | None] = ...
    boundary: str = ...

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe replay report."""
        ...

@dataclass
class ComposeTrace:
    """Self-contained action/fault trace for the Compose runner."""

    seed: int
    compose: dict[str, object]
    actions: list[ComposeTraceAction] = ...
    failure: ComposeFailure | None = ...
    final_state: dict[str, object] = ...
    duration: float = ...
    replay: ComposeReplayReport | None = ...
    runner: str = ...
    schema_version: int = ...

    @builtins.property
    def failure_signature(self) -> str | None:
        """Return the exact recorded failure signature, when the run failed."""
        ...

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe trace payload."""
        ...

    def content_hash(self) -> str:
        """Return a stable short hash of the complete trace payload."""
        ...

    def save(self, path: str | Path) -> None:
        """Save the trace as JSON, with optional gzip compression."""
        ...

    @classmethod
    def load(cls, path: str | Path) -> ComposeTrace:
        """Load and validate a Compose trace from JSON or gzip-compressed JSON."""
        ...

    @classmethod
    def is_trace_file(cls, path: str | Path) -> bool:
        """Return whether a JSON trace declares the Compose runner schema."""
        ...

@dataclass
class ComposeExplorationResult:
    """Result and artifacts produced by one Compose exploration."""

    trace: ComposeTrace
    trace_path: Path
    replay: ComposeReplayReport | None
    requests: int
    faults: int
    duration: float
    coverage: dict[str, Any] = ...
    protection: dict[str, Any] = ...
    evidence: dict[str, Any] | None = ...

@dataclass
class ComposeRegressionArtifacts:
    """Committed trace and manifest paths for one Compose regression."""

    finding_id: str
    trace_path: Path
    manifest_path: Path
    binding: dict[str, Any]
    ...

def compose_reliability_coverage(trace: ComposeTrace) -> dict[str, Any]:
    """Build operation × fault × property coverage from a Compose trace.

    Configured cells are declared before observations, so a fault/property
    combination that never ran remains ``NOT EXERCISED`` instead of becoming a
    silent pass. Only clean validated requests contribute observations; the
    intentionally unvalidated request inside a fault window does not.
    """
    ...

class ComposeController:
    """Docker Compose lifecycle adapter using shell-free argv execution."""

    def __init__(
        self,
        config: ComposeConfig,
        *,
        run_command: Callable[..., subprocess.CompletedProcess[str]] = ...,
    ) -> None: ...
    def start(self) -> bool:
        """Start the topology and return whether this harness owns its cleanup."""
        ...

    def stop(self) -> None:
        """Stop services started by this harness without deleting volumes."""
        ...

    def kill(self, service: str) -> None:
        """Send SIGKILL to one configured Compose service."""
        ...

    def start_service(self, service: str) -> None:
        """Start one stopped service and its required dependencies."""
        ...

    def restart(self, service: str) -> None:
        """Restart one configured Compose service."""
        ...

class HttpTransport:
    """Standard-library HTTP transport used by the Compose runner."""

    def request(
        self,
        method: str,
        url: str,
        *,
        headers: Mapping[str, str],
        json_body: object | None,
        timeout: float,
    ) -> HttpResponse:
        """Send one HTTP request and return HTTP errors as normal responses."""
        ...

class _StrictState(dict[str, object]):
    def __missing__(self, key: str) -> object: ...

class ComposeRunner:
    """Explore one long-lived Compose topology and record every action."""

    def __init__(
        self,
        config: ComposeConfig,
        *,
        controller: ComposeController | None = ...,
        transport: HttpTransport | None = ...,
        monotonic: Callable[[], float] = ...,
        sleep: Callable[[float], None] = ...,
    ) -> None: ...
    def run(self) -> ComposeTrace:
        """Run a seeded service exploration and return its exact trace."""
        ...

    def replay(self, source: ComposeTrace) -> ComposeFailure | None:
        """Execute the recorded actions once and return the observed failure."""
        ...

def replay_compose_trace(
    trace: ComposeTrace,
    *,
    attempts: int | None = ...,
    runner_factory: Callable[[ComposeConfig], ComposeRunner] | None = ...,
) -> ComposeReplayReport:
    """Replay an exact service trace repeatedly and count exact failure matches."""
    ...

def measure_compose_workload_strength(
    trace: ComposeTrace,
    *,
    budget: int,
    runner_factory: Callable[[ComposeConfig], ComposeRunner] | None = ...,
) -> dict[str, Any]:
    """Measure whether observed Compose properties detect oracle mutations.

    Each trial first replays the unmodified trace prefix. Only a clean control
    allows the corresponding status, JSON, or capture expectation to be
    mutated. A mutant is killed only when the altered expectation fails at the
    selected operation. This measures the recorded workload and harness wiring;
    it does not claim that production service source code was mutated.
    """
    ...

def build_compose_finding_evidence(
    trace: ComposeTrace,
    *,
    replay: ComposeReplayReport | None,
    coverage: Mapping[str, Any],
    protection: Mapping[str, Any],
    trace_path: Path | None = ...,
) -> dict[str, Any]:
    """Build the shared bounded evidence-card schema for a Compose failure."""
    ...

def run_compose_exploration(
    config: ComposeConfig,
    *,
    seed: int | None = ...,
    max_time: float | None = ...,
    replay_attempts: int | None = ...,
) -> ComposeExplorationResult:
    """Run the Compose harness, save its exact trace, and replay failures."""
    ...

def save_compose_regression(
    result: ComposeExplorationResult,
    *,
    workspace: str | Path = ...,
    regression_dir: str | Path = ...,
    manifest_path: str | Path = ...,
) -> ComposeRegressionArtifacts | None:
    """Save a replay-backed Compose failure as a portable durable regression.

    Findings that never reproduced are deliberately not promoted. The manifest
    keeps the existing v1 envelope and distinguishes Compose records with
    ``runner=compose`` plus a canonical trace binding.
    """
    ...
