# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import hypothesis.strategies as st
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal
from ordeal.system_diff import (
    FaultEvent,
    Operation,
    PerformanceBudget,
    SystemDiffResult,
    SystemEvent,
)

"\nThis type stub file was generated by pyright.\n"
DiffStatus = Literal["divergent", "no_divergence_observed", "proven_equivalent", "inconclusive"]
__all__ = [
    "DiffOutcome",
    "DiffResult",
    "DiffWitness",
    "DivergenceWitness",
    "FaultEvent",
    "Mismatch",
    "Operation",
    "OutcomeObservation",
    "PerformanceBudget",
    "SideEffect",
    "SystemDiffResult",
    "diff",
]

@dataclass(frozen=True)
class SideEffect:
    """One explicitly selected external state channel to isolate and compare.

    ``capture`` returns the current state. ``restore`` must replace that state
    with a previously captured value. Ordeal restores the baseline before and
    after each revision invocation.
    """

    capture: Callable[[], Any]
    restore: Callable[[Any], None]
    ...

@dataclass(frozen=True)
class DiffOutcome:
    """Immutable public observation of one revision's full outcome envelope."""

    returned: bool
    return_value: Any
    exception_type: type[Exception] | None
    exception_message: str | None
    mutated_arguments: Mapping[str, Any]
    receiver_state: Mapping[str, Any] | None
    side_effects: Mapping[str, Any]
    terminal_source_location: Mapping[str, Any] | None = ...
    normalized_value: Any = ...

@dataclass(frozen=True)
class DiffWitness:
    """One minimized, immutable, replay-measured divergence witness."""

    args: Mapping[str, Any]
    outcome_a: DiffOutcome
    outcome_b: DiffOutcome
    differences: tuple[str, ...]
    replay_attempts: int = ...
    replay_matches: int = ...
    replay_verified: bool = ...
    artifact: Mapping[str, Any] = ...
    artifact_path: str | None = ...
    replay_args_json: str | None = ...

    def __str__(self) -> str:
        """Format a compact full-envelope divergence preview."""
        ...

OutcomeObservation = DiffOutcome
DivergenceWitness = DiffWitness

@dataclass
class Mismatch:
    """A compatibility view of one input where the two revisions disagree.

    ``artifact`` is the complete machine-readable evidence record. ``args`` and
    ``output_a``/``output_b`` preserve the original small debugging surface.
    """

    args: dict[str, Any]
    output_a: Any
    output_b: Any
    artifact: dict[str, Any] | None = ...
    artifact_path: str | None = ...

    def __str__(self) -> str:
        """Format the compact input and paired return/exception observations."""
        ...

@dataclass
class DiffResult:
    """Bounded result of searching two revisions for behavioral divergence."""

    function_a: str
    function_b: str
    total: int
    mismatches: list[Mismatch] = ...
    status: DiffStatus | None = ...
    witness: DiffWitness | None = ...
    reason: str | None = ...
    proof_method: str | None = ...
    regression_path: str | None = ...
    manifest_path: str | None = ...
    finding_id: str | None = ...
    regression_error: str | None = ...

    def __post_init__(self) -> None:
        """Derive the status for callers constructing legacy result objects."""
        ...

    @builtins.property
    def divergent(self) -> bool:
        """True when a sampled input established a full-envelope mismatch."""
        ...

    @builtins.property
    def no_divergence_found(self) -> bool:
        """True when no mismatch was observed; not itself an equivalence proof."""
        ...

    @builtins.property
    def equivalent(self) -> bool | None:
        """False if disproved, true only with an explicit proof, else unknown."""
        ...

    @builtins.property
    def artifacts(self) -> list[dict[str, Any]]:
        """Return every JSON-ready divergence artifact produced by this run."""
        ...

    @builtins.property
    def artifact_paths(self) -> list[str]:
        """Return paths written through ``artifact_dir``."""
        ...

    def summary(self) -> str:
        """Return a bounded report and compact witness preview."""
        ...

class _DivergenceFound(Exception):
    """Private signal that lets Hypothesis shrink one mismatch candidate."""

    def __init__(self, candidate: _Candidate) -> None: ...

class _ReconstructionInconclusive(Exception):
    """Internal signal for inputs or receivers that cannot be isolated."""

    ...

@dataclass
class _CallOutcome:
    """Mutable internal observation retained until artifact construction."""

    value: Any = ...
    exception: Exception | None = ...
    terminal_source_location: dict[str, Any] | None = ...
    mutated_arguments: dict[str, Any] = ...
    receiver_state: dict[str, Any] | None = ...
    side_effects: dict[str, Any] = ...

    @builtins.property
    def recorded_value(self) -> Any:
        """Return the legacy mismatch value for this outcome."""
        ...

@dataclass
class _Candidate:
    """One Hypothesis divergence candidate and its comparison-normalized values."""

    args: dict[str, Any]
    outcome_a: _CallOutcome
    outcome_b: _CallOutcome
    normalized_a: Any
    normalized_b: Any
    differences: tuple[str, ...]
    ...

_DIFF_REGRESSION_TEST = ...

def replay_diff_regression_case(case: Mapping[str, object]) -> None:
    """Replay one saved function or system divergence until it stays fixed."""
    ...

def diff(
    fn_a: Callable[..., Any],
    fn_b: Callable[..., Any],
    *,
    max_examples: int = ...,
    rtol: float | None = ...,
    atol: float | None = ...,
    compare: Callable[[Any, Any], bool] | None = ...,
    normalize: Callable[[Any], Any] | None = ...,
    replay_attempts: int = ...,
    artifact_dir: str | Path | None = ...,
    regression_path: str | Path | None = ...,
    manifest_path: str | Path | None = ...,
    side_effects: Mapping[str, SideEffect] | Callable[[Any], Any] | None = ...,
    equivalence_proof: Callable[[Callable[..., Any], Callable[..., Any]], bool] | None = ...,
    sequence: Sequence[SystemEvent] | None = ...,
    state: Callable[[Any], Any] | None = ...,
    apply_fault: Callable[[Any, FaultEvent], None] | None = ...,
    performance: PerformanceBudget | None = ...,
    minimize: bool = ...,
    **fixtures: st.SearchStrategy[Any] | Any,
) -> DiffResult | SystemDiffResult:
    """Search two revisions for a full-envelope behavioral divergence.

    Every observed divergence is minimized, replayed on the same input, and
    represented by a source-bound ``ordeal.divergence-evidence/v1`` artifact.
    The artifact is always available in ``result.artifacts``; pass
    ``artifact_dir`` to persist it as JSON. ``normalize`` transforms returned
    values before the default or custom comparator runs. Exceptions, mutated
    arguments, bound receiver state, and selected ``side_effects`` remain part
    of the comparison independently of return-value normalization.

    ``no_divergence_found`` is bounded by the sampled inputs and selected
    observable channels. Only an explicit successful ``equivalence_proof``
    produces ``status == "proven_equivalent"``.

    Providing ``sequence`` switches to system mode. The same ordered
    operations and fault transitions run against fresh instances from both
    zero-argument factories. Public exports, signatures, outcomes, public
    state, selected side effects, and recovery are reported together;
    ``performance`` remains a separate measured contract.

    System example::

        result = diff(
            OldStore,
            NewStore,
            sequence=[
                FaultEvent("timeout", "activate"),
                Operation("read"),
                FaultEvent("timeout", "deactivate"),
                Operation("read"),
            ],
            state=lambda store: store.snapshot(),
        )

    See ``docs/concepts/system-differential.md`` for the layman model and
    ``docs/guides/system-differential.md`` for a complete copyable tutorial.
    """
    ...
