# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import ast
from collections.abc import Callable
from dataclasses import dataclass

"\nThis type stub file was generated by pyright.\n"
logger = ...
_Z3_AVAILABLE: bool | None = ...
_Z3_INSTALL_HINT = ...

@dataclass
class EquivalenceResult:
    """Result of an equivalence analysis between an original and mutant function.

    Attributes:
        equivalent: ``True`` if proven/detected equivalent, ``False`` if a
            distinguishing input was found, ``None`` if inconclusive.
        confidence: 1.0 for structural or formal proof, 0.0-1.0 for
            statistical estimation.  Represents the lower bound of the
            Wilson score confidence interval for the probability that the
            functions agree on a random input.
        method: Which analysis produced this result — one of ``"structural"``,
            ``"statistical"``, ``"formal"``, or ``"inconclusive"``.
        counterexample: When ``equivalent`` is ``False``, a dict of input
            kwargs that produced different outputs from the two functions.
            ``None`` when equivalent or inconclusive.
        time_seconds: Wall-clock time for the analysis in seconds.
    """

    equivalent: bool | None
    confidence: float
    method: str
    counterexample: dict | None = ...
    time_seconds: float = ...

class _ASTNormalizer(ast.NodeTransformer):
    """Normalize an AST for structural comparison.

    Transformations:
    - Remove docstrings (first Expr(Constant(str)) in function bodies).
    - Normalize all local variable names to positional placeholders (_v0, _v1, ...).
    - Fold simple constant expressions (e.g., ``x + 0`` -> ``x``).
    - Sort commutative binary operands by AST dump for canonical form.
    - Strip type annotations from arguments and assignments.
    """

    def __init__(self) -> None: ...
    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.FunctionDef: ...
    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> ast.AsyncFunctionDef: ...
    def visit_Name(self, node: ast.Name) -> ast.Name: ...
    def visit_BinOp(self, node: ast.BinOp) -> ast.AST: ...
    def visit_AnnAssign(self, node: ast.AnnAssign) -> ast.AST:
        """Strip annotation from annotated assignments, keep the value."""
        ...

def structural_equivalence(original_source: str, mutant_source: str) -> EquivalenceResult:
    """Check structural equivalence via AST normalization.

    Parses both source strings, normalizes the ASTs (removes docstrings,
    canonicalizes variable names, folds trivial constants, sorts commutative
    operands), and compares the resulting AST dumps.

    This is fast (microseconds) but conservative — it only catches mutants
    that are trivially equivalent after normalization.  If it says equivalent,
    it is.  If it says not equivalent, the functions may still be semantically
    identical.

    Args:
        original_source: Source code of the original function.
        mutant_source: Source code of the mutant function.

    Returns:
        EquivalenceResult with ``method="structural"``.  ``equivalent`` is
        ``True`` if the normalized ASTs match, ``None`` otherwise (not
        ``False`` — structural difference does not prove behavioral difference).
    """
    ...

_BOUNDARY_VALUES: dict[type, list] = ...

def statistical_equivalence(
    original_fn: Callable, mutant_fn: Callable, *, n_samples: int = ..., confidence: float = ...
) -> EquivalenceResult:
    """Statistical equivalence test with Wilson score confidence bounds.

    Runs both functions on boundary values and *n_samples* random inputs,
    then computes a Wilson score confidence interval for the probability
    that the functions agree.

    This extends the behavioral filtering in ``ordeal.mutations`` with
    rigorous statistics: instead of a simple "all samples matched" boolean,
    it quantifies how confident we are that the functions are equivalent.

    Args:
        original_fn: The original function.
        mutant_fn: The mutant function.
        n_samples: Number of random samples to draw beyond boundary values.
        confidence: Confidence level for the Wilson interval (default 0.99).

    Returns:
        EquivalenceResult with ``method="statistical"``.

        - ``equivalent=True`` if all samples agree and the Wilson lower bound
          exceeds ``confidence``.
        - ``equivalent=False`` if any sample disagrees (with counterexample).
        - ``equivalent=None`` if inputs cannot be generated.
    """
    ...

def prove_equivalent(
    original_fn: Callable,
    mutant_fn: Callable,
    *,
    max_seconds: int = ...,
    _original_source: str | None = ...,
    _mutant_source: str | None = ...,
) -> EquivalenceResult:
    """Attempt formal equivalence proof using Z3 SMT solver.

    Encodes both functions as SMT formulas and checks whether there exists
    any input where they produce different outputs.  If UNSAT (no such input
    exists), the functions are proven equivalent.  If SAT, a concrete
    counterexample is returned.

    Only works for functions expressible in the supported subset: integer
    and real arithmetic, comparisons, boolean logic, simple conditionals.
    Returns inconclusive for functions with loops, string operations,
    data structures, or external calls.

    Args:
        original_fn: The original function.
        mutant_fn: The mutant function.
        max_seconds: Solver timeout in seconds.

    Returns:
        EquivalenceResult with ``method="formal"``.

        - ``equivalent=True`` with ``confidence=1.0`` if proven equivalent.
        - ``equivalent=False`` with counterexample if proven different.
        - ``equivalent=None`` if Z3 is not installed, the functions cannot
          be encoded, or the solver times out.
    """
    ...

def classify_mutant(
    original_fn: Callable,
    mutant_fn: Callable,
    original_source: str | None = ...,
    mutant_source: str | None = ...,
    *,
    max_seconds: int = ...,
    n_samples: int = ...,
    confidence: float = ...,
) -> EquivalenceResult:
    """Run all equivalence methods in order: structural, statistical, formal.

    Starts with the fastest method (structural AST comparison) and
    escalates to slower methods only when the previous one is inconclusive.
    Returns the first definitive result.

    Args:
        original_fn: The original function.
        mutant_fn: The mutant function.
        original_source: Source code of the original (auto-extracted if None).
        mutant_source: Source code of the mutant (auto-extracted if None).
        max_seconds: Timeout for formal Z3 proof in seconds.
        n_samples: Number of random samples for statistical test.
        confidence: Confidence level for statistical test.

    Returns:
        The first definitive EquivalenceResult, or an inconclusive result
        with cumulative time if no method was definitive.
    """
    ...

@dataclass
class MutantPair:
    """A mutant paired with its source code for equivalence analysis.

    Attributes:
        mutant_fn: The compiled mutant callable.
        mutant_source: Source code of the mutant.
        label: Human-readable label (e.g., operator name + line number).
    """

    mutant_fn: Callable
    mutant_source: str
    label: str = ...

def filter_equivalent_mutants(
    original_fn: Callable,
    mutant_pairs: list[MutantPair],
    *,
    methods: tuple[str, ...] = ...,
    original_source: str | None = ...,
    n_samples: int = ...,
    confidence: float = ...,
    max_seconds: int = ...,
) -> list[tuple[MutantPair, EquivalenceResult]]:
    """Filter equivalent mutants using layered analysis.

    Drop-in enhancement for the equivalence filtering in ``ordeal.mutations``.
    Runs the specified methods in order for each mutant, skipping those
    classified as equivalent.

    Args:
        original_fn: The original function.
        mutant_pairs: List of MutantPair instances to classify.
        methods: Which methods to use, in order.  Default is
            ``("structural", "statistical")`` for speed.  Add ``"formal"``
            for Z3-backed proof when available.
        original_source: Source of the original function (auto-extracted if None).
        n_samples: Random samples for statistical method.
        confidence: Confidence level for statistical method.
        max_seconds: Timeout for formal method.

    Returns:
        List of ``(MutantPair, EquivalenceResult)`` tuples for mutants that
        are NOT equivalent (i.e., should be tested).  Equivalent mutants are
        filtered out.
    """
    ...
