# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from dataclasses import dataclass
from typing import Any

"\nThis type stub file was generated by pyright.\n"
_ORACLE_MARKER = ...

@dataclass(frozen=True)
class EvidenceCheck:
    """One expected-versus-observed evidence check."""

    name: str
    passed: bool
    expected: Any
    actual: Any
    category: str

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly check payload."""
        ...

@dataclass(frozen=True)
class BugEvidenceVerification:
    """Observed verification result for one executable evidence record."""

    evidence_id: str
    record_path: str
    claim: str
    scope: str
    local_verified: bool
    sources_verified: bool
    verified: bool
    online_sources_required: bool
    checks: tuple[EvidenceCheck, ...]
    backing_values: dict[str, Any]
    limitations: tuple[str, ...] = ...
    errors: tuple[str, ...] = ...

    def summary(self) -> str:
        """Return a compact, claim-scoped verification summary."""
        ...

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-friendly evidence result."""
        ...

    def to_json(self) -> str:
        """Return stable JSON for CI evidence artifacts."""
        ...

def verify_bug_evidence(
    path: str, *, online_sources: bool = ..., python_executable: str | None = ...
) -> BugEvidenceVerification:
    """Verify one source-backed bug/fix evidence record and its executable oracle.

    ``online_sources=True`` fetches every pinned authoritative URL and is
    required when the record declares ``online_sources_required = true``.
    Each buggy and fixed replay runs in a fresh Python process.
    """
    ...
