# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import hypothesis.strategies as st
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, TYPE_CHECKING
from ordeal.trace import Trace

"\nThis type stub file was generated by pyright.\n"
if TYPE_CHECKING: ...

class CoverageCollector:
    """Track edge coverage via ``sys.settrace``.

    Uses AFL-style edge hashing to capture control-flow *transitions*,
    not just line visits.

    **N-gram coverage** (configurable via the ``ngram`` parameter):

    With ``ngram=1`` (the default), hashing uses a single previous location:
    ``prev_loc XOR cur_loc``.  This is the classic AFL edge model — fast and
    effective, but blind to *path context*.  The same edge A->B looks
    identical regardless of whether we arrived via X->A->B or Y->A->B.

    With ``ngram=2+``, the collector maintains a ring buffer of the last N
    locations and hashes all of them together with the current location.
    This captures deeper path patterns: the edge A->B reached via X->A->B
    produces a different hash than Y->A->B.  This is the same idea as
    AFL++'s ``NGRAM`` instrumentation (``-fsanitize-coverage=trace-pc-guard``
    with N-gram context), adapted for Python's ``sys.settrace`` collector.

    **Why ngram=2 is the sweet spot for Python:**

    AFL++ defaults to NGRAM-4 for compiled C/C++ where basic blocks are
    tiny and paths diverge rapidly.  Python's line-level tracing is much
    coarser — each "location" is a full source line, not a machine-code
    basic block.  Empirically, ngram=2 captures the important path context
    (which branch led to this edge) without the exponential hash-space
    explosion that makes ngram=4 produce mostly unique, never-repeated
    hashes in Python.  The memory cost is minimal: one extra ``int`` per
    thread (the deque), and the hash computation adds a ``tuple()`` call
    per traced line.

    **Memory/performance tradeoff:**

    - ``ngram=1``: One ``int`` per thread (``prev_loc``).  XOR + shift per
      traced line.  Identical to classic AFL.
    - ``ngram=2``: Two-element deque per thread.  ``hash(tuple(...)) ^ loc``
      per traced line.  ~10-15% slower than ngram=1 in microbenchmarks,
      negligible in real exploration runs (I/O and strategy generation
      dominate).
    - ``ngram=3+``: Diminishing returns.  The hash space grows
      exponentially, so most N-gram hashes are seen only once, reducing
      the signal-to-noise ratio for checkpoint energy scheduling.
      Not recommended for Python unless profiling shows a specific need.

    Optimizations over naive per-line locking:

    - **Filename cache**: ``_is_target`` result is cached per filename so
      the path-segment check runs at most once per unique file.
    - **Thread-local edge buffer**: Edges accumulate in a per-thread list
      and are flushed to the shared set every 256 edges, reducing lock
      acquisitions by ~256x.
    - **Snapshot caching**: ``snapshot()`` returns a cached ``frozenset``
      when no new edges have arrived since the last call, avoiding
      repeated O(n) construction on steps that don't discover new paths.

    Thread-safe for free-threaded Python 3.13+: per-thread location state
    (``prev_loc`` or ``prev_locs``) and edge buffer are thread-local, and
    ``_edges`` is lock-protected.
    """

    _FLUSH_THRESHOLD = ...

    def __init__(self, target_paths: list[str], *, ngram: int = ...) -> None: ...
    def start(self) -> None:
        """Reset state and begin collecting edge coverage via ``sys.settrace``."""
        ...

    def stop(self) -> frozenset[int]:
        """Stop collection and restore the previous trace function."""
        ...

    def snapshot(self) -> frozenset[int]:
        """Current edges without stopping collection.

        Returns a cached frozenset when no new edges have been
        flushed since the last call, avoiding repeated construction.
        """
        ...

    @builtins.property
    def lines_hit(self) -> dict[str, set[int]]:
        """Mapping of filename -> set of line numbers visited."""
        ...

@dataclass
class _RuleInfo:
    """Metadata about a single @rule method."""

    name: str
    strategies: dict[str, st.SearchStrategy]
    has_data: bool = ...

class _DataProxy:
    """Stand-in for Hypothesis's ``data`` object.

    Records every draw for trace replay.
    """

    def __init__(self) -> None: ...
    def draw(self, strategy: st.SearchStrategy[Any], label: str | None = ...) -> Any:
        """Draw a value from a Hypothesis strategy."""
        ...

_ENERGY_REWARD = ...
_ENERGY_DECAY = ...
_ENERGY_MIN = ...
_CHECKPOINT_FEEDBACK_WINDOW = ...
_CHECKPOINT_FEEDBACK_MIN_SAMPLES = ...
_HIGH_RESTORE_SHARE = ...
_MIN_ADAPTIVE_CHECKPOINT_PROB = ...
_SEED_MUTATION_PROB = ...
_MAX_SEEDS_PER_CHECKPOINT = ...
_AUTO_WORKER_CAP = ...
_SWARM_ENERGY_REWARD = ...
_SWARM_ENERGY_DECAY = ...
_SWARM_ENERGY_MIN = ...
_SWARM_WARMUP_RUNS = ...

@dataclass
class SwarmConfig:
    """A joint rule+fault configuration for one exploration run.

    Each configuration determines which rules are callable AND which
    faults the nemesis can toggle.  This is the paper's model (Groce
    et al., ISSTA 2012): a "configuration" is the full feature set.

    The ``energy`` field enables adaptive scheduling (MOpt pattern):
    configurations that led to new coverage get higher selection
    probability in future runs.
    """

    active_rules: list[str]
    active_faults: list[str]
    energy: float = ...
    times_used: int = ...
    edges_found: int = ...
    runs_with_new_edges: int = ...
    failure_count: int = ...
    property_hits: int = ...

    @builtins.property
    def key(self) -> tuple[tuple[str, ...], tuple[str, ...]]:
        """Hashable identity for dedup and lookup."""
        ...

_EDGE_BITMAP_SIZE = ...
_STATE_BITMAP_SIZE = ...
_POOL_NUM_SLOTS = ...
_POOL_SLOT_SIZE = ...
_POOL_HEADER_SIZE = ...
_POOL_RING_SIZE = ...
_POOL_SLOT_HDR_SIZE = ...
_POOL_SLOT_DATA_MAX = ...
_POOL_AUTH_TAG_SIZE = ...

@dataclass
class _MachineSnapshot:
    """Lightweight snapshot: user state dict + fault active flags.

    Avoids deep-copying Fault objects (which carry locks, compiled
    patterns, and monkeypatched references).  Restore by creating a
    fresh machine and overlaying the saved state.
    """

    state_dict: dict[str, Any]
    fault_active: dict[str, bool]
    ...

@dataclass
class Checkpoint:
    """A saved machine state with energy-based scheduling weight and seed corpus.

    Each checkpoint stores the machine state *and* the rule parameters that
    led to new coverage from that state.  When the explorer branches from
    this checkpoint, it can either generate fresh parameters (Hypothesis
    strategies) or **mutate** a productive seed — the AFL closed-loop
    pattern adapted for stateful testing.

    The ``seed_params`` list is bounded by ``_MAX_SEEDS_PER_CHECKPOINT``
    to prevent memory growth.  When full, new seeds replace the lowest-energy
    entry (the one that was mutated most without finding new coverage).

    Attributes:
        snapshot: The machine state at checkpoint time.
        new_edge_count: Number of new edges found when this checkpoint was created.
        step: The step index within the run where this checkpoint was taken.
        run_id: The run that produced this checkpoint.
        energy: Energy-based scheduling weight (AFL++ power schedule analog).
            Checkpoints that lead to new edges get rewarded; others decay.
        times_selected: How many times this checkpoint has been branched from.
            Used in energy selection to penalize over-exploitation.
        seed_params: Productive ``(rule_name, params_dict)`` pairs that led
            to new coverage from this checkpoint's state.  Used as mutation
            seeds when branching from this checkpoint.
    """

    snapshot: _MachineSnapshot
    new_edge_count: int
    step: int
    run_id: int
    energy: float = ...
    times_selected: int = ...
    seed_params: list[tuple[str, dict[str, Any]]] = ...
    _pool_slot: int = ...

@dataclass
class ProgressSnapshot:
    """Live stats emitted during exploration."""

    elapsed: float
    total_runs: int
    total_steps: int
    unique_edges: int
    checkpoints: int
    failures: int
    runs_per_second: float
    ...

@dataclass
class Failure:
    """A failure found during exploration, with optional trace for replay."""

    error: Exception
    step: int
    run_id: int
    active_faults: list[str]
    rule_log: list[str]
    trace: Trace | None = ...
    necessary_faults: dict[str, bool] | None = ...
    error_traceback: str | None = ...
    native_boundary: dict[str, Any] | None = ...

    def __str__(self) -> str: ...

@dataclass
class ExplorationResult:
    """Aggregated results from an exploration run."""

    total_runs: int = ...
    total_steps: int = ...
    skipped_steps: int = ...
    unique_edges: int = ...
    checkpoints_saved: int = ...
    failures: list[Failure] = ...
    duration_seconds: float = ...
    edge_log: list[tuple[int, int]] = ...
    traces: list[Trace] = ...
    last_new_edge_run: int = ...
    runs_since_new_edge: int = ...
    saturated: bool = ...
    stopped_reason: str = ...
    adaptation_phase: int = ...
    unique_states: int = ...
    properties_satisfied: int = ...
    mutations_total: int = ...
    mutations_killed: int = ...
    seed_mutations_used: int = ...
    seed_mutations_productive: int = ...
    strategy_failures: dict[str, int] = ...
    ngram: int = ...
    seed_replays: list[dict[str, Any]] = ...
    rule_swarm_runs: int = ...
    swarm_stats: list[dict[str, Any]] = ...
    fault_pair_coverage: list[dict[str, Any]] = ...
    uncovered_fault_pairs: list[list[str]] = ...
    rule_fault_coverage: dict[str, dict[str, int]] = ...
    behavior_coverage: dict[str, dict[str, list[str]]] = ...
    property_stress: dict[str, dict[str, int]] = ...
    native_boundary_findings: list[dict[str, Any]] = ...
    coverage_gaps: list[dict[str, Any]] = ...
    lines_covered: int = ...
    lines_total: int = ...
    coordination_mode: str = ...
    coordination_degraded_reason: str = ...
    parallel_result_warning: str = ...
    parallel_fallback_reason: str = ...

    def summary(self) -> str:
        """Human-readable exploration summary."""
        ...

    @builtins.property
    def capabilities_used(self) -> dict[str, bool]:
        """Which exploration capabilities were active for this run.

        Exposes structured metadata so tooling (or an AI assistant) can
        identify what's available but wasn't exercised, and decide
        whether to suggest it based on context.
        """
        ...

    def reachability_suggestions(self) -> list[dict[str, Any]]:
        """Generate ``reachable()`` suggestions for branches not reached.

        Each suggestion is a structured dict an AI assistant can act on:

        - ``file``: source file path
        - ``line``: line number of the branch not reached
        - ``code``: the branch statement (``if``, ``for``, etc.)
        - ``suggestion``: a ``reachable()`` call to insert near that line
        - ``confidence``: ``"not_reached"`` — the explorer did not hit
          this line; it may be reachable with more runs or different faults
        - ``runs``: number of exploration runs in this session

        **Epistemic note**: these are branches the explorer did not reach.
        Adding ``reachable()`` lets future runs prove whether the branch
        is reachable or genuinely dead code.

        Returns an empty list if there are no coverage gaps.
        """
        ...

class Explorer:
    """Coverage-guided stateful exploration with checkpoints, energy scheduling, and seed mutation.

    The core exploration engine.  Runs ChaosTest rule sequences while tracking
    edge coverage (AFL-style), checkpointing interesting states, and branching
    from them with three orthogonal exploration dimensions:

    - **Swarm**: each run uses a random fault subset (different failure environments)
    - **Energy**: checkpoints that led to new edges are selected more often
    - **Seed mutation**: rule parameters that led to new coverage are stored on
      checkpoints and mutated (via ``ordeal.mutagen``) on the next branch —
      the AFL closed-loop adapted for typed stateful testing

    Compared to Hypothesis (random search + shrinking), the Explorer finds bugs
    at the intersection of features — the class of bugs that random testing
    almost never reaches.

    Example::

        from ordeal.explore import Explorer

        explorer = Explorer(MyChaosTest, target_modules=["myapp"])
        result = explorer.run(max_time=60)
        print(result.summary())
        # → Exploration: 500 runs, 25000 steps, 60.0s
        # → Coverage: 142 edges, 38 checkpoints
        # → Seed mutations: 312 used, 47 productive
    """

    ...

    def __init__(
        self,
        test_class: type,
        *,
        target_modules: list[str] | None = ...,
        seed: int = ...,
        max_checkpoints: int = ...,
        checkpoint_prob: float = ...,
        checkpoint_strategy: str = ...,
        fault_toggle_prob: float = ...,
        record_traces: bool = ...,
        workers: int = ...,
        share_edges: bool = ...,
        share_checkpoints: bool = ...,
        mutation_targets: list[str] | None = ...,
        seed_mutation_prob: float | None = ...,
        seed_mutation_respect_strategies: bool = ...,
        ngram: int = ...,
        corpus_dir: str | Path | None = ...,
        rule_swarm: bool = ...,
    ) -> None:
        """Initialize the exploration engine.

        Args:
            test_class: A ChaosTest subclass to explore.
            target_modules: Dotted module names for coverage (e.g. ``["myapp"]``).
            seed: RNG seed for reproducible runs.
            max_checkpoints: Checkpoint corpus size limit.
            checkpoint_prob: Probability of starting from a checkpoint.
            checkpoint_strategy: ``"energy"`` | ``"uniform"`` | ``"recent"``.
            fault_toggle_prob: Probability of nemesis action per step.
            record_traces: If True, keep full traces in the result.
            workers: Number of parallel worker processes. ``0`` means auto
                (uses ``os.cpu_count()``). Default ``1`` (sequential).
            mutation_targets: Dotted paths to functions to mutate
                (e.g. ``["myapp.service.process"]``).  Mutations become
                faults that the nemesis toggles during exploration.
                Killed mutants = your tests catch the bug.  Surviving
                mutants = test gap found.
            share_edges: When ``workers > 1``, use a shared-memory edge
                bitmap so workers skip edges already found by others.
                AFL-style: one byte per edge hash, single-byte atomic
                writes, zero locks.  Default ``True``.
            share_checkpoints: When ``workers > 1``, share checkpoints
                between workers via a shared-memory ring buffer.  Workers
                publish discoveries and subscribe to others' finds with
                global energy propagation — a checkpoint that leads to
                new edges for any worker gets higher priority for all.
                Default ``True``.
            seed_mutation_prob: Probability of mutating a productive seed
                instead of generating fresh parameters when branching from
                a checkpoint.  Default ``0.25`` (25%), matching the ratio
                used in ``mine()``'s Phase 2.  Set to ``0.0`` to disable
                seed mutation entirely.  Higher values (up to ``1.0``)
                make the explorer more exploitation-focused — useful when
                the rule parameter space is large relative to the state
                space.  See ``ordeal.mutagen`` for the mutation engine.
            seed_mutation_respect_strategies: If True, mutate productive
                seeds but keep values within common bounds implied by the
                rule's declared Hypothesis strategies.  Useful for control-
                plane systems where "nearby but still valid" mutations are
                more informative than unconstrained fuzzing.
            ngram: N-gram depth for edge coverage hashing.  ``1`` gives
                classic AFL single-edge hashing (``prev_loc XOR cur_loc``).
                ``2`` (the default) hashes the last 2 locations with the
                current one, capturing which branch led to each edge.
                Higher values capture deeper path context but have
                diminishing returns for Python's coarse line-level tracing.
                See :class:`CoverageCollector` for the full rationale.
            rule_swarm: When True, each exploration run includes each
                rule with independent probability 0.5 (fair coin flip),
                per the swarm testing algorithm (Groce et al., ISSTA
                2012).  Disabling some rules per run forces others to
                accumulate state (e.g. only inserts, no deletes → cache
                grows large → GC triggers).  At least one rule is always
                kept.  Default ``False``.
            corpus_dir: Directory for the persistent seed corpus.  Failing
                traces are saved here and replayed automatically on the
                next run for instant regression detection.  Default
                ``".ordeal/seeds"``.  Set to ``None`` to disable.
        """
        ...

    def save_state(self, path: str | Path) -> None:
        """Save exploration state to disk for later resumption.

        Persists the checkpoint corpus, discovered edges, state hashes,
        satisfied properties, and RNG state.  The file is a pickle — not
        intended for cross-version portability, but reliable for
        resume-after-interrupt on the same codebase.
        """
        ...

    def load_state(self, path: str | Path, *, allow_unsafe: bool = ...) -> dict[str, Any]:
        """Load saved exploration state, restoring checkpoints and edges.

        Returns a dict of counters (``total_runs``, ``total_steps``, etc.)
        that the caller should seed into the ``ExplorationResult``.
        """
        ...

    def run(
        self,
        *,
        max_time: float = ...,
        max_runs: int | None = ...,
        steps_per_run: int = ...,
        shrink: bool = ...,
        max_shrink_time: float = ...,
        patience: int = ...,
        progress: Callable[[ProgressSnapshot], None] | None = ...,
        resume_from: str | Path | None = ...,
        save_state_to: str | Path | None = ...,
        allow_unsafe_resume: bool = ...,
    ) -> ExplorationResult:
        """Run the coverage-guided exploration loop.

        Args:
            max_time: Wall-clock time limit in seconds.
            max_runs: Maximum number of runs (or ``None`` for time-only).
            steps_per_run: Max rule steps per run.
            shrink: If True, shrink failing traces after exploration.
            max_shrink_time: Time limit for shrinking each failure.
            patience: Stop after N consecutive runs without new edges. 0=disabled.
            progress: Optional callback for live progress updates.
            resume_from: Path to a saved state file from a previous run.
                Restores checkpoints, edges, and RNG state so exploration
                continues where it left off.
            save_state_to: Path to save exploration state on completion
                (and on interrupt).  Use with ``resume_from`` on the next
                run to continue exploration across sessions.
            allow_unsafe_resume: Permit loading trusted pickle state files
                passed via ``resume_from``. Disabled by default because
                pickle deserialization can execute arbitrary code.
        """
        ...
