# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
"\nThis type stub file was generated by pyright.\n"
_FINDING_EVIDENCE_SCHEMA = ...
_DIVERGENCE_EVIDENCE_SCHEMA = ...
