# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import hypothesis.strategies as st
from typing import Any

"\nThis type stub file was generated by pyright.\n"

@st.composite
def json_strategy(
    draw: st.DrawFn, schema: dict[str, Any] | None = ..., max_depth: int = ...
) -> st.SearchStrategy:
    """Hypothesis strategy for valid JSON values.

    Without *schema*, generates random valid JSON: objects, arrays, strings,
    numbers, booleans, and null, nested up to *max_depth* levels.

    With *schema* (a dict describing structure), generates conforming
    instances.  Schema keys are field names; values are either:

    - A Python type (``str``, ``int``, ``float``, ``bool``)
    - ``None`` for JSON null
    - A ``list`` with one element describing the item type
    - A nested ``dict`` for sub-objects

    Example::

        from ordeal.grammar import json_strategy

        # Random valid JSON
        @given(json_strategy())
        def test_roundtrip(val):
            assert json.loads(json.dumps(val)) == val or isinstance(val, float)

        # Schema-constrained
        @given(json_strategy(schema={"name": str, "age": int, "tags": [str]}))
        def test_user(user):
            assert isinstance(user["name"], str)
            assert isinstance(user["age"], int)
    """
    ...

@st.composite
def sql_strategy(
    draw: st.DrawFn, dialect: str = ..., tables: dict[str, list[str]] | None = ...
) -> st.SearchStrategy[str]:
    """Hypothesis strategy for valid SQL queries.

    Generates SELECT, INSERT, UPDATE, and DELETE statements with valid
    syntax.  If *tables* is provided (mapping table names to column name
    lists), uses those names; otherwise generates plausible identifiers.

    The *dialect* parameter is reserved for future dialect-specific syntax;
    currently all output follows ANSI/SQLite conventions.

    Example::

        from ordeal.grammar import sql_strategy

        tables = {"users": ["id", "name", "email"], "orders": ["id", "user_id", "total"]}

        @given(sql_strategy(tables=tables))
        def test_parser_accepts(query):
            # Should never raise a parse error
            parse_sql(query)
    """
    ...

@st.composite
def url_strategy(draw: st.DrawFn, schemes: list[str] | None = ...) -> st.SearchStrategy[str]:
    """Hypothesis strategy for valid URLs.

    Generates URLs with various schemes, hosts, paths, query parameters,
    and fragments.  If *schemes* is given, restricts to those schemes;
    otherwise picks from common ones (http, https, ftp, etc.).

    Example::

        from ordeal.grammar import url_strategy

        @given(url_strategy(schemes=["https"]))
        def test_https_only(url):
            assert url.startswith("https://")
    """
    ...

@st.composite
def email_strategy(draw: st.DrawFn) -> st.SearchStrategy[str]:
    """Hypothesis strategy for valid email addresses.

    Generates addresses with varied local parts (dots, plus tags, digits),
    domains, and TLDs.  Focuses on structurally valid but diverse inputs.

    Example::

        from ordeal.grammar import email_strategy

        @given(email_strategy())
        def test_validate_accepts(email):
            assert "@" in email
            assert validate_email(email)
    """
    ...

@st.composite
def path_strategy(draw: st.DrawFn) -> st.SearchStrategy[str]:
    """Hypothesis strategy for valid file paths (Unix and Windows).

    Generates both Unix-style (``/usr/local/bin``) and Windows-style
    (``C:\\\\Users\\\\docs``) paths with varied depth, extensions, and
    special directory names.

    Example::

        from ordeal.grammar import path_strategy

        @given(path_strategy())
        def test_path_handling(path):
            result = normalize(path)
            assert isinstance(result, str)
    """
    ...

@st.composite
def csv_strategy(
    draw: st.DrawFn, columns: list[str] | None = ..., rows: int | None = ...
) -> st.SearchStrategy[str]:
    """Hypothesis strategy for valid CSV data.

    Generates CSV text with a header row and data rows.  If *columns* is
    provided, uses those as headers; otherwise generates random headers.
    If *rows* is given, generates exactly that many data rows; otherwise
    picks a random count (0-20).

    Example::

        from ordeal.grammar import csv_strategy

        @given(csv_strategy(columns=["name", "age", "score"]))
        def test_csv_parser(csv_text):
            records = parse_csv(csv_text)
            assert all("name" in r for r in records)
    """
    ...

@st.composite
def xml_strategy(
    draw: st.DrawFn, tag: str | None = ..., max_depth: int = ...
) -> st.SearchStrategy[str]:
    """Hypothesis strategy for valid XML documents.

    Generates well-formed XML with nested elements, attributes, and text
    content.  If *tag* is provided, uses it as the root element name;
    otherwise generates a random tag name.

    Example::

        from ordeal.grammar import xml_strategy

        @given(xml_strategy(tag="config", max_depth=3))
        def test_xml_parser(xml_text):
            root = ET.fromstring(xml_text)
            assert root.tag == "config"
    """
    ...

def regex_strategy(pattern: str) -> st.SearchStrategy[str]:
    """Hypothesis strategy that generates strings matching a regex pattern.

    Wraps ``hypothesis.strategies.from_regex`` with ``fullmatch=True`` so
    every generated string matches the entire pattern.

    Example::

        from ordeal.grammar import regex_strategy

        @given(regex_strategy(r"[A-Z]{2,4}-\\d{1,5}"))
        def test_ticket_format(ticket_id):
            assert re.fullmatch(r"[A-Z]{2,4}-\\d{1,5}", ticket_id)
    """
    ...

@st.composite
def structured_strategy(draw: st.DrawFn, example: Any) -> st.SearchStrategy:
    """Infer a strategy from a concrete example value.

    Takes a concrete value and produces structurally similar values.  The
    structure (dict keys, list element types, nesting) is preserved while
    the leaf values vary.

    Supported types: ``dict``, ``list``, ``tuple``, ``str``, ``int``,
    ``float``, ``bool``, ``None``.

    Example::

        from ordeal.grammar import structured_strategy

        template = {"name": "Alice", "age": 30, "scores": [95, 88]}

        @given(structured_strategy(template))
        def test_user_record(user):
            assert isinstance(user["name"], str)
            assert isinstance(user["age"], int)
            assert all(isinstance(s, int) for s in user["scores"])
    """
    ...

_PUBLIC_STRATEGIES = ...

def catalog() -> list[dict[str, str]]:
    """Discover all grammar-based strategies via runtime introspection.

    Returns a list of dicts with ``name``, ``qualname``, ``doc``,
    ``signature``, and ``parameters``.
    """
    ...
