# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from typing import Any, Callable

"\nThis type stub file was generated by pyright.\n"
_MISSING = ...

class Invariant:
    """A named, composable assertion."""

    def __init__(self, name: str, check_fn: Callable[..., None]) -> None: ...
    def __call__(self, value: Any = ..., *, name: str | None = ...) -> Any:
        """Run the invariant check, or return self if called with no args.

        This makes both patterns work::

            finite(value)   # check immediately
            finite()        # returns the invariant (for use as a parameter)
        """
        ...

    def __and__(self, other: Invariant) -> Invariant:
        """Compose two invariants: ``(a & b)(x)`` checks both ``a`` and ``b``.

        Use this to build domain-specific compound checks from simple
        invariants::

            check = bounded(0, 1) & finite
            check(value)  # raises on out-of-range, NaN, or Inf

        The operator is associative and flattens nested compositions,
        so ``a & b & c`` produces a single flat check list.
        """
        ...

    def __repr__(self) -> str: ...

class _Composed(Invariant):
    """Multiple invariants composed with ``&``."""

    def __init__(self, checks: list[Invariant]) -> None: ...

no_nan = ...
no_inf = ...
finite = ...

def bounded(lo: float, hi: float) -> Invariant:
    """Value (or all elements) must be in [lo, hi]."""
    ...

def monotonic(*, strict: bool = ...) -> Invariant:
    """Sequence must be monotonically non-decreasing (or strictly increasing)."""
    ...

def unique(*, key: Callable | None = ...) -> Invariant:
    """All elements must be unique (optionally by *key*)."""
    ...

def non_empty() -> Invariant:
    """Value must not be empty / falsy."""
    ...

def unit_normalized(*, tol: float = ...) -> Invariant:
    """Each row vector has L2 norm within *tol* of 1.0.

    For 1-D arrays, checks the single vector norm.
    For 2-D arrays, checks each row independently.
    """
    ...

def orthonormal(*, tol: float = ...) -> Invariant:
    """Rows of a 2-D array form an orthonormal set.

    Checks that ``M @ M.T`` is close to the identity matrix.
    """
    ...

def symmetric(*, tol: float = ...) -> Invariant:
    """2-D array is symmetric: ``M == M.T`` within tolerance."""
    ...

def positive_semi_definite(*, tol: float = ...) -> Invariant:
    """All eigenvalues of a square matrix are >= -tol."""
    ...

def rank_bounded(min_rank: int = ..., max_rank: int | None = ...) -> Invariant:
    """Matrix rank is within [min_rank, max_rank]."""
    ...

def mean_bounded(lo: float, hi: float) -> Invariant:
    """Mean of a numeric sequence must be in [lo, hi]."""
    ...

def variance_bounded(lo: float, hi: float) -> Invariant:
    """Variance of a numeric sequence must be in [lo, hi]."""
    ...

def catalog() -> list[dict[str, str]]:
    """Discover all available invariants via runtime introspection.

    Returns a list of dicts with ``name``, ``type`` (instance or factory),
    ``doc``, and ``signature`` (for factories).  Derived from module globals
    — new invariants appear automatically.
    """
    ...
