"""Evidence-first migration workflow from a base module to a candidate.

The workflow composes ordeal's existing capabilities in one ordered run:

``audit base -> mine candidate -> diff -> classify -> save -> mutate -> scan``

Mined properties remain candidate contracts. They are never promoted to
correctness claims. Explicit :class:`ordeal.auto.ContractCheck` instances are
the domain assertions used by mutation testing and the candidate-only scan.
"""

from __future__ import annotations

import hashlib
import importlib
import json
import math
import re
from collections.abc import Callable, Collection, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from ordeal.audit import ModuleAudit
from ordeal.audit import audit as _audit
from ordeal.auto import (
    ContractCheck,
    ScanResult,
    _call_contract_predicate,
    _call_sync,
    _get_public_functions,
)
from ordeal.auto import (
    scan_module as _scan_module,
)
from ordeal.diff import DiffResult, DiffWitness, Mismatch, _approx_equal
from ordeal.diff import diff as _diff
from ordeal.mine import (
    STRUCTURAL_LIMITATIONS,
    MineModuleResult,
)
from ordeal.mine import (
    mine_module as _mine_module,
)
from ordeal.mutations import MutationResult
from ordeal.mutations import mutate as _mutate

StageStatus = Literal["passed", "failed", "blocked"]
ChangeKind = Literal["behavior", "added", "removed"]
ChangeClassification = Literal["intended", "unexpected"]
ChangeClassifier = Callable[
    ["MigrationChange"],
    ChangeClassification | tuple[ChangeClassification, str],
]

_SCHEMA_VERSION = 1
_GENERATED_HEADER = '"""Generated by `ordeal migrate`.'


@dataclass(frozen=True)
class MigrationStage:
    """One ordered stage and its evidence status."""

    name: str
    status: StageStatus
    summary: str


@dataclass(frozen=True)
class CandidateContract:
    """A property observed while mining the candidate implementation."""

    function: str
    property: str
    holds: int
    total: int
    confidence: float
    source: str = "mined_hypothesis"


@dataclass
class MigrationChange:
    """One behavioral or public-surface change between base and candidate."""

    id: str
    function: str
    kind: ChangeKind
    mismatch: Mismatch | None = None
    witness: DiffWitness | None = None
    regression_options: dict[str, object] = field(default_factory=dict)
    classification: ChangeClassification = "unexpected"
    reason: str = "not declared as intended"

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe evidence record for this change."""
        record: dict[str, object] = {
            "id": self.id,
            "function": self.function,
            "kind": self.kind,
            "classification": self.classification,
            "reason": self.reason,
        }
        if self.mismatch is not None:
            record.update(
                {
                    "args": _display_value(self.mismatch.args),
                    "base_outcome": _display_value(self.mismatch.output_a),
                    "candidate_outcome": _display_value(self.mismatch.output_b),
                }
            )
        if self.witness is not None:
            record["witness"] = {
                "differences": list(self.witness.differences),
                "replay_attempts": self.witness.replay_attempts,
                "replay_matches": self.witness.replay_matches,
                "replay_verified": self.witness.replay_verified,
                "artifact_id": self.witness.artifact.get("artifact_id"),
                "artifact_path": self.witness.artifact_path,
            }
        if self.regression_options:
            record["regression_options"] = dict(self.regression_options)
        return record


@dataclass(frozen=True)
class RegressionArtifacts:
    """Paths and persistence evidence for unexpected divergences."""

    evidence_path: Path
    regression_path: Path
    regression_cases: tuple[dict[str, object], ...] = ()
    unsupported_change_ids: tuple[str, ...] = ()
    error: str | None = None


@dataclass(frozen=True)
class MutationGate:
    """Mutation result or the exact reason mutation evidence is unavailable."""

    status: StageStatus
    threshold: float
    result: MutationResult | None = None
    reason: str | None = None


@dataclass
class MigrationResult:
    """Structured evidence from a complete base-to-candidate workflow."""

    base: str
    candidate: str
    stages: list[MigrationStage]
    base_audit: ModuleAudit
    candidate_mining: MineModuleResult
    candidate_contracts: list[CandidateContract]
    changes: list[MigrationChange]
    artifacts: RegressionArtifacts
    mutation: MutationGate
    candidate_scan: ScanResult
    diff_errors: dict[str, str] = field(default_factory=dict)
    explicit_invariant_count: int = 0
    mining_limitations: list[str] = field(default_factory=lambda: list(STRUCTURAL_LIMITATIONS))

    @property
    def unexpected_changes(self) -> list[MigrationChange]:
        """Return divergences not explicitly classified as intended."""
        return [change for change in self.changes if change.classification == "unexpected"]

    @property
    def intended_changes(self) -> list[MigrationChange]:
        """Return divergences explicitly classified as intended."""
        return [change for change in self.changes if change.classification == "intended"]

    @property
    def protected_within_measured_scope(self) -> bool:
        """Whether every required evidence gate passed within configured scope."""
        audit_blocked = bool(getattr(self.base_audit, "blocking_reason", None))
        mutation_result = self.mutation.result
        mutation_fully_killed = bool(
            mutation_result is not None
            and mutation_result.total > 0
            and mutation_result.killed == mutation_result.total
        )
        return (
            not audit_blocked
            and not self.unexpected_changes
            and not self.diff_errors
            and not self.artifacts.unsupported_change_ids
            and self.artifacts.error is None
            and self.explicit_invariant_count > 0
            and self.mutation.status == "passed"
            and mutation_fully_killed
            and self.candidate_scan.passed
        )

    @property
    def ready(self) -> bool:
        """Alias for :attr:`protected_within_measured_scope`."""
        return self.protected_within_measured_scope

    def summary(self) -> str:
        """Render the workflow in stage order without overstating evidence."""
        lines = [f"ordeal migrate {self.base} -> {self.candidate}"]
        for stage in self.stages:
            lines.append(f"  {stage.status.upper():7} {stage.name}: {stage.summary}")
        lines.append(
            "  RESULT  "
            + (
                "PROTECTIVE_WITHIN_MEASURED_SCOPE"
                if self.protected_within_measured_scope
                else "INCOMPLETE"
            )
        )
        lines.append(
            "  NOTE    mined properties are hypotheses; explicit invariants, mutation, "
            "and candidate scan carry correctness/protection evidence"
        )
        return "\n".join(lines)

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe result for CLI and agent consumers."""
        mutation_result = self.mutation.result
        return {
            "schema_version": _SCHEMA_VERSION,
            "base": self.base,
            "candidate": self.candidate,
            "protected_within_measured_scope": self.protected_within_measured_scope,
            "stages": [
                {"name": stage.name, "status": stage.status, "summary": stage.summary}
                for stage in self.stages
            ],
            "candidate_contracts": [
                {
                    "function": contract.function,
                    "property": contract.property,
                    "holds": contract.holds,
                    "total": contract.total,
                    "confidence": contract.confidence,
                    "source": contract.source,
                }
                for contract in self.candidate_contracts
            ],
            "changes": [change.to_dict() for change in self.changes],
            "diff_errors": dict(self.diff_errors),
            "explicit_invariant_count": self.explicit_invariant_count,
            "artifacts": {
                "evidence_path": self.artifacts.evidence_path.as_posix(),
                "regression_path": self.artifacts.regression_path.as_posix(),
                "regression_cases": len(self.artifacts.regression_cases),
                "unsupported_change_ids": list(self.artifacts.unsupported_change_ids),
                "error": self.artifacts.error,
            },
            "mutation": {
                "status": self.mutation.status,
                "threshold": self.mutation.threshold,
                "reason": self.mutation.reason,
                "killed": mutation_result.killed if mutation_result is not None else None,
                "total": mutation_result.total if mutation_result is not None else None,
                "score": mutation_result.score if mutation_result is not None else None,
            },
            "candidate_scan": {
                "passed": self.candidate_scan.passed,
                "total": self.candidate_scan.total,
                "failed": self.candidate_scan.failed,
                "verdict_counts": self.candidate_scan.verdict_counts,
            },
            "mining_limitations": list(self.mining_limitations),
        }


def _slug(value: str) -> str:
    """Return a stable path-safe module slug."""
    return re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_") or "module"


def _default_evidence_path(base: str, candidate: str) -> Path:
    """Return the per-pair evidence path."""
    return Path(".ordeal/migrations") / f"{_slug(base)}_to_{_slug(candidate)}.json"


def _default_regression_path(candidate: str) -> Path:
    """Return the generated pytest path for a candidate module."""
    return Path("tests") / f"test_ordeal_migration_{_slug(candidate)}.py"


def _display_value(value: object) -> dict[str, object]:
    """Represent an arbitrary outcome without claiming it is replayable."""
    if isinstance(value, BaseException):
        return {
            "kind": "exception",
            "type": f"{type(value).__module__}.{type(value).__qualname__}",
            "message": str(value),
        }
    return {
        "kind": "return",
        "type": f"{type(value).__module__}.{type(value).__qualname__}",
        "repr": repr(value),
    }


def _encode_value(value: object) -> object:
    """Encode common witness values into JSON-safe, exactly replayable data."""
    if value is None or isinstance(value, (bool, int, str)):
        return value
    if isinstance(value, float):
        if not math.isfinite(value):
            return {"__ordeal_type__": "float", "value": repr(value)}
        return value
    if isinstance(value, bytes):
        return {"__ordeal_type__": "bytes", "hex": value.hex()}
    if isinstance(value, Path):
        return {"__ordeal_type__": "path", "value": value.as_posix()}
    if isinstance(value, list):
        return [_encode_value(item) for item in value]
    if isinstance(value, tuple):
        return {"__ordeal_type__": "tuple", "items": [_encode_value(item) for item in value]}
    if isinstance(value, set):
        return {"__ordeal_type__": "set", "items": [_encode_value(item) for item in value]}
    if isinstance(value, frozenset):
        return {
            "__ordeal_type__": "frozenset",
            "items": [_encode_value(item) for item in value],
        }
    if isinstance(value, Mapping):
        return {
            "__ordeal_type__": "dict",
            "items": [[_encode_value(key), _encode_value(item)] for key, item in value.items()],
        }
    raise TypeError(
        f"{type(value).__module__}.{type(value).__qualname__} is not a replayable literal"
    )


def _decode_value(value: object) -> object:
    """Decode data written by :func:`_encode_value`."""
    if isinstance(value, list):
        return [_decode_value(item) for item in value]
    if not isinstance(value, dict) or "__ordeal_type__" not in value:
        return value
    kind = value["__ordeal_type__"]
    if kind == "bytes":
        return bytes.fromhex(str(value["hex"]))
    if kind == "path":
        return Path(str(value["value"]))
    if kind == "float":
        return float(str(value["value"]))
    items = list(value.get("items", []))
    if kind == "tuple":
        return tuple(_decode_value(item) for item in items)
    if kind == "set":
        return {_decode_value(item) for item in items}
    if kind == "frozenset":
        return frozenset(_decode_value(item) for item in items)
    if kind == "dict":
        return {
            _decode_value(pair[0]): _decode_value(pair[1])
            for pair in items
            if isinstance(pair, list) and len(pair) == 2
        }
    raise ValueError(f"unknown ordeal migration value type: {kind!r}")


def _canonical_state(value: object) -> object:
    """Canonicalize replay state the same way immutable diff witnesses do."""
    if isinstance(value, Mapping):
        return {str(key): _canonical_state(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return tuple(_canonical_state(item) for item in value)
    if isinstance(value, (set, frozenset)):
        return frozenset(_canonical_state(item) for item in value)
    return value


def replay_migration_case(case: Mapping[str, object]) -> None:
    """Replay one saved unexpected divergence against its candidate module."""
    candidate = str(case["candidate"])
    function = str(case["function"])
    kind = str(case["kind"])
    module = importlib.import_module(candidate)

    if kind == "added":
        if hasattr(module, function):
            raise AssertionError(f"unexpected public callable still present: {function}")
        return
    if kind == "removed":
        if not hasattr(module, function):
            raise AssertionError(f"expected public callable is still missing: {function}")
        return
    if kind != "behavior":
        raise ValueError(f"unknown migration regression kind: {kind!r}")

    func = getattr(module, function)
    kwargs_value = _decode_value(case["kwargs"])
    if not isinstance(kwargs_value, dict):
        raise TypeError("migration regression kwargs must decode to a dict")
    expected = case["expected"]
    if not isinstance(expected, Mapping):
        raise TypeError("migration regression expected outcome must be a mapping")

    observed_error: BaseException | None = None
    actual: object = None
    try:
        actual = _call_sync(func, **kwargs_value)
    except BaseException as exc:
        observed_error = exc

    if expected.get("kind") == "exception":
        expected_type = f"{expected['type_module']}.{expected['type_qualname']}"
        if observed_error is None:
            raise AssertionError(f"candidate did not raise {expected_type}: {expected['message']}")
        observed_type = f"{type(observed_error).__module__}.{type(observed_error).__qualname__}"
        if observed_type != expected_type or str(observed_error) != str(expected["message"]):
            raise AssertionError(
                "candidate raised a different exception: "
                f"{type(observed_error).__name__}: {observed_error}"
            ) from observed_error
    else:
        if observed_error is not None:
            raise observed_error
        expected_value = _decode_value(expected["value"])
        comparison_options = case.get("comparison", {})
        if not isinstance(comparison_options, Mapping):
            raise TypeError("migration regression comparison must be a mapping")
        rtol_value = comparison_options.get("rtol")
        atol_value = comparison_options.get("atol")
        if rtol_value is not None or atol_value is not None:
            matches = _approx_equal(
                actual,
                expected_value,
                float(rtol_value or 1e-9),
                float(atol_value or 0.0),
            )
        else:
            comparison = actual == expected_value
            try:
                matches = bool(comparison)
            except (TypeError, ValueError):
                matches = False
        if not matches:
            raise AssertionError(
                f"candidate returned {actual!r}; expected preserved base outcome "
                f"{expected_value!r}"
            )

    if "expected_mutated_arguments" in case:
        expected_arguments = _decode_value(case["expected_mutated_arguments"])
        if _canonical_state(kwargs_value) != _canonical_state(expected_arguments):
            raise AssertionError(
                f"candidate mutated arguments to {kwargs_value!r}; expected preserved "
                f"base state {expected_arguments!r}"
            )


def _case_for_change(
    change: MigrationChange,
    *,
    candidate: str,
) -> dict[str, object]:
    """Build one executable regression case or raise when it cannot be replayed."""
    payload: dict[str, object] = {
        "change_id": change.id,
        "candidate": candidate,
        "function": change.function,
        "kind": change.kind,
    }
    if change.kind == "behavior":
        if change.mismatch is None or change.witness is None:
            raise TypeError("behavior change has no mismatch witness")
        unsupported = {"receiver_state", "side_effects"} & set(change.witness.differences)
        if unsupported:
            joined = ", ".join(sorted(unsupported))
            raise TypeError(f"cannot persist selected state channel(s): {joined}")
        if change.regression_options.get("custom_compare"):
            raise TypeError("cannot persist a custom diff comparator")
        if change.regression_options.get("custom_normalize"):
            raise TypeError("cannot persist a custom diff normalizer")
        payload["kwargs"] = _encode_value(change.mismatch.args)
        payload["expected_mutated_arguments"] = _encode_value(
            change.witness.outcome_a.mutated_arguments
        )
        comparison = {
            key: change.regression_options[key]
            for key in ("rtol", "atol")
            if change.regression_options.get(key) is not None
        }
        if comparison:
            payload["comparison"] = comparison
        base_outcome = change.mismatch.output_a
        if isinstance(base_outcome, BaseException):
            payload["expected"] = {
                "kind": "exception",
                "type_module": type(base_outcome).__module__,
                "type_qualname": type(base_outcome).__qualname__,
                "message": str(base_outcome),
            }
        else:
            payload["expected"] = {
                "kind": "return",
                "value": _encode_value(base_outcome),
            }
    digest = hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()[:12]
    payload["id"] = f"{change.id}:{digest}"
    return payload


def _load_existing_cases(
    path: Path,
    *,
    base: str,
    candidate: str,
) -> list[dict[str, object]]:
    """Load prior cases for the same module pair."""
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != _SCHEMA_VERSION:
        raise ValueError(f"unsupported migration evidence schema in {path}")
    if data.get("base") != base or data.get("candidate") != candidate:
        raise ValueError(f"migration evidence at {path} belongs to another module pair")
    cases = data.get("regression_cases", [])
    if not isinstance(cases, list):
        raise ValueError(f"invalid regression_cases in {path}")
    return [dict(case) for case in cases if isinstance(case, dict)]


def _render_regression_file(cases: Sequence[Mapping[str, object]]) -> str:
    """Render a standalone pytest module backed by replay helpers."""
    return "\n".join(
        [
            _GENERATED_HEADER,
            "",
            "Review and commit this file with its migration evidence artifact.",
            '"""',
            "",
            "import pytest",
            "",
            "from ordeal.migration import replay_migration_case",
            "",
            f"CASES = {list(cases)!r}",
            "",
            "",
            '@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])',
            "def test_ordeal_migration_regression(case: dict[str, object]) -> None:",
            '    """Keep one previously unexpected candidate divergence fixed."""',
            "    replay_migration_case(case)",
            "",
        ]
    )


def _selector_matches(selector: str, *, change_id: str, function: str) -> bool:
    """Return whether an intended-change selector names a change."""
    return selector in {change_id, function, f"*:{function}"}


def _classify_change(
    change: MigrationChange,
    *,
    intended: Mapping[str, str],
    classifier: ChangeClassifier | None,
) -> None:
    """Apply explicit classification without inferring intent from parity."""
    if classifier is not None:
        decision = classifier(change)
        if isinstance(decision, tuple):
            classification, reason = decision
        else:
            classification, reason = decision, "classified by callback"
        if classification not in ("intended", "unexpected"):
            raise ValueError(f"invalid change classification: {classification!r}")
        change.classification = classification
        change.reason = reason
        return
    for selector, reason in intended.items():
        if _selector_matches(selector, change_id=change.id, function=change.function):
            change.classification = "intended"
            change.reason = reason
            return


def _normalize_intended_changes(
    intended_changes: Collection[str] | Mapping[str, str],
) -> dict[str, str]:
    """Normalize simple selectors and selector-to-reason mappings."""
    if isinstance(intended_changes, Mapping):
        return {str(selector): str(reason) for selector, reason in intended_changes.items()}
    return {str(selector): "declared as intended" for selector in intended_changes}


def _candidate_contracts(result: MineModuleResult) -> list[CandidateContract]:
    """Flatten universal mined observations while labeling their weak status."""
    contracts: list[CandidateContract] = []
    for function, mine_result in sorted(result.per_function.items()):
        for prop in mine_result.universal:
            contracts.append(
                CandidateContract(
                    function=function,
                    property=prop.name,
                    holds=prop.holds,
                    total=prop.total,
                    confidence=prop.confidence,
                )
            )
    for prop in result.cross_function:
        if prop.total > 0 and prop.holds == prop.total:
            contracts.append(
                CandidateContract(
                    function=f"{prop.function_a}<->{prop.function_b}",
                    property=prop.relation,
                    holds=prop.holds,
                    total=prop.total,
                    confidence=prop.confidence,
                )
            )
    return contracts


def _run_explicit_invariants(
    candidate: str,
    invariants: Mapping[str, Sequence[ContractCheck]],
) -> None:
    """Execute explicit contracts against the live candidate module."""
    module = importlib.import_module(candidate)
    for function, checks in invariants.items():
        func: object = module
        for part in function.split("."):
            func = getattr(func, part)
        for check in checks:
            error: BaseException | None = None
            try:
                value = _call_sync(func, **dict(check.kwargs))
            except BaseException as exc:
                error = exc
                value = None
            passed = _call_contract_predicate(
                check.predicate,
                value,
                func=func,
                call_context=getattr(func, "__ordeal_last_call_context__", None),
                kwargs=check.kwargs,
                error=error,
            )
            if not passed:
                detail = f" ({type(error).__name__}: {error})" if error is not None else ""
                raise AssertionError(f"explicit invariant failed: {function}:{check.name}{detail}")


def _save_artifacts(
    *,
    base: str,
    candidate: str,
    changes: Sequence[MigrationChange],
    intended: Mapping[str, str],
    evidence_path: Path,
    regression_path: Path,
) -> RegressionArtifacts:
    """Persist unexpected changes and merge replayable witnesses across reruns."""
    unsupported: list[str] = []
    try:
        existing = _load_existing_cases(
            evidence_path,
            base=base,
            candidate=candidate,
        )
        intended_ids = {change.id for change in changes if change.classification == "intended"}
        existing = [
            case
            for case in existing
            if str(case.get("change_id")) not in intended_ids
            and not any(
                _selector_matches(
                    selector,
                    change_id=str(case.get("change_id", "")),
                    function=str(case.get("function", "")),
                )
                for selector in intended
            )
        ]
        current_cases: list[dict[str, object]] = []
        for change in changes:
            if change.classification != "unexpected":
                continue
            try:
                current_cases.append(_case_for_change(change, candidate=candidate))
            except (TypeError, ValueError):
                unsupported.append(change.id)

        by_id = {str(case["id"]): case for case in [*existing, *current_cases]}
        cases = list(by_id.values())
        evidence = {
            "schema_version": _SCHEMA_VERSION,
            "base": base,
            "candidate": candidate,
            "changes": [change.to_dict() for change in changes],
            "regression_cases": cases,
            "unsupported_change_ids": unsupported,
            "mining_limitations": list(STRUCTURAL_LIMITATIONS),
            "regression_path": regression_path.as_posix(),
        }
        evidence_path.parent.mkdir(parents=True, exist_ok=True)
        evidence_path.write_text(
            json.dumps(evidence, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        if cases or regression_path.exists():
            if regression_path.exists() and not regression_path.read_text(
                encoding="utf-8"
            ).startswith(_GENERATED_HEADER):
                raise ValueError(
                    f"refusing to overwrite non-generated regression file: {regression_path}"
                )
            regression_path.parent.mkdir(parents=True, exist_ok=True)
            regression_path.write_text(_render_regression_file(cases), encoding="utf-8")
        return RegressionArtifacts(
            evidence_path=evidence_path,
            regression_path=regression_path,
            regression_cases=tuple(cases),
            unsupported_change_ids=tuple(unsupported),
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return RegressionArtifacts(
            evidence_path=evidence_path,
            regression_path=regression_path,
            unsupported_change_ids=tuple(unsupported),
            error=str(exc),
        )


def migrate(
    base: str,
    candidate: str,
    *,
    intended_changes: Collection[str] | Mapping[str, str] = (),
    classify: ChangeClassifier | None = None,
    invariants: Mapping[str, Sequence[ContractCheck]] | None = None,
    test_dir: str = "tests",
    audit_max_examples: int = 20,
    mine_max_examples: int = 200,
    diff_max_examples: int = 100,
    scan_max_examples: int = 50,
    mutation_preset: Literal["essential", "standard", "thorough"] = "standard",
    mutation_workers: int = 1,
    mutation_threshold: float = 1.0,
    mine_fixtures: Mapping[str, Any] | None = None,
    diff_options: Mapping[str, Mapping[str, Any]] | None = None,
    scan_options: Mapping[str, Any] | None = None,
    evidence_path: str | Path | None = None,
    regression_path: str | Path | None = None,
) -> MigrationResult:
    """Run the ordered evidence workflow from *base* to *candidate*.

    Unexpected divergences are saved as executable parity regressions when
    their witnesses are replayable literals. A run with a still-unexpected
    divergence deliberately blocks mutation because a mutation score is not
    meaningful while the resulting regression baseline fails. Re-run after
    fixing the candidate, or classify the change as intended.

    ``invariants`` are explicit candidate contracts keyed by public callable
    name. They are executed directly during mutation and passed to the final
    candidate-only scan. Mined properties are returned as hypotheses only.

    Args:
        base: Importable base module path.
        candidate: Importable candidate module path.
        intended_changes: Function names or stable ``kind:function`` selectors,
            optionally mapped to human-readable reasons.
        classify: Optional callback for programmatic change classification.
        invariants: Explicit semantic checks keyed by candidate callable name.
        test_dir: Existing test directory used by the base audit.
        audit_max_examples: Example budget for the base audit.
        mine_max_examples: Example budget for candidate contract mining.
        diff_max_examples: Example budget for each shared callable diff.
        scan_max_examples: Example budget for the candidate-only scan.
        mutation_preset: Mutation operator preset for resulting tests.
        mutation_workers: Mutation worker count.
        mutation_threshold: Minimum measured mutation score, default 100%.
        mine_fixtures: Global fixture overrides for candidate mining.
        diff_options: Per-function options forwarded to :func:`ordeal.diff.diff`.
        scan_options: Additional options forwarded to candidate ``scan_module``.
        evidence_path: JSON artifact path; defaults under ``.ordeal/migrations``.
        regression_path: Generated pytest path; defaults under ``tests``.

    Returns:
        A :class:`MigrationResult` with evidence for all seven ordered stages.
    """
    if not 0.0 <= mutation_threshold <= 1.0:
        raise ValueError("mutation_threshold must be between 0 and 1")
    explicit_invariants = {str(name): list(checks) for name, checks in (invariants or {}).items()}
    explicit_invariant_count = sum(len(checks) for checks in explicit_invariants.values())
    intended = _normalize_intended_changes(intended_changes)
    evidence = (
        Path(evidence_path)
        if evidence_path is not None
        else _default_evidence_path(base, candidate)
    )
    regression = (
        Path(regression_path)
        if regression_path is not None
        else _default_regression_path(candidate)
    )
    stages: list[MigrationStage] = []

    base_audit = _audit(
        base,
        test_dir=test_dir,
        max_examples=audit_max_examples,
        workers=mutation_workers,
        contract_checks=explicit_invariants,
    )
    audit_block = getattr(base_audit, "blocking_reason", None)
    stages.append(
        MigrationStage(
            "audit base",
            "blocked" if audit_block else "passed",
            str(audit_block or base_audit.test_protection_view()["summary"]),
        )
    )

    candidate_mining = _mine_module(
        candidate,
        max_examples=mine_max_examples,
        **dict(mine_fixtures or {}),
    )
    candidate_contracts = _candidate_contracts(candidate_mining)
    stages.append(
        MigrationStage(
            "mine candidate contracts",
            "passed",
            f"{len(candidate_contracts)} observed contract hypothesis/hypotheses",
        )
    )

    base_module = importlib.import_module(base)
    candidate_module = importlib.import_module(candidate)
    base_functions = dict(_get_public_functions(base_module))
    candidate_functions = dict(_get_public_functions(candidate_module))
    changes: list[MigrationChange] = []
    diff_errors: dict[str, str] = {}
    for function in sorted(base_functions.keys() & candidate_functions.keys()):
        options = dict((diff_options or {}).get(function, {}))
        options.pop("max_examples", None)
        try:
            result: DiffResult = _diff(
                base_functions[function],
                candidate_functions[function],
                max_examples=diff_max_examples,
                **options,
            )
        except (TypeError, ValueError) as exc:
            diff_errors[function] = str(exc)
            continue
        if result.divergent:
            if result.witness is None or len(result.mismatches) != 1:
                diff_errors[function] = "divergent diff did not provide one canonical witness"
                continue
            changes.append(
                MigrationChange(
                    id=f"behavior:{function}",
                    function=function,
                    kind="behavior",
                    mismatch=result.mismatches[-1],
                    witness=result.witness,
                    regression_options={
                        **({"rtol": options["rtol"]} if options.get("rtol") is not None else {}),
                        **({"atol": options["atol"]} if options.get("atol") is not None else {}),
                        **({"custom_compare": True} if options.get("compare") else {}),
                        **({"custom_normalize": True} if options.get("normalize") else {}),
                    },
                )
            )
        elif result.status == "inconclusive":
            diff_errors[function] = result.reason or "differential comparison was inconclusive"
    for function in sorted(candidate_functions.keys() - base_functions.keys()):
        changes.append(
            MigrationChange(
                id=f"added:{function}",
                function=function,
                kind="added",
            )
        )
    for function in sorted(base_functions.keys() - candidate_functions.keys()):
        changes.append(
            MigrationChange(
                id=f"removed:{function}",
                function=function,
                kind="removed",
            )
        )
    diff_status: StageStatus = "failed" if diff_errors else "passed"
    stages.append(
        MigrationStage(
            "diff base/candidate",
            diff_status,
            f"{len(changes)} divergence(s), {len(diff_errors)} untested callable(s)",
        )
    )

    for change in changes:
        _classify_change(change, intended=intended, classifier=classify)
    unexpected = [change for change in changes if change.classification == "unexpected"]
    intended_count = len(changes) - len(unexpected)
    stages.append(
        MigrationStage(
            "classify intended changes",
            "passed",
            f"{intended_count} intended, {len(unexpected)} unexpected",
        )
    )

    artifacts = _save_artifacts(
        base=base,
        candidate=candidate,
        changes=changes,
        intended=intended,
        evidence_path=evidence,
        regression_path=regression,
    )
    save_status: StageStatus = "failed" if artifacts.error else "passed"
    stages.append(
        MigrationStage(
            "save unexpected divergences",
            save_status,
            (
                artifacts.error
                or f"{len(artifacts.regression_cases)} replayable case(s), "
                f"{len(artifacts.unsupported_change_ids)} evidence-only"
            ),
        )
    )

    baseline_errors: list[str] = []

    def resulting_tests() -> None:
        for case in artifacts.regression_cases:
            replay_migration_case(case)
        _run_explicit_invariants(candidate, explicit_invariants)

    if artifacts.error:
        baseline_errors.append(artifacts.error)
    if artifacts.unsupported_change_ids:
        baseline_errors.append(
            "non-replayable unexpected divergences: " + ", ".join(artifacts.unsupported_change_ids)
        )
    if not artifacts.regression_cases and explicit_invariant_count == 0:
        baseline_errors.append("no resulting regression tests or explicit invariants")
    if not baseline_errors:
        try:
            resulting_tests()
        except Exception as exc:
            baseline_errors.append(f"resulting test baseline fails: {type(exc).__name__}: {exc}")

    if baseline_errors:
        mutation_gate = MutationGate(
            status="blocked",
            threshold=mutation_threshold,
            reason="; ".join(baseline_errors),
        )
    else:
        mutation_result = _mutate(
            candidate,
            test_fn=resulting_tests,
            preset=mutation_preset,
            workers=mutation_workers,
            contract_context={
                "source": "migration",
                "explicit_invariants": {
                    name: [check.name for check in checks]
                    for name, checks in explicit_invariants.items()
                },
                "saved_regressions": len(artifacts.regression_cases),
            },
        )
        mutation_passed = mutation_result.total > 0 and mutation_result.score >= mutation_threshold
        mutation_gate = MutationGate(
            status="passed" if mutation_passed else "failed",
            threshold=mutation_threshold,
            result=mutation_result,
            reason=(
                None
                if mutation_passed
                else (
                    "no mutants were measured"
                    if mutation_result.total == 0
                    else f"mutation score {mutation_result.score:.0%} below "
                    f"{mutation_threshold:.0%}"
                )
            ),
        )
    stages.append(
        MigrationStage(
            "mutate resulting tests",
            mutation_gate.status,
            (
                mutation_gate.reason
                or f"{mutation_gate.result.killed}/{mutation_gate.result.total} mutants killed"
            ),
        )
    )

    effective_scan_options = dict(scan_options or {})
    if "contract_checks" in effective_scan_options:
        raise ValueError("pass explicit contract_checks through invariants, not scan_options")
    effective_scan_options.setdefault("max_examples", scan_max_examples)
    candidate_scan = _scan_module(
        candidate,
        contract_checks=explicit_invariants,
        **effective_scan_options,
    )
    stages.append(
        MigrationStage(
            "scan candidate",
            "passed" if candidate_scan.passed else "failed",
            f"{candidate_scan.total} callable(s), {candidate_scan.failed} promoted finding(s)",
        )
    )

    return MigrationResult(
        base=base,
        candidate=candidate,
        stages=stages,
        base_audit=base_audit,
        candidate_mining=candidate_mining,
        candidate_contracts=candidate_contracts,
        changes=changes,
        artifacts=artifacts,
        mutation=mutation_gate,
        candidate_scan=candidate_scan,
        diff_errors=diff_errors,
        explicit_invariant_count=explicit_invariant_count,
    )
