# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from collections.abc import Callable, Collection, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal
from ordeal.audit import ModuleAudit
from ordeal.auto import ContractCheck, ScanResult
from ordeal.diff import DiffWitness, Mismatch
from ordeal.mine import MineModuleResult
from ordeal.mutations import MutationResult

"\nThis type stub file was generated by pyright.\n"
StageStatus = Literal["passed", "failed", "blocked"]
ChangeKind = Literal["behavior", "signature", "added", "removed"]
ChangeClassification = Literal["intended", "unexpected"]
ChangeClassifier = Callable[
    ["MigrationChange"], ChangeClassification | tuple[ChangeClassification, str]
]
_SCHEMA_VERSION = ...
_GENERATED_HEADER = ...

@dataclass(frozen=True)
class MigrationStage:
    """One ordered stage and its evidence status."""

    name: str
    status: StageStatus
    summary: str
    ...

@dataclass(frozen=True)
class CandidateContract:
    """A property observed while mining the candidate implementation."""

    function: str
    property: str
    holds: int
    total: int
    confidence: float
    source: str = ...

@dataclass
class MigrationChange:
    """One behavioral or public-surface change between base and candidate."""

    id: str
    function: str
    kind: ChangeKind
    mismatch: Mismatch | None = ...
    witness: DiffWitness | None = ...
    base_signature: str | None = ...
    candidate_signature: str | None = ...
    regression_options: dict[str, object] = ...
    classification: ChangeClassification = ...
    reason: str = ...

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe evidence record for this change."""
        ...

@dataclass(frozen=True)
class RegressionArtifacts:
    """Paths and persistence evidence for unexpected divergences."""

    evidence_path: Path
    regression_path: Path
    regression_cases: tuple[dict[str, object], ...] = ...
    unsupported_change_ids: tuple[str, ...] = ...
    error: str | None = ...
    manifest_path: Path | None = ...
    finding_id: str | None = ...

@dataclass(frozen=True)
class MutationGate:
    """Mutation result or the exact reason mutation evidence is unavailable."""

    status: StageStatus
    threshold: float
    result: MutationResult | None = ...
    reason: str | None = ...

@dataclass
class MigrationResult:
    """Structured evidence from a complete base-to-candidate workflow."""

    base: str
    candidate: str
    stages: list[MigrationStage]
    base_audit: ModuleAudit
    candidate_mining: MineModuleResult
    candidate_contracts: list[CandidateContract]
    changes: list[MigrationChange]
    artifacts: RegressionArtifacts
    mutation: MutationGate
    candidate_scan: ScanResult
    diff_errors: dict[str, str] = ...
    explicit_invariant_count: int = ...
    explicit_invariant_functions: tuple[str, ...] = ...
    mining_limitations: list[str] = ...

    @builtins.property
    def unexpected_changes(self) -> list[MigrationChange]:
        """Return divergences not explicitly classified as intended."""
        ...

    @builtins.property
    def intended_changes(self) -> list[MigrationChange]:
        """Return divergences explicitly classified as intended."""
        ...

    @builtins.property
    def measured_regression_callables(self) -> tuple[str, ...]:
        """Return callables whose measured mutants were all killed by resulting tests."""
        ...

    @builtins.property
    def unprotected_changed_callables(self) -> tuple[str, ...]:
        """Return intended behavior changes lacking callable-scoped protection."""
        ...

    @builtins.property
    def protected_within_measured_scope(self) -> bool:
        """Whether every required evidence gate passed within configured scope."""
        ...

    @builtins.property
    def ready(self) -> bool:
        """Alias for :attr:`protected_within_measured_scope`."""
        ...

    def summary(self) -> str:
        """Render the workflow in stage order without overstating evidence."""
        ...

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe result for CLI and agent consumers."""
        ...

def replay_migration_case(case: Mapping[str, object]) -> None:
    """Replay one saved unexpected divergence against its candidate module."""
    ...

def migrate(
    base: str,
    candidate: str,
    *,
    intended_changes: Collection[str] | Mapping[str, str] = ...,
    classify: ChangeClassifier | None = ...,
    invariants: Mapping[str, Sequence[ContractCheck]] | None = ...,
    test_dir: str = ...,
    audit_max_examples: int = ...,
    mine_max_examples: int = ...,
    diff_max_examples: int = ...,
    scan_max_examples: int = ...,
    mutation_preset: Literal["essential", "standard", "thorough"] = ...,
    mutation_workers: int = ...,
    mutation_threshold: float = ...,
    mine_fixtures: Mapping[str, Any] | None = ...,
    diff_options: Mapping[str, Mapping[str, Any]] | None = ...,
    scan_options: Mapping[str, Any] | None = ...,
    evidence_path: str | Path | None = ...,
    regression_path: str | Path | None = ...,
    manifest_path: str | Path | None = ...,
) -> MigrationResult:
    """Run the ordered evidence workflow from *base* to *candidate*.

    Unexpected divergences are saved as executable parity regressions when
    their witnesses are replayable literals. A run with a still-unexpected
    divergence deliberately blocks mutation because a mutation score is not
    meaningful while the resulting regression baseline fails. Re-run after
    fixing the candidate, or classify the change as intended.

    ``invariants`` are explicit candidate contracts keyed by public callable
    name. Each intended behavior change needs an invariant for that callable
    or fully killed mutants attributed to it. Invariant inputs are cloned for
    every mutation invocation. The final candidate scan must exercise at least
    one callable. Mined properties are returned as hypotheses only.

    Args:
        base: Importable base module path.
        candidate: Importable candidate module path.
        intended_changes: Function names or stable ``kind:function`` selectors,
            optionally mapped to human-readable reasons.
        classify: Optional callback for programmatic change classification.
        invariants: Explicit semantic checks keyed by candidate callable name.
        test_dir: Existing test directory used by the base audit.
        audit_max_examples: Example budget for the base audit.
        mine_max_examples: Example budget for candidate contract mining.
        diff_max_examples: Example budget for each shared callable diff.
        scan_max_examples: Example budget for the candidate-only scan.
        mutation_preset: Mutation operator preset for resulting tests.
        mutation_workers: Mutation worker count.
        mutation_threshold: Minimum measured mutation score, default 100%.
        mine_fixtures: Global fixture overrides for candidate mining.
        diff_options: Per-function options forwarded to :func:`ordeal.diff.diff`.
        scan_options: Additional options forwarded to candidate ``scan_module``.
        evidence_path: JSON artifact path; defaults under ``.ordeal/migrations``.
        regression_path: Generated pytest path; defaults under ``tests``.

    Returns:
        A :class:`MigrationResult` with evidence for all seven ordered stages.
    """
    ...
