"""Evidence-first migration workflow from a base module to a candidate.

The workflow composes ordeal's existing capabilities in one ordered run:

``audit base -> mine candidate -> diff -> classify -> save -> mutate -> scan``

Mined properties remain candidate contracts. They are never promoted to
correctness claims. Explicit :class:`ordeal.auto.ContractCheck` instances are
the domain assertions used by mutation testing and the candidate-only scan.
"""

from __future__ import annotations

import copy
import hashlib
import importlib
import inspect
import json
import re
from collections.abc import Callable, Collection, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from ordeal._observation import observe
from ordeal.audit import ModuleAudit
from ordeal.audit import audit as _audit
from ordeal.auto import (
    ContractCheck,
    ScanResult,
    _call_contract_predicate,
    _call_sync,
    _get_public_functions,
)
from ordeal.auto import (
    scan_module as _scan_module,
)
from ordeal.diff import (
    DiffResult,
    DiffWitness,
    Mismatch,
    _approx_equal,
    _bind_named_arguments,
)
from ordeal.diff import diff as _diff
from ordeal.finding_evidence import _json_ready
from ordeal.mine import (
    STRUCTURAL_LIMITATIONS,
    MineModuleResult,
)
from ordeal.mine import (
    mine_module as _mine_module,
)
from ordeal.mutations import MutationResult
from ordeal.mutations import mutate as _mutate
from ordeal.regression_evidence import _decode_replay_value, _encode_replay_value

StageStatus = Literal["passed", "failed", "blocked"]
ChangeKind = Literal["behavior", "signature", "added", "removed"]
ChangeClassification = Literal["intended", "unexpected"]
ChangeClassifier = Callable[
    ["MigrationChange"],
    ChangeClassification | tuple[ChangeClassification, str],
]

_SCHEMA_VERSION = 1
_GENERATED_HEADER = '"""Generated by `ordeal migrate`.'


@dataclass(frozen=True)
class MigrationStage:
    """One ordered stage and its evidence status."""

    name: str
    status: StageStatus
    summary: str


@dataclass(frozen=True)
class CandidateContract:
    """A property observed while mining the candidate implementation."""

    function: str
    property: str
    holds: int
    total: int
    confidence: float
    source: str = "mined_hypothesis"


@dataclass
class MigrationChange:
    """One behavioral or public-surface change between base and candidate."""

    id: str
    function: str
    kind: ChangeKind
    mismatch: Mismatch | None = None
    witness: DiffWitness | None = None
    base_signature: str | None = None
    candidate_signature: str | None = None
    regression_options: dict[str, object] = field(default_factory=dict)
    classification: ChangeClassification = "unexpected"
    reason: str = "not declared as intended"

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe evidence record for this change."""
        record: dict[str, object] = {
            "id": self.id,
            "function": self.function,
            "kind": self.kind,
            "classification": self.classification,
            "reason": self.reason,
        }
        if self.mismatch is not None:
            record.update(
                {
                    "args": _display_value(self.mismatch.args),
                    "base_outcome": _display_value(self.mismatch.output_a),
                    "candidate_outcome": _display_value(self.mismatch.output_b),
                }
            )
        if self.witness is not None:
            record["witness"] = {
                "differences": list(self.witness.differences),
                "replay_attempts": self.witness.replay_attempts,
                "replay_matches": self.witness.replay_matches,
                "replay_verified": self.witness.replay_verified,
                "artifact_id": self.witness.artifact.get("artifact_id"),
                "artifact_path": self.witness.artifact_path,
            }
        if self.kind == "signature":
            record["base_signature"] = self.base_signature
            record["candidate_signature"] = self.candidate_signature
        if self.regression_options:
            record["regression_options"] = dict(self.regression_options)
        return record


@dataclass(frozen=True)
class RegressionArtifacts:
    """Paths and persistence evidence for unexpected divergences."""

    evidence_path: Path
    regression_path: Path
    regression_cases: tuple[dict[str, object], ...] = ()
    unsupported_change_ids: tuple[str, ...] = ()
    error: str | None = None
    manifest_path: Path | None = None
    finding_id: str | None = None


@dataclass(frozen=True)
class MutationGate:
    """Mutation result or the exact reason mutation evidence is unavailable."""

    status: StageStatus
    threshold: float
    result: MutationResult | None = None
    reason: str | None = None


@dataclass
class MigrationResult:
    """Structured evidence from a complete base-to-candidate workflow."""

    base: str
    candidate: str
    stages: list[MigrationStage]
    base_audit: ModuleAudit
    candidate_mining: MineModuleResult
    candidate_contracts: list[CandidateContract]
    changes: list[MigrationChange]
    artifacts: RegressionArtifacts
    mutation: MutationGate
    candidate_scan: ScanResult
    diff_errors: dict[str, str] = field(default_factory=dict)
    explicit_invariant_count: int = 0
    explicit_invariant_functions: tuple[str, ...] = ()
    mining_limitations: list[str] = field(default_factory=lambda: list(STRUCTURAL_LIMITATIONS))

    @property
    def unexpected_changes(self) -> list[MigrationChange]:
        """Return divergences not explicitly classified as intended."""
        return [change for change in self.changes if change.classification == "unexpected"]

    @property
    def intended_changes(self) -> list[MigrationChange]:
        """Return divergences explicitly classified as intended."""
        return [change for change in self.changes if change.classification == "intended"]

    @property
    def measured_regression_callables(self) -> tuple[str, ...]:
        """Return callables whose measured mutants were all killed by resulting tests."""
        mutation_result = self.mutation.result
        if mutation_result is None:
            return ()
        by_callable: dict[str, list[bool]] = {}
        for mutant in mutation_result.mutants:
            if mutant.qualname:
                by_callable.setdefault(mutant.qualname, []).append(mutant.killed)
        return tuple(
            sorted(
                function
                for function, outcomes in by_callable.items()
                if outcomes and all(outcomes)
            )
        )

    @property
    def unprotected_changed_callables(self) -> tuple[str, ...]:
        """Return intended behavior changes lacking callable-scoped protection."""
        intended_behavior = {
            change.function for change in self.intended_changes if change.kind == "behavior"
        }
        protected = set(self.explicit_invariant_functions) | set(
            self.measured_regression_callables
        )
        return tuple(sorted(intended_behavior - protected))

    @property
    def protected_within_measured_scope(self) -> bool:
        """Whether every required evidence gate passed within configured scope."""
        audit_blocked = bool(getattr(self.base_audit, "blocking_reason", None))
        mutation_result = self.mutation.result
        mutation_fully_killed = bool(
            mutation_result is not None
            and mutation_result.total > 0
            and mutation_result.killed == mutation_result.total
        )
        return (
            not audit_blocked
            and not self.unexpected_changes
            and not self.diff_errors
            and not self.artifacts.unsupported_change_ids
            and self.artifacts.error is None
            and self.explicit_invariant_count > 0
            and not self.unprotected_changed_callables
            and self.mutation.status == "passed"
            and mutation_fully_killed
            and self.candidate_scan.total > 0
            and self.candidate_scan.passed
        )

    @property
    def ready(self) -> bool:
        """Alias for :attr:`protected_within_measured_scope`."""
        return self.protected_within_measured_scope

    def summary(self) -> str:
        """Render the workflow in stage order without overstating evidence."""
        lines = [f"ordeal migrate {self.base} -> {self.candidate}"]
        for stage in self.stages:
            lines.append(f"  {stage.status.upper():7} {stage.name}: {stage.summary}")
        lines.append(
            "  RESULT  "
            + (
                "PROTECTIVE_WITHIN_MEASURED_SCOPE"
                if self.protected_within_measured_scope
                else "INCOMPLETE"
            )
        )
        lines.append(
            "  NOTE    mined properties are hypotheses; explicit invariants, mutation, "
            "and candidate scan carry correctness/protection evidence"
        )
        if self.unprotected_changed_callables:
            lines.append(
                "  NOTE    intended behavior lacks callable-scoped protection: "
                + ", ".join(self.unprotected_changed_callables)
            )
        return "\n".join(lines)

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe result for CLI and agent consumers."""
        mutation_result = self.mutation.result
        return {
            "schema_version": _SCHEMA_VERSION,
            "base": self.base,
            "candidate": self.candidate,
            "protected_within_measured_scope": self.protected_within_measured_scope,
            "stages": [
                {"name": stage.name, "status": stage.status, "summary": stage.summary}
                for stage in self.stages
            ],
            "candidate_contracts": [
                {
                    "function": contract.function,
                    "property": contract.property,
                    "holds": contract.holds,
                    "total": contract.total,
                    "confidence": contract.confidence,
                    "source": contract.source,
                }
                for contract in self.candidate_contracts
            ],
            "changes": [change.to_dict() for change in self.changes],
            "diff_errors": dict(self.diff_errors),
            "explicit_invariant_count": self.explicit_invariant_count,
            "explicit_invariant_functions": list(self.explicit_invariant_functions),
            "measured_regression_callables": list(self.measured_regression_callables),
            "unprotected_changed_callables": list(self.unprotected_changed_callables),
            "artifacts": {
                "evidence_path": self.artifacts.evidence_path.as_posix(),
                "regression_path": self.artifacts.regression_path.as_posix(),
                "regression_cases": len(self.artifacts.regression_cases),
                "unsupported_change_ids": list(self.artifacts.unsupported_change_ids),
                "error": self.artifacts.error,
                "manifest_path": (
                    self.artifacts.manifest_path.as_posix()
                    if self.artifacts.manifest_path is not None
                    else None
                ),
                "finding_id": self.artifacts.finding_id,
            },
            "mutation": {
                "status": self.mutation.status,
                "threshold": self.mutation.threshold,
                "reason": self.mutation.reason,
                "test_basis": (
                    mutation_result.contract_context.get("test_basis")
                    if mutation_result is not None
                    else None
                ),
                "killed": mutation_result.killed if mutation_result is not None else None,
                "total": mutation_result.total if mutation_result is not None else None,
                "score": mutation_result.score if mutation_result is not None else None,
            },
            "candidate_scan": {
                "passed": self.candidate_scan.total > 0 and self.candidate_scan.passed,
                "total": self.candidate_scan.total,
                "failed": self.candidate_scan.failed,
                "verdict_counts": self.candidate_scan.verdict_counts,
            },
            "mining_limitations": list(self.mining_limitations),
        }


def _slug(value: str) -> str:
    """Return a stable path-safe module slug."""
    return re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_") or "module"


def _default_evidence_path(base: str, candidate: str) -> Path:
    """Return the per-pair evidence path."""
    return Path(".ordeal/migrations") / f"{_slug(base)}_to_{_slug(candidate)}.json"


def _default_regression_path(candidate: str) -> Path:
    """Return the generated pytest path for a candidate module."""
    return Path("tests") / f"test_ordeal_migration_{_slug(candidate)}.py"


def _display_value(value: object) -> dict[str, object]:
    """Represent an arbitrary outcome without claiming it is replayable."""
    if isinstance(value, BaseException):
        return {
            "kind": "exception",
            "type": f"{type(value).__module__}.{type(value).__qualname__}",
            "message": str(value),
        }
    return {
        "kind": "return",
        "type": f"{type(value).__module__}.{type(value).__qualname__}",
        "repr": repr(value),
    }


def _encode_value(value: object) -> object:
    """Encode common witness values into JSON-safe, exactly replayable data."""
    return _encode_replay_value(value)


def _decode_value(value: object) -> object:
    """Decode data written by :func:`_encode_value`."""
    return _decode_replay_value(value)


def _canonical_state(value: object) -> object:
    """Canonicalize replay state the same way immutable diff witnesses do."""
    return observe(value, label="migration replay state").payload


def replay_migration_case(case: Mapping[str, object]) -> None:
    """Replay one saved unexpected divergence against its candidate module."""
    candidate = str(case["candidate"])
    function = str(case["function"])
    kind = str(case["kind"])
    module = importlib.import_module(candidate)

    if kind == "added":
        if hasattr(module, function):
            raise AssertionError(f"unexpected public callable still present: {function}")
        return
    if kind == "removed":
        if not hasattr(module, function):
            raise AssertionError(f"expected public callable is still missing: {function}")
        return
    if kind == "signature":
        func = getattr(module, function)
        expected_signature = str(case["expected_signature"])
        try:
            observed_signature = str(inspect.signature(func))
        except (TypeError, ValueError) as exc:
            raise AssertionError(
                f"candidate public signature is not inspectable: {function}"
            ) from exc
        if observed_signature != expected_signature:
            raise AssertionError(
                f"candidate public signature for {function} is {observed_signature}; "
                f"expected {expected_signature}"
            )
        return
    if kind != "behavior":
        raise ValueError(f"unknown migration regression kind: {kind!r}")

    func = getattr(module, function)
    kwargs_value = _decode_value(case["kwargs"])
    if not isinstance(kwargs_value, dict):
        raise TypeError("migration regression kwargs must decode to a dict")
    expected = case["expected"]
    if not isinstance(expected, Mapping):
        raise TypeError("migration regression expected outcome must be a mapping")

    observed_error: BaseException | None = None
    actual: object = None
    try:
        call_args, call_kwargs = _bind_named_arguments(func, kwargs_value)
        actual = _call_sync(func, *call_args, **call_kwargs)
    except BaseException as exc:
        observed_error = exc

    expected_kind = expected.get("kind")
    if expected_kind == "exception":
        expected_type = f"{expected['type_module']}.{expected['type_qualname']}"
        if observed_error is None:
            raise AssertionError(f"candidate did not raise {expected_type}: {expected['message']}")
        observed_type = f"{type(observed_error).__module__}.{type(observed_error).__qualname__}"
        if observed_type != expected_type or str(observed_error) != str(expected["message"]):
            raise AssertionError(
                "candidate raised a different exception: "
                f"{type(observed_error).__name__}: {observed_error}"
            ) from observed_error
    elif expected_kind == "canonical_return":
        if observed_error is not None:
            raise observed_error
        expected_observation = expected.get("observation")
        if not isinstance(expected_observation, Mapping):
            raise TypeError("canonical migration outcome must contain an observation graph")
        actual_observation = observe(
            actual,
            label="migration candidate return value",
        ).payload
        if actual_observation != expected_observation:
            raise AssertionError(
                "candidate returned a structurally different value from the preserved base outcome"
            )
    elif expected_kind == "return":
        if observed_error is not None:
            raise observed_error
        expected_value = _decode_value(expected["value"])
        comparison_options = case.get("comparison", {})
        if not isinstance(comparison_options, Mapping):
            raise TypeError("migration regression comparison must be a mapping")
        rtol_value = comparison_options.get("rtol")
        atol_value = comparison_options.get("atol")
        if rtol_value is not None or atol_value is not None:
            matches = _approx_equal(
                actual,
                expected_value,
                float(rtol_value or 1e-9),
                float(atol_value or 0.0),
            )
        else:
            comparison = actual == expected_value
            try:
                matches = bool(comparison)
            except (TypeError, ValueError):
                matches = False
        if not matches:
            raise AssertionError(
                f"candidate returned {actual!r}; expected preserved base outcome "
                f"{expected_value!r}"
            )
    else:
        raise ValueError(f"unknown migration expected outcome kind: {expected_kind!r}")

    if "expected_mutated_arguments_observation" in case:
        expected_arguments_observation = case["expected_mutated_arguments_observation"]
        if not isinstance(expected_arguments_observation, Mapping):
            raise TypeError("canonical migration argument state must contain an observation graph")
        actual_arguments_observation = observe(
            kwargs_value,
            label="migration candidate mutated arguments",
        ).payload
        if actual_arguments_observation != expected_arguments_observation:
            raise AssertionError(
                "candidate arguments have structurally different state from the preserved "
                "base outcome"
            )
    elif "expected_mutated_arguments" in case:
        expected_arguments = _decode_value(case["expected_mutated_arguments"])
        if _canonical_state(kwargs_value) != _canonical_state(expected_arguments):
            raise AssertionError(
                f"candidate mutated arguments to {kwargs_value!r}; expected preserved "
                f"base state {expected_arguments!r}"
            )


def _case_for_change(
    change: MigrationChange,
    *,
    candidate: str,
) -> dict[str, object]:
    """Build one executable regression case or raise when it cannot be replayed."""
    payload: dict[str, object] = {
        "change_id": change.id,
        "candidate": candidate,
        "function": change.function,
        "kind": change.kind,
    }
    if change.kind == "behavior":
        if change.mismatch is None or change.witness is None:
            raise TypeError("behavior change has no mismatch witness")
        unsupported = {"receiver_state", "side_effects"} & set(change.witness.differences)
        if unsupported:
            joined = ", ".join(sorted(unsupported))
            raise TypeError(f"cannot persist selected state channel(s): {joined}")
        if change.regression_options.get("custom_compare"):
            raise TypeError("cannot persist a custom diff comparator")
        if change.regression_options.get("custom_normalize"):
            raise TypeError("cannot persist a custom diff normalizer")
        artifact_observations = change.witness.artifact.get("observations", {})
        baseline_observation = (
            artifact_observations.get("a", {})
            if isinstance(artifact_observations, Mapping)
            else {}
        )
        if change.witness.replay_args_json is not None:
            replay_args = json.loads(change.witness.replay_args_json)
            if not isinstance(replay_args, Mapping):
                raise TypeError("behavior witness arguments are not a replayable mapping")
            payload["kwargs"] = replay_args
        elif change.witness.artifact.get("schema") == "ordeal.divergence-evidence/v1":
            raise TypeError("behavior witness arguments are not exactly replayable")
        else:
            payload["kwargs"] = _encode_value(change.mismatch.args)
        canonical_mutated_arguments = (
            baseline_observation.get("canonical_mutated_arguments")
            if isinstance(baseline_observation, Mapping)
            else None
        )
        if isinstance(canonical_mutated_arguments, Mapping):
            payload["expected_mutated_arguments_observation"] = _json_ready(
                canonical_mutated_arguments
            )
        else:
            payload["expected_mutated_arguments"] = _encode_value(
                change.witness.outcome_a.mutated_arguments
            )
        comparison = {
            key: change.regression_options[key]
            for key in ("rtol", "atol")
            if change.regression_options.get(key) is not None
        }
        if comparison:
            payload["comparison"] = comparison
        base_outcome = change.witness.outcome_a
        if not base_outcome.returned:
            if base_outcome.exception_type is None:
                raise TypeError("baseline exception witness has no exception type")
            payload["expected"] = {
                "kind": "exception",
                "type_module": base_outcome.exception_type.__module__,
                "type_qualname": base_outcome.exception_type.__qualname__,
                "message": str(base_outcome.exception_message or ""),
            }
        else:
            canonical_value = (
                baseline_observation.get("canonical_value")
                if isinstance(baseline_observation, Mapping)
                else None
            )
            if isinstance(canonical_value, Mapping) and not comparison:
                payload["expected"] = {
                    "kind": "canonical_return",
                    "observation": _json_ready(canonical_value),
                }
            else:
                payload["expected"] = {
                    "kind": "return",
                    "value": _encode_value(base_outcome.return_value),
                }
    elif change.kind == "signature":
        if change.base_signature is None:
            raise TypeError("signature change has no base signature")
        payload["expected_signature"] = change.base_signature
    digest = hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()[:12]
    payload["id"] = f"{change.id}:{digest}"
    return payload


def _load_existing_cases(
    path: Path,
    *,
    base: str,
    candidate: str,
) -> list[dict[str, object]]:
    """Load prior cases for the same module pair."""
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != _SCHEMA_VERSION:
        raise ValueError(f"unsupported migration evidence schema in {path}")
    if data.get("base") != base or data.get("candidate") != candidate:
        raise ValueError(f"migration evidence at {path} belongs to another module pair")
    cases = data.get("regression_cases", [])
    if not isinstance(cases, list):
        raise ValueError(f"invalid regression_cases in {path}")
    return [dict(case) for case in cases if isinstance(case, dict)]


def _render_regression_file(cases: Sequence[Mapping[str, object]]) -> str:
    """Render a standalone pytest module backed by replay helpers."""
    return "\n".join(
        [
            _GENERATED_HEADER,
            "",
            "Review and commit this file with its migration evidence artifact.",
            '"""',
            "",
            "import pytest",
            "",
            "from ordeal.migration import replay_migration_case",
            "",
            f"CASES = {list(cases)!r}",
            "",
            "",
            '@pytest.mark.parametrize("case", CASES, ids=[case["id"] for case in CASES])',
            "def test_ordeal_migration_regression(case: dict[str, object]) -> None:",
            '    """Keep one previously unexpected candidate divergence fixed."""',
            "    replay_migration_case(case)",
            "",
        ]
    )


def _selector_matches(selector: str, *, change_id: str, function: str) -> bool:
    """Return whether an intended-change selector names a change."""
    return selector in {change_id, function, f"*:{function}"}


def _classify_change(
    change: MigrationChange,
    *,
    intended: Mapping[str, str],
    classifier: ChangeClassifier | None,
) -> None:
    """Apply explicit classification without inferring intent from parity."""
    if classifier is not None:
        decision = classifier(change)
        if isinstance(decision, tuple):
            classification, reason = decision
        else:
            classification, reason = decision, "classified by callback"
        if classification not in ("intended", "unexpected"):
            raise ValueError(f"invalid change classification: {classification!r}")
        change.classification = classification
        change.reason = reason
        return
    for selector, reason in intended.items():
        if _selector_matches(selector, change_id=change.id, function=change.function):
            change.classification = "intended"
            change.reason = reason
            return


def _normalize_intended_changes(
    intended_changes: Collection[str] | Mapping[str, str],
) -> dict[str, str]:
    """Normalize simple selectors and selector-to-reason mappings."""
    if isinstance(intended_changes, Mapping):
        return {str(selector): str(reason) for selector, reason in intended_changes.items()}
    return {str(selector): "declared as intended" for selector in intended_changes}


def _candidate_contracts(result: MineModuleResult) -> list[CandidateContract]:
    """Flatten universal mined observations while labeling their weak status."""
    contracts: list[CandidateContract] = []
    for function, mine_result in sorted(result.per_function.items()):
        for prop in mine_result.universal:
            contracts.append(
                CandidateContract(
                    function=function,
                    property=prop.name,
                    holds=prop.holds,
                    total=prop.total,
                    confidence=prop.confidence,
                )
            )
    for prop in result.cross_function:
        if prop.total > 0 and prop.holds == prop.total:
            contracts.append(
                CandidateContract(
                    function=f"{prop.function_a}<->{prop.function_b}",
                    property=prop.relation,
                    holds=prop.holds,
                    total=prop.total,
                    confidence=prop.confidence,
                )
            )
    return contracts


def _run_explicit_invariants(
    candidate: str,
    invariants: Mapping[str, Sequence[ContractCheck]],
) -> None:
    """Execute explicit contracts against the live candidate module."""
    module = importlib.import_module(candidate)
    for function, checks in invariants.items():
        func: object = module
        for part in function.split("."):
            func = getattr(func, part)
        for check in checks:
            invocation_kwargs = copy.deepcopy(check.kwargs)
            error: BaseException | None = None
            try:
                call_args, call_kwargs = _bind_named_arguments(func, invocation_kwargs)
                value = _call_sync(func, *call_args, **call_kwargs)
            except BaseException as exc:
                error = exc
                value = None
            passed = _call_contract_predicate(
                check.predicate,
                value,
                func=func,
                call_context=getattr(func, "__ordeal_last_call_context__", None),
                kwargs=invocation_kwargs,
                error=error,
            )
            if not passed:
                detail = f" ({type(error).__name__}: {error})" if error is not None else ""
                raise AssertionError(f"explicit invariant failed: {function}:{check.name}{detail}")


def _save_artifacts(
    *,
    base: str,
    candidate: str,
    changes: Sequence[MigrationChange],
    intended: Mapping[str, str],
    evidence_path: Path,
    regression_path: Path,
) -> RegressionArtifacts:
    """Persist unexpected changes and merge replayable witnesses across reruns."""
    unsupported: list[str] = []
    try:
        existing = _load_existing_cases(
            evidence_path,
            base=base,
            candidate=candidate,
        )
        intended_ids = {change.id for change in changes if change.classification == "intended"}
        existing = [
            case
            for case in existing
            if str(case.get("change_id")) not in intended_ids
            and not any(
                _selector_matches(
                    selector,
                    change_id=str(case.get("change_id", "")),
                    function=str(case.get("function", "")),
                )
                for selector in intended
            )
        ]
        current_cases: list[dict[str, object]] = []
        for change in changes:
            if change.classification != "unexpected":
                continue
            try:
                current_cases.append(_case_for_change(change, candidate=candidate))
            except (TypeError, ValueError):
                unsupported.append(change.id)

        by_id = {str(case["id"]): case for case in [*existing, *current_cases]}
        cases = list(by_id.values())
        evidence = {
            "schema_version": _SCHEMA_VERSION,
            "base": base,
            "candidate": candidate,
            "changes": [change.to_dict() for change in changes],
            "change_evidence": [
                _json_ready(change.witness.artifact)
                for change in changes
                if change.witness is not None
                and change.witness.artifact.get("schema") == "ordeal.divergence-evidence/v1"
            ],
            "regression_cases": cases,
            "unsupported_change_ids": unsupported,
            "mining_limitations": list(STRUCTURAL_LIMITATIONS),
            "regression_path": regression_path.as_posix(),
        }
        evidence_path.parent.mkdir(parents=True, exist_ok=True)
        evidence_path.write_text(
            json.dumps(evidence, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

        if cases or regression_path.exists():
            if regression_path.exists() and not regression_path.read_text(
                encoding="utf-8"
            ).startswith(_GENERATED_HEADER):
                raise ValueError(
                    f"refusing to overwrite non-generated regression file: {regression_path}"
                )
            regression_path.parent.mkdir(parents=True, exist_ok=True)
            regression_path.write_text(_render_regression_file(cases), encoding="utf-8")
        return RegressionArtifacts(
            evidence_path=evidence_path,
            regression_path=regression_path,
            regression_cases=tuple(cases),
            unsupported_change_ids=tuple(unsupported),
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return RegressionArtifacts(
            evidence_path=evidence_path,
            regression_path=regression_path,
            unsupported_change_ids=tuple(unsupported),
            error=str(exc),
        )


def _persist_final_result(result: MigrationResult) -> str | None:
    """Append mutation, scan, and the final verdict to the migration artifact."""
    path = result.artifacts.evidence_path
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise ValueError("migration evidence must contain a JSON object")
        final = result.to_dict()
        payload.update(
            {
                "protected_within_measured_scope": final["protected_within_measured_scope"],
                "stages": final["stages"],
                "candidate_contracts": final["candidate_contracts"],
                "diff_errors": final["diff_errors"],
                "explicit_invariant_count": final["explicit_invariant_count"],
                "explicit_invariant_functions": final["explicit_invariant_functions"],
                "measured_regression_callables": final["measured_regression_callables"],
                "unprotected_changed_callables": final["unprotected_changed_callables"],
                "mutation": final["mutation"],
                "candidate_scan": final["candidate_scan"],
                "final_verdict": (
                    "protective_within_measured_scope"
                    if result.protected_within_measured_scope
                    else "incomplete"
                ),
            }
        )
        path.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return str(exc)
    return None


def _register_migration_regression(
    *,
    base: str,
    candidate: str,
    artifacts: RegressionArtifacts,
    manifest_path: Path,
) -> tuple[Path | None, str | None, str | None]:
    """Register the generated parity regression in the shared CI manifest."""
    from ordeal.regression_evidence import _register_python_regression

    finding_id = (
        "fnd_migration_" + hashlib.sha256(f"{base}\0{candidate}".encode("utf-8")).hexdigest()[:16]
    )
    try:
        evidence_payload = json.loads(artifacts.evidence_path.read_text(encoding="utf-8"))
        change_evidence = evidence_payload.get("change_evidence", [])
        artifact_ids = [
            str(item.get("artifact_id"))
            for item in change_evidence
            if isinstance(item, Mapping) and item.get("artifact_id")
        ]
        registered, error = _register_python_regression(
            manifest_path=manifest_path,
            finding_id=finding_id,
            change_kind="migration",
            target=f"{base} -> {candidate}",
            test_path=artifacts.regression_path,
            test_name="test_ordeal_migration_regression",
            evidence_path=artifacts.evidence_path,
            change_artifact_ids=artifact_ids,
            test_basis="generated_parity_and_explicit_contracts",
            active=bool(artifacts.regression_cases),
        )
        if error is not None:
            return None, None, error
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return None, None, str(exc)
    return registered, finding_id if artifacts.regression_cases else None, None


def migrate(
    base: str,
    candidate: str,
    *,
    intended_changes: Collection[str] | Mapping[str, str] = (),
    classify: ChangeClassifier | None = None,
    invariants: Mapping[str, Sequence[ContractCheck]] | None = None,
    test_dir: str = "tests",
    audit_max_examples: int = 20,
    mine_max_examples: int = 200,
    diff_max_examples: int = 100,
    scan_max_examples: int = 50,
    mutation_preset: Literal["essential", "standard", "thorough"] = "standard",
    mutation_workers: int = 1,
    mutation_threshold: float = 1.0,
    mine_fixtures: Mapping[str, Any] | None = None,
    diff_options: Mapping[str, Mapping[str, Any]] | None = None,
    scan_options: Mapping[str, Any] | None = None,
    evidence_path: str | Path | None = None,
    regression_path: str | Path | None = None,
    manifest_path: str | Path | None = None,
) -> MigrationResult:
    """Run the ordered evidence workflow from *base* to *candidate*.

    Unexpected divergences are saved as executable parity regressions when
    their witnesses are replayable literals. A run with a still-unexpected
    divergence deliberately blocks mutation because a mutation score is not
    meaningful while the resulting regression baseline fails. Re-run after
    fixing the candidate, or classify the change as intended.

    ``invariants`` are explicit candidate contracts keyed by public callable
    name. Each intended behavior change needs an invariant for that callable
    or fully killed mutants attributed to it. Invariant inputs are cloned for
    every mutation invocation. The final candidate scan must exercise at least
    one callable. Mined properties are returned as hypotheses only.

    Args:
        base: Importable base module path.
        candidate: Importable candidate module path.
        intended_changes: Function names or stable ``kind:function`` selectors,
            optionally mapped to human-readable reasons.
        classify: Optional callback for programmatic change classification.
        invariants: Explicit semantic checks keyed by candidate callable name.
        test_dir: Existing test directory used by the base audit.
        audit_max_examples: Example budget for the base audit.
        mine_max_examples: Example budget for candidate contract mining.
        diff_max_examples: Example budget for each shared callable diff.
        scan_max_examples: Example budget for the candidate-only scan.
        mutation_preset: Mutation operator preset for resulting tests.
        mutation_workers: Mutation worker count.
        mutation_threshold: Minimum measured mutation score, default 100%.
        mine_fixtures: Global fixture overrides for candidate mining.
        diff_options: Per-function options forwarded to :func:`ordeal.diff.diff`.
        scan_options: Additional options forwarded to candidate ``scan_module``.
        evidence_path: JSON artifact path; defaults under ``.ordeal/migrations``.
        regression_path: Generated pytest path; defaults under ``tests``.

    Returns:
        A :class:`MigrationResult` with evidence for all seven ordered stages.
    """
    if not 0.0 <= mutation_threshold <= 1.0:
        raise ValueError("mutation_threshold must be between 0 and 1")
    explicit_invariants = {str(name): list(checks) for name, checks in (invariants or {}).items()}
    explicit_invariant_count = sum(len(checks) for checks in explicit_invariants.values())
    intended = _normalize_intended_changes(intended_changes)
    evidence = (
        Path(evidence_path)
        if evidence_path is not None
        else _default_evidence_path(base, candidate)
    )
    regression = (
        Path(regression_path)
        if regression_path is not None
        else _default_regression_path(candidate)
    )
    stages: list[MigrationStage] = []

    base_audit = _audit(
        base,
        test_dir=test_dir,
        max_examples=audit_max_examples,
        workers=mutation_workers,
        contract_checks=explicit_invariants,
    )
    audit_block = getattr(base_audit, "blocking_reason", None)
    stages.append(
        MigrationStage(
            "audit base",
            "blocked" if audit_block else "passed",
            str(audit_block or base_audit.test_protection_view()["summary"]),
        )
    )

    candidate_mining = _mine_module(
        candidate,
        max_examples=mine_max_examples,
        **dict(mine_fixtures or {}),
    )
    candidate_contracts = _candidate_contracts(candidate_mining)
    stages.append(
        MigrationStage(
            "mine candidate contracts",
            "passed",
            f"{len(candidate_contracts)} observed contract hypothesis/hypotheses",
        )
    )

    base_module = importlib.import_module(base)
    candidate_module = importlib.import_module(candidate)
    base_functions = dict(_get_public_functions(base_module, preserve_wrappers=True))
    candidate_functions = dict(_get_public_functions(candidate_module, preserve_wrappers=True))
    changes: list[MigrationChange] = []
    diff_errors: dict[str, str] = {}
    shared_functions = base_functions.keys() & candidate_functions.keys()
    if not shared_functions:
        diff_errors["<migration>"] = "no shared public callables were differentially evaluated"
    for function in sorted(shared_functions):
        try:
            base_signature = str(inspect.signature(base_functions[function]))
            candidate_signature = str(inspect.signature(candidate_functions[function]))
        except (TypeError, ValueError) as exc:
            diff_errors[function] = f"public signature comparison failed: {exc}"
            continue
        if base_signature != candidate_signature:
            changes.append(
                MigrationChange(
                    id=f"signature:{function}",
                    function=function,
                    kind="signature",
                    base_signature=base_signature,
                    candidate_signature=candidate_signature,
                )
            )
        options = dict((diff_options or {}).get(function, {}))
        options.pop("max_examples", None)
        try:
            result: DiffResult = _diff(
                base_functions[function],
                candidate_functions[function],
                max_examples=diff_max_examples,
                **options,
            )
        except (TypeError, ValueError) as exc:
            diff_errors[function] = str(exc)
            continue
        if result.total < 1:
            diff_errors[function] = "differential comparison executed zero examples"
            continue
        if result.divergent:
            if result.witness is None or len(result.mismatches) != 1:
                diff_errors[function] = "divergent diff did not provide one canonical witness"
                continue
            changes.append(
                MigrationChange(
                    id=f"behavior:{function}",
                    function=function,
                    kind="behavior",
                    mismatch=result.mismatches[-1],
                    witness=result.witness,
                    regression_options={
                        **({"rtol": options["rtol"]} if options.get("rtol") is not None else {}),
                        **({"atol": options["atol"]} if options.get("atol") is not None else {}),
                        **({"custom_compare": True} if options.get("compare") else {}),
                        **({"custom_normalize": True} if options.get("normalize") else {}),
                    },
                )
            )
        elif result.status == "inconclusive":
            diff_errors[function] = result.reason or "differential comparison was inconclusive"
    for function in sorted(candidate_functions.keys() - base_functions.keys()):
        changes.append(
            MigrationChange(
                id=f"added:{function}",
                function=function,
                kind="added",
            )
        )
    for function in sorted(base_functions.keys() - candidate_functions.keys()):
        changes.append(
            MigrationChange(
                id=f"removed:{function}",
                function=function,
                kind="removed",
            )
        )
    diff_status: StageStatus = "failed" if diff_errors else "passed"
    stages.append(
        MigrationStage(
            "diff base/candidate",
            diff_status,
            f"{len(changes)} divergence(s), {len(diff_errors)} untested callable(s)",
        )
    )

    for change in changes:
        _classify_change(change, intended=intended, classifier=classify)
    unexpected = [change for change in changes if change.classification == "unexpected"]
    intended_count = len(changes) - len(unexpected)
    stages.append(
        MigrationStage(
            "classify intended changes",
            "passed",
            f"{intended_count} intended, {len(unexpected)} unexpected",
        )
    )

    artifacts = _save_artifacts(
        base=base,
        candidate=candidate,
        changes=changes,
        intended=intended,
        evidence_path=evidence,
        regression_path=regression,
    )
    save_status: StageStatus = "failed" if artifacts.error else "passed"
    stages.append(
        MigrationStage(
            "save unexpected divergences",
            save_status,
            (
                artifacts.error
                or f"{len(artifacts.regression_cases)} replayable case(s), "
                f"{len(artifacts.unsupported_change_ids)} evidence-only"
            ),
        )
    )

    baseline_errors: list[str] = []

    def resulting_tests() -> None:
        for case in artifacts.regression_cases:
            replay_migration_case(case)
        _run_explicit_invariants(candidate, explicit_invariants)

    if artifacts.error:
        baseline_errors.append(artifacts.error)
    if artifacts.unsupported_change_ids:
        baseline_errors.append(
            "non-replayable unexpected divergences: " + ", ".join(artifacts.unsupported_change_ids)
        )
    if not artifacts.regression_cases and explicit_invariant_count == 0:
        baseline_errors.append("no resulting regression tests or explicit invariants")
    if not baseline_errors:
        try:
            resulting_tests()
        except Exception as exc:
            baseline_errors.append(f"resulting test baseline fails: {type(exc).__name__}: {exc}")

    if baseline_errors:
        mutation_gate = MutationGate(
            status="blocked",
            threshold=mutation_threshold,
            reason="; ".join(baseline_errors),
        )
    else:
        mutation_result = _mutate(
            candidate,
            test_fn=resulting_tests,
            preset=mutation_preset,
            workers=mutation_workers,
            contract_context={
                "source": "migration",
                "test_basis": "generated_parity_and_explicit_contracts",
                "explicit_invariants": {
                    name: [check.name for check in checks]
                    for name, checks in explicit_invariants.items()
                },
                "saved_regressions": len(artifacts.regression_cases),
            },
        )
        mutation_passed = mutation_result.total > 0 and mutation_result.score >= mutation_threshold
        mutation_gate = MutationGate(
            status="passed" if mutation_passed else "failed",
            threshold=mutation_threshold,
            result=mutation_result,
            reason=(
                None
                if mutation_passed
                else (
                    "no mutants were measured"
                    if mutation_result.total == 0
                    else f"mutation score {mutation_result.score:.0%} below "
                    f"{mutation_threshold:.0%}"
                )
            ),
        )
    stages.append(
        MigrationStage(
            "mutate resulting tests",
            mutation_gate.status,
            (
                mutation_gate.reason
                or f"{mutation_gate.result.killed}/{mutation_gate.result.total} mutants killed"
            ),
        )
    )

    effective_scan_options = dict(scan_options or {})
    if "contract_checks" in effective_scan_options:
        raise ValueError("pass explicit contract_checks through invariants, not scan_options")
    effective_scan_options.setdefault("max_examples", scan_max_examples)
    candidate_scan = _scan_module(
        candidate,
        contract_checks=explicit_invariants,
        **effective_scan_options,
    )
    candidate_scan_passed = candidate_scan.total > 0 and candidate_scan.passed
    candidate_scan_summary = (
        f"{candidate_scan.total} callable(s), {candidate_scan.failed} promoted finding(s)"
        if candidate_scan.total > 0
        else "no callables produced executable scan evidence"
    )
    stages.append(
        MigrationStage(
            "scan candidate",
            "passed" if candidate_scan_passed else "failed",
            candidate_scan_summary,
        )
    )

    result = MigrationResult(
        base=base,
        candidate=candidate,
        stages=stages,
        base_audit=base_audit,
        candidate_mining=candidate_mining,
        candidate_contracts=candidate_contracts,
        changes=changes,
        artifacts=artifacts,
        mutation=mutation_gate,
        candidate_scan=candidate_scan,
        diff_errors=diff_errors,
        explicit_invariant_count=explicit_invariant_count,
        explicit_invariant_functions=tuple(
            sorted(name for name, checks in explicit_invariants.items() if checks)
        ),
    )
    if result.artifacts.error is None and manifest_path is not None:
        registered_path, finding_id, registration_error = _register_migration_regression(
            base=base,
            candidate=candidate,
            artifacts=result.artifacts,
            manifest_path=Path(manifest_path),
        )
        result.artifacts = RegressionArtifacts(
            evidence_path=result.artifacts.evidence_path,
            regression_path=result.artifacts.regression_path,
            regression_cases=result.artifacts.regression_cases,
            unsupported_change_ids=result.artifacts.unsupported_change_ids,
            error=registration_error,
            manifest_path=registered_path,
            finding_id=finding_id,
        )
    if result.artifacts.error is None:
        finalization_error = _persist_final_result(result)
        if finalization_error is not None:
            result.artifacts = RegressionArtifacts(
                evidence_path=result.artifacts.evidence_path,
                regression_path=result.artifacts.regression_path,
                regression_cases=result.artifacts.regression_cases,
                unsupported_change_ids=result.artifacts.unsupported_change_ids,
                error=finalization_error,
                manifest_path=result.artifacts.manifest_path,
                finding_id=result.artifacts.finding_id,
            )
    return result
