# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import hypothesis.strategies as st
from collections.abc import Callable
from dataclasses import dataclass
from types import ModuleType
from typing import Any

"\nThis type stub file was generated by pyright.\n"
_REL_TOL = ...
_ABS_TOL = ...
_SUSPICIOUS_CONFIDENCE = ...
_MAX_SUSPICIOUS_PROPERTIES = ...
_NOT_CHECKED_PREVIEW = ...
_SUMMARY_OMIT_PREFIXES = ...
_SUSPICIOUS_PREFIXES = ...

@dataclass
class MinedProperty:
    """A likely property observed during mining."""

    name: str
    holds: int
    total: int
    counterexample: dict[str, Any] | None = ...
    replayable: bool | None = ...
    replay_attempts: int = ...
    replay_matches: int = ...
    replay_match_basis: str | None = ...
    minimization: dict[str, Any] | None = ...

    @builtins.property
    def confidence(self) -> float:
        """Fraction of examples where the property held."""
        ...

    @builtins.property
    def universal(self) -> bool:
        """True if the property held for every example."""
        ...

    def __str__(self) -> str: ...

_DURABLE_PROPERTY_NAMES = ...

@dataclass
class CrossFunctionProperty:
    """A relationship discovered between two functions.

    Cross-function properties capture structural relationships that no
    single-function analysis can find.  These are the most valuable
    properties for regression testing because they encode *contracts*
    between components:

    - **roundtrip**: ``g(f(x)) == x`` — encoding/decoding, serialize/deserialize,
      compress/decompress.  If this breaks, data is being lost or corrupted.
    - **commutative_composition**: ``f(g(x)) == g(f(x))`` — the two functions
      can be applied in either order.  Rare but powerful when it holds.
    - **equivalent**: ``f(x) == g(x)`` — both produce identical output for
      all tested inputs.  Often signals duplicate implementations, or a
      fast-path that should match a reference implementation.

    Attributes:
        function_a: Qualified name of the first function.
        function_b: Qualified name of the second function.
        relation: Kind of relationship: ``"roundtrip"``,
            ``"commutative_composition"``, or ``"equivalent"``.
        confidence: Fraction of tested inputs where the relation held
            (0.0 to 1.0).
        holds: Number of inputs where the relation held.
        total: Number of inputs tested.
        counterexample: If the relation failed, one example showing the
            disagreement.  ``None`` when the relation held universally.
    """

    function_a: str
    function_b: str
    relation: str
    confidence: float
    holds: int
    total: int
    counterexample: dict[str, Any] | None = ...

    def __str__(self) -> str: ...

STRUCTURAL_LIMITATIONS: list[str] = ...

@dataclass
class MineResult:
    """All properties discovered for a function.

    Separates what was checked into three categories:

    - ``properties``: checked and applicable (total > 0)
    - ``not_applicable``: checked but not relevant to this function
      (e.g., "bounded [0,1]" for a function returning strings)
    - ``not_checked``: structural limitations — things mine()
      fundamentally cannot verify (always the same list)
    """

    function: str
    examples: int
    properties: list[MinedProperty] = ...
    not_applicable: list[str] = ...
    not_checked: list[str] = ...
    collected_inputs: list[dict[str, object]] = ...
    collected_outputs: list[object] = ...
    edges_discovered: int = ...
    saturated: bool = ...
    branch_points: dict[str, list[object]] = ...
    branches_cracked: int = ...

    @builtins.property
    def universal(self) -> list[MinedProperty]:
        """Properties that held on every single example."""
        ...

    @builtins.property
    def likely(self) -> list[MinedProperty]:
        """Properties with >= 95% confidence but not universal."""
        ...

    def summary(self) -> str:
        """Human-readable report."""
        ...

@dataclass
class MineModuleResult:
    """Results of mining an entire module for both per-function and cross-function properties.

    Combines individual ``MineResult`` per function with ``CrossFunctionProperty``
    relationships discovered between function pairs.  The ``summary()`` method
    produces a single report covering both, so developers and AI assistants can
    see the full picture at a glance.

    Attributes:
        module: Dotted module path (e.g. ``"myapp.scoring"``).
        per_function: Individual mining results keyed by function name.
        cross_function: Relationships discovered between function pairs.
    """

    module: str
    per_function: dict[str, MineResult] = ...
    cross_function: list[CrossFunctionProperty] = ...

    def summary(self) -> str:
        """Human-readable report covering per-function and cross-function properties.

        Per-function properties are listed first (one section per function),
        followed by cross-function relationships grouped by confidence.
        """
        ...

_GENERIC_OPERAND_NAMES = ...

def mine(
    fn: Callable[..., Any],
    *,
    max_examples: int = ...,
    ignore_properties: list[str] | tuple[str, ...] = ...,
    minimize_findings: bool = ...,
    **fixtures: st.SearchStrategy[Any] | Any,
) -> MineResult:
    """Discover likely properties of a function by running it many times.

    Simple::

        result = mine(my_function)
        for p in result.universal:
            print(p)  # properties that always held

    With fixtures::

        result = mine(my_function, model=mock_model)

    Args:
        fn: The function to mine properties from.
        max_examples: Number of random inputs to try.
        ignore_properties: Property names to suppress from the result.
        minimize_findings: Shrink and replay suspicious witnesses for durable handoff.
        **fixtures: Strategy overrides or plain values.
    """
    ...

def mine_pair(
    f: Callable[..., Any],
    g: Callable[..., Any],
    *,
    max_examples: int = ...,
    **fixtures: st.SearchStrategy[Any] | Any,
) -> MineResult:
    """Discover relational properties between two functions.

    Checks roundtrip (``g(f(x)) == x``), the reverse (``f(g(x)) == x``),
    and commutative composition (``f(g(x)) == g(f(x))``).  Strategies
    are inferred from *f*'s signature.

    Example::

        result = mine_pair(json.dumps, json.loads)
        # discovers: roundtrip g(f(x)) == x

        result = mine_pair(encode, decode)
        # discovers: roundtrip g(f(x)) == x, roundtrip f(g(x)) == x
    """
    ...

def mine_module(
    module: str | ModuleType,
    *,
    max_examples: int = ...,
    cross_max_examples: int = ...,
    mine_per_function: bool = ...,
    ignore_properties: list[str] | tuple[str, ...] = ...,
    ignore_relations: list[str] | tuple[str, ...] = ...,
    property_overrides: dict[str, list[str]] | None = ...,
    relation_overrides: dict[str, list[str]] | None = ...,
    **fixtures: st.SearchStrategy[Any] | Any,
) -> MineModuleResult:
    """Discover properties across an entire module — both per-function and cross-function.

    Single-function mining (via ``mine()``) finds properties like "output >= 0"
    or "deterministic".  Cross-function mining finds relationships that only
    exist *between* functions — the kind of properties that break during
    refactoring because no single unit test covers the contract.

    Three cross-function relationships are checked for every compatible pair:

    - **roundtrip**: ``g(f(x)) == x``.  Discovered when f's return type matches
      g's parameter type.  Classic examples: ``decode(encode(x))``,
      ``deserialize(serialize(x))``, ``decompress(compress(x))``.

    - **commutative_composition**: ``f(g(x)) == g(f(x))``.  Discovered when
      both functions accept and return the same type.  Examples: two
      normalization passes that can be applied in either order, or
      ``sort(reverse(xs)) == reverse(sort(xs))`` (which would *not* hold
      and produce a counterexample).

    - **equivalent**: ``f(x) == g(x)``.  Discovered when both functions
      accept the same input types.  Flags duplicate implementations,
      reference/optimized pairs, or accidental copies that should be
      consolidated.

    Because the number of pairs grows as O(n^2), ``cross_max_examples`` is
    kept low (default 30) to avoid combinatorial blowup.  For a module with
    10 functions there are 45 directed pairs; at 30 examples each that is
    1350 calls per relationship check — fast enough for CI.

    Args:
        module: Dotted module path (``"myapp.scoring"``) or an already-imported
            module object.
        max_examples: Examples per function for individual ``mine()`` calls.
        cross_max_examples: Examples per function pair for cross-function checks.
            Kept low because there are O(n^2) pairs.
        mine_per_function: If ``True`` (default), also run ``mine()`` on each
            function individually.  Set to ``False`` to only discover
            cross-function relationships.
        ignore_properties: Property names to suppress for every function.
        ignore_relations: Cross-function relation names to suppress.
        property_overrides: Per-function property suppressions.
        relation_overrides: Per-function relation suppressions.
        **fixtures: Strategy overrides or plain values passed through to
            ``mine()`` and ``_infer_strategies()``.

    Returns:
        A ``MineModuleResult`` containing per-function ``MineResult`` objects
        and a list of ``CrossFunctionProperty`` relationships.

    Example::

        result = mine_module("myapp.codecs")
        print(result.summary())
        # mine_module(myapp.codecs)
        #   4 functions, 2 cross-function relationships
        #
        #   mine(encode): 200 examples
        #     ALWAYS  output type is bytes (200/200)
        #     ...
        #
        #   Cross-function relationships:
        #     ALWAYS  encode <-> decode: roundtrip (30/30)
        #      97%    fast_encode <-> encode: equivalent (29/30)
    """
    ...
