# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import random as _random
from typing import Any

"\nThis type stub file was generated by pyright.\n"

def mutate_value(value: Any, rng: _random.Random, intensity: float = ...) -> Any:
    """Mutate a single Python value — the core AFL bit-flip adapted for Python types.

    Used by ``mine()`` Phase 2 (coverage-guided input mutation) and
    ``Explorer`` (seed mutation from productive checkpoints).

    The mutation is type-aware: integers get bit-flips and arithmetic
    perturbations, strings get character swaps and truncation, floats
    get mantissa perturbation and special values, etc.

    Args:
        value: The value to mutate.
        rng: Random number generator (seeded for determinism).
        intensity: Probability of each mutation firing (0.0-1.0).
            Lower = subtle perturbation, higher = aggressive mutation.

    Returns:
        A mutated copy of the value.  May return the original unchanged
        if no mutation was selected (by design — some inputs should be
        retested as-is to confirm determinism).
    """
    ...

def extract_strategy_constraint(strategy: Any) -> dict[str, Any] | None:
    """Return a lightweight mutation constraint for a Hypothesis strategy.

    The returned constraint is intentionally small and only covers the
    common strategies that Explorer seed mutation needs to keep values
    "nearby but still valid": integers, floats, text, lists, booleans,
    and sampled/just strategies.
    """
    ...

def mutate_inputs(
    inputs: dict[str, Any],
    rng: _random.Random,
    intensity: float = ...,
    *,
    strategies: dict[str, Any] | None = ...,
    respect_strategies: bool | None = ...,
    constraints: dict[str, dict[str, Any]] | None = ...,
    stay_within_bounds: bool = ...,
) -> dict[str, Any]:
    """Mutate a full kwargs dict — used by mine() and Explorer's seed mutation loop.

    Takes a known-good input that reached interesting coverage and
    perturbs it.  The coverage feedback loop then checks if the
    mutation reaches new edges::

        for good_input in productive_inputs:
            mutated = mutate_inputs(good_input, rng)
            edges_before = collector.snapshot()
            fn(**mutated)
            edges_after = collector.snapshot()
            if edges_after - edges_before:
                # This mutation found new coverage — keep it as a seed
                productive_inputs.append(mutated)

    Args:
        inputs: Function kwargs to mutate (e.g. ``{"x": 42, "mode": "admin"}``).
        rng: Seeded RNG for deterministic mutation.
        intensity: Mutation aggressiveness (0.0-1.0).
        strategies: Optional Hypothesis strategies keyed by parameter name.
            When provided, common bounds are extracted automatically.
        respect_strategies: Backward-compatible alias for
            ``stay_within_bounds`` when callers are thinking in terms of
            declared strategies rather than explicit constraints.
        constraints: Optional per-parameter strategy constraints extracted
            from Hypothesis strategies.
        stay_within_bounds: If ``True``, project each mutated value back into
            its declared strategy bounds.  Useful for config/control-plane
            systems where "nearby but still valid" beats boundary-breaking
            mutations.

    Returns:
        A new dict with mutated values.  Keys are preserved.
    """
    ...
