# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import ast
import types
from dataclasses import dataclass
from typing import Any, Callable, Literal, Mapping, Sequence, TYPE_CHECKING
from ordeal.faults import PatchFault
from ordeal.mine import MineResult

"\nThis type stub file was generated by pyright.\n"
if TYPE_CHECKING: ...
ValidationMode = Literal["fast", "deep"]

@dataclass(frozen=True)
class _ResolvedMutationTarget:
    """Resolved callable target used by mutation execution paths."""

    target: str
    module: types.ModuleType
    owner: object
    attr_name: str | None
    qualname_parts: tuple[str, ...] = ...

    @builtins.property
    def module_name(self) -> str: ...
    @builtins.property
    def is_module(self) -> bool: ...
    @builtins.property
    def leaf_name(self) -> str | None: ...

class NoTestsFoundError(RuntimeError):
    """Raised when auto-discovery finds no tests for a mutation target.

    Attributes:
        target: The dotted path that was being tested.
        suggested_file: Recommended filename to save starter tests to.
    """

    def __init__(self, message: str, *, target: str = ..., suggested_file: str = ...) -> None: ...

_REMEDIATION: dict[str, str] = ...

@dataclass
class Mutant:
    """A single code mutation."""

    operator: str
    description: str
    line: int
    col: int
    killed: bool = ...
    error: str | None = ...
    source_line: str = ...
    killed_by: str | None = ...
    qualname: str | None = ...
    metadata: dict[str, Any] = ...
    _mutant_source: str | None = ...

    @builtins.property
    def location(self) -> str:
        """Source location as ``L<line>:<col>``."""
        ...

    @builtins.property
    def site_summary(self) -> str:
        """Return the exact source site for this mutant."""
        ...

    @builtins.property
    def report_label(self) -> str:
        """Return a compact, review-friendly label for this mutant."""
        ...

    @builtins.property
    def remediation(self) -> str:
        """Actionable guidance for killing this mutant."""
        ...

_CONTRACT_TAG_ALIASES: dict[str, str] = ...
_COHERENT_BOUNDARY_TAGS = ...

def mutation_contract_context(
    contract_checks: Sequence[Any] | None, *, harness: str | None = ...
) -> dict[str, Any]:
    """Summarize configured contract checks into mutation-ranking metadata."""
    ...

_TYPE_VALUES: dict[str, list[object]] = ...
_TYPE_EXAMPLES: dict[str, str] = ...

@dataclass
class MutationResult:
    """Aggregated mutation testing results.

    Key attributes and methods::

        result.score              # 0.625 (kill ratio, 1.0 = all caught)
        result.survived           # list of Mutant objects — test gaps
        result.summary()          # formatted report with gaps + fix guidance
        result.generate_test_stubs()  # Python test file with real signatures

    Per-gap data (each item in ``result.survived``)::

        m.operator      # "arithmetic"
        m.description   # "+ -> -"
        m.location      # "L12:4"
        m.source_line   # "return a + b"
        m.remediation   # what test to write to close this gap

    Metadata::

        result.target           # "myapp.scoring.compute"
        result.operators_used   # ["arithmetic", ...] or None
        result.preset_used      # "standard" or None
    """

    target: str
    mutants: list[Mutant] = ...
    operators_used: list[str] | None = ...
    preset_used: str | None = ...
    concern: str | None = ...
    contract_context: dict[str, Any] = ...
    property_observations: list[dict[str, int | str]] = ...
    validation_sample_matrix_sha256: str | None = ...
    timings: dict[str, float] = ...
    promote_clusters_only: bool = ...
    cluster_min_size: int = ...
    diagnostics: dict[str, int] = ...

    @builtins.property
    def total(self) -> int:
        """Total number of mutants generated."""
        ...

    @builtins.property
    def killed(self) -> int:
        """Number of mutants detected (killed) by the tests."""
        ...

    @builtins.property
    def survived(self) -> list[Mutant]:
        """Mutants that the tests failed to detect — potential test gaps."""
        ...

    def kill_attribution(self) -> dict[str, list[Mutant]]:
        """Group killed mutants by the test/property that killed them.

        Returns a dict mapping test names to the mutants they caught.
        Shows which tests carry their weight and which are redundant::

            attr = result.kill_attribution()
            for test, mutants in attr.items():
                print(f"{test}: killed {len(mutants)} mutant(s)")
        """
        ...

    @builtins.property
    def score(self) -> float:
        """Kill ratio: 1.0 means every mutant was caught."""
        ...

    @builtins.property
    def score_text(self) -> str:
        """Exact mutation score rendered as ``killed/total (pct%)``."""
        ...

    def semantic_survivor_clusters(self) -> list[dict[str, Any]]:
        """Group surviving mutants by coarse semantic boundary or sink."""
        ...

    def promoted_survivor_clusters(self) -> list[dict[str, Any]]:
        """Return survivor clusters strong enough to surface as main gaps."""
        ...

    def weakest_killers(self, *, limit: int | None = ...) -> list[dict[str, Any]]:
        """Return compact weakest-killer metadata ordered by strength."""
        ...

    def property_strength(self) -> list[dict[str, Any]]:
        """Measure whether exercised mined properties discriminate real mutations.

        A property is ``discriminating`` only when it kills at least one tested
        mutant. An exercised property that kills none is reported as
        ``tautological_or_weak``: mutation testing proves that it added no signal
        for this mutant set, but does not claim a formal logical tautology.
        """
        ...

    def test_protection_view(self) -> dict[str, Any]:
        """Answer whether the tests protect the target within measured scope.

        Returns a JSON-compatible dict containing the scoped verdict, exact
        mutation score, survivors, kill attribution, property-strength rows,
        and convenience lists for weak or unexercised properties.

        ``weak`` means a mutant survived or a declared property was not
        exercised. ``inconclusive`` means no non-equivalent mutant was tested.
        ``protective_within_measured_scope`` means every tested mutant was
        killed; it is not a universal correctness guarantee.
        """
        ...

    def epistemic_view(self) -> dict[str, Any]:
        """Return a tight mutation-evidence payload for reports and audit aggregation."""
        ...

    def filter_report(self) -> str:
        """Structured breakdown of the mutation pipeline for AI assistants.

        Shows how many mutants were generated and where they were filtered,
        so the consumer can understand *why* the result looks the way it does.

        Returns an empty string when diagnostics are not populated.
        """
        ...

    def summary(self, remediation: bool = ...) -> str:
        """Report with test gaps and per-gap fix guidance.

        Each surviving mutant is a **test gap** — a real code change
        that the test suite fails to detect.  The output names each gap,
        shows the affected source line, and explains the specific fix
        (what kind of test would close the gap).

        Args:
            remediation: If True (default), include per-gap fix guidance
                explaining what test to write.
        """
        ...

    def generate_test_stubs(self) -> str:
        """Generate a Python test file for surviving mutants.

        Produces draft review stubs instead of runnable regressions.
        Each surviving mutant gets a test function with explicit review
        notes, a module-qualified call site, and either a pinned-behavior
        placeholder or a mined-invariant candidate.

        Returns an empty string when all mutants are killed.
        """
        ...

    def harden(self, extra_tests: list[str]) -> HardeningResult:
        """Verify that test code actually kills surviving mutants (Meta ACH pattern).

        Takes source strings of test functions written by an AI assistant
        or human, and runs the **three-assurance verification loop** for
        each:

        1. **Buildable** — the test source parses and compiles.
        2. **Valid regression** — the test passes on the original code.
        3. **Hardening** — the test fails (kills) at least one surviving mutant.

        Tests that pass all three assurances are *verified* — they provably
        close a mutation gap.  Tests that fail on the original are *invalid*.
        Tests that pass but don't kill any mutant are *ineffective*.

        Example — AI assistant writes tests, ordeal verifies::

            result = mutate("myapp.scoring.compute", preset="standard")

            hardened = result.harden([
                '''
            def test_boundary():
                from myapp.scoring import compute
                assert compute(0, 5) == 5
                ''',
                '''
            def test_negative():
                from myapp.scoring import compute
                assert compute(-1, 5) == 0
                ''',
            ])

            print(f"Verified: {len(hardened.verified)}")
            print(f"Invalid: {len(hardened.invalid)}")
            print(f"Ineffective: {len(hardened.ineffective)}")

        Args:
            extra_tests: Source strings, each containing one or more
                ``def test_*()`` functions.  The tests should import
                the target function themselves.

        Returns:
            A :class:`HardeningResult` with verified, invalid, and
            ineffective tests.
        """
        ...

@dataclass
class VerifiedTest:
    """A test that provably kills one or more surviving mutants.

    Attributes:
        name: The test function name (e.g. ``"test_boundary"``).
        source: The full test source code.
        kills: Mutants this test kills — the hardening guarantee.
    """

    name: str
    source: str
    kills: list[Mutant] = ...

@dataclass
class HardeningResult:
    """Result of the hardening verification loop (Meta ACH 3-assurance pattern).

    Three categories:

    - **verified** — tests that pass all 3 assurances: buildable, valid
      regression (passes on original), and hardening (kills at least one
      surviving mutant).  Each has a machine-verified kill guarantee.
    - **invalid** — tests that don't compile or fail on the original code.
    - **ineffective** — tests that pass on the original but don't kill
      any surviving mutant (they test something, just not a gap).
    """

    verified: list[VerifiedTest] = ...
    invalid: list[str] = ...
    ineffective: list[str] = ...

    @builtins.property
    def total_kills(self) -> int:
        """Total number of unique mutants killed across all verified tests."""
        ...

    def summary(self) -> str:
        """Human-readable summary of hardening results."""
        ...

def generate_starter_tests(target: str, *, dry_run: bool = ...) -> str:
    """Generate a smoke-test file for a target that has no tests yet.

    Introspects the target (function or module) via ``inspect`` and
    produces one smoke test per public callable — real imports, real
    parameter names, typed example values.  No assertions beyond
    ``assert result is not None``; the goal is a runnable file that
    gives mutation testing something to work with.

    When *dry_run* is ``True``, generates tests from signatures and type
    hints only — **no modules are imported and no functions are executed**.
    Discovery uses filesystem scanning and AST parsing.  This prevents
    all side effects when previewing what ``ordeal init --dry-run`` would
    create.

    Args:
        target: Dotted path to a function (``"myapp.scoring.compute"``)
            or module (``"myapp.scoring"``).
        dry_run: If ``True``, no imports or execution — AST-only stubs.

    Returns an empty string if the target cannot be resolved.
    """
    ...

@dataclass
class _CallResult:
    """Result of trying to call a function with example args."""

    value: object = ...
    value_repr: str = ...
    kwargs: dict[str, object] = ...
    call_repr: str = ...
    error: str = ...
    error_type: str = ...

@dataclass
class _MineFindings:
    """Everything mine() discovered about a function."""

    pinned: list[tuple[dict[str, object], object]]
    property_lines: list[str]
    prop_names: list[str]
    ...

_PROPERTY_ASSERTIONS: dict[str, str | None] = ...
_ALGEBRAIC_ASSERTIONS: dict[str, str] = ...
_SENTINEL = ...
_SKIP_DIRS = ...
_TEST_DIRS = ...

def init_project(
    target: str | None = ..., *, output_dir: str = ..., dry_run: bool = ...
) -> list[dict[str, str]]:
    """Bootstrap test files for a Python package.

    Scans *target* for public modules, checks which ones already have
    tests, and generates starter smoke tests for the rest.

    Args:
        target: Dotted package path (e.g. ``"myapp"``).  When ``None``,
            auto-detects from the current directory.
        output_dir: Directory to write test files to (default ``"tests"``).
        dry_run: If True, no files are written and no functions are executed.
            Generates stub tests from signatures and type hints only, so
            ``--dry-run`` is safe even on packages with side effects.

    Returns:
        List of dicts with keys ``module``, ``status``, ``path``, ``content``.
        Status is one of ``"generated"``, ``"exists"``, ``"empty"``.
    """
    ...

class _Applicator(ast.NodeTransformer):
    """Apply exactly the Nth possible mutation of a specific type."""

    def __init__(self, target_idx: int) -> None: ...

class _ArithmeticApplicator(_Applicator):
    SWAPS: dict[type, tuple[type, str, str]] = ...

    def visit_BinOp(self, node: ast.BinOp) -> ast.AST: ...

class _ComparisonApplicator(_Applicator):
    SWAPS: dict[type, tuple[type, str, str]] = ...

    def visit_Compare(self, node: ast.Compare) -> ast.AST: ...

class _NegateApplicator(_Applicator):
    def visit_If(self, node: ast.If) -> ast.AST: ...
    def visit_While(self, node: ast.While) -> ast.AST: ...

class _ReturnNoneApplicator(_Applicator):
    def visit_Return(self, node: ast.Return) -> ast.AST: ...

class _Counter(ast.NodeVisitor):
    def __init__(self) -> None: ...

class _ArithmeticCounter(_Counter):
    def visit_BinOp(self, node: ast.BinOp) -> None: ...

class _ComparisonCounter(_Counter):
    def visit_Compare(self, node: ast.Compare) -> None: ...

class _NegateCounter(_Counter):
    def visit_If(self, node: ast.If) -> None: ...
    def visit_While(self, node: ast.While) -> None: ...

class _ReturnNoneCounter(_Counter):
    def visit_Return(self, node: ast.Return) -> None: ...

class _BoundaryApplicator(_Applicator):
    """Mutate integer constants: ``n`` -> ``n + 1`` and ``n`` -> ``n - 1``.

    Both directions are needed: ``<= 10`` with n=10+1 catches upper
    bound errors, n=10-1 catches lower bound errors.
    """

    def visit_Constant(self, node: ast.Constant) -> ast.AST: ...

class _BoundaryCounter(_Counter):
    def visit_Constant(self, node: ast.Constant) -> None: ...

class _ConstantApplicator(_Applicator):
    """Replace numeric constants with 0, 1, or -1."""

    REPLACEMENTS = ...

    def visit_Constant(self, node: ast.Constant) -> ast.AST: ...

class _ConstantCounter(_Counter):
    def visit_Constant(self, node: ast.Constant) -> None: ...

class _DeleteStatementApplicator(_Applicator):
    """Replace a statement with ``pass``.

    Skips docstrings (``Expr(Constant(str))``) to avoid equivalent mutants.
    """

    def visit_Assign(self, node: ast.Assign) -> ast.AST: ...
    def visit_Expr(self, node: ast.Expr) -> ast.AST: ...
    def visit_AugAssign(self, node: ast.AugAssign) -> ast.AST: ...

class _DeleteStatementCounter(_Counter):
    def visit_Assign(self, node: ast.Assign) -> None: ...
    def visit_Expr(self, node: ast.Expr) -> None: ...
    def visit_AugAssign(self, node: ast.AugAssign) -> None: ...

class _LogicalApplicator(_Applicator):
    """Swap ``and`` with ``or`` and vice versa."""

    SWAPS: dict[type, tuple[type, str, str]] = ...

    def visit_BoolOp(self, node: ast.BoolOp) -> ast.AST: ...

class _LogicalCounter(_Counter):
    def visit_BoolOp(self, node: ast.BoolOp) -> None: ...

class _SwapIfElseApplicator(_Applicator):
    """Swap the if-body and else-body of an if statement."""

    def visit_If(self, node: ast.If) -> ast.AST: ...

class _SwapIfElseCounter(_Counter):
    def visit_If(self, node: ast.If) -> None: ...

class _RemoveNotApplicator(_Applicator):
    """Remove ``not`` from unary-not expressions."""

    def visit_UnaryOp(self, node: ast.UnaryOp) -> ast.AST: ...

class _RemoveNotCounter(_Counter):
    def visit_UnaryOp(self, node: ast.UnaryOp) -> None: ...

class _ExceptionSwallowApplicator(_Applicator):
    """Replace except handler body with ``pass`` (swallow the exception)."""

    def visit_ExceptHandler(self, node: ast.ExceptHandler) -> ast.AST: ...

class _ExceptionSwallowCounter(_Counter):
    def visit_ExceptHandler(self, node: ast.ExceptHandler) -> None: ...

class _ArgumentSwapApplicator(_Applicator):
    """Swap the first two arguments of a function call."""

    def visit_Call(self, node: ast.Call) -> ast.AST: ...

class _ArgumentSwapCounter(_Counter):
    def visit_Call(self, node: ast.Call) -> None: ...

class _BreakContinueSwapApplicator(_Applicator):
    """Swap ``break`` ↔ ``continue`` in loops."""

    def visit_Break(self, node: ast.Break) -> ast.AST: ...
    def visit_Continue(self, node: ast.Continue) -> ast.AST: ...

class _BreakContinueSwapCounter(_Counter):
    def visit_Break(self, node: ast.Break) -> None: ...
    def visit_Continue(self, node: ast.Continue) -> None: ...

class _UnaryNegateApplicator(_Applicator):
    """Remove unary minus: ``-x`` → ``x``."""

    def visit_UnaryOp(self, node: ast.UnaryOp) -> ast.AST: ...

class _UnaryNegateCounter(_Counter):
    def visit_UnaryOp(self, node: ast.UnaryOp) -> None: ...

OPERATORS: dict[str, tuple[type[_Counter], type[_Applicator]]] = ...
PresetName = Literal["essential", "standard", "thorough"]
PRESETS: dict[str, list[str]] = ...

def catalog() -> list[dict[str, str]]:
    """Discover all mutation operators and presets via runtime introspection.

    Returns a list of dicts with ``name``, ``type`` (``"operator"`` or
    ``"preset"``), ``doc`` (remediation guidance for operators, operator
    list for presets), and ``operators`` (list of operator names for presets).
    Derived from :data:`OPERATORS`, :data:`PRESETS`, and :data:`_REMEDIATION`
    — new operators appear automatically.
    """
    ...

_SKIP_METHODS = ...
_IDENTITY_OPS: dict[type, set[int | float]] = ...

def generate_mutants(
    source: str,
    operators: list[str] | None = ...,
    *,
    extra_mutants: list[str | tuple[str, str]] | None = ...,
    llm: Callable[[str], str] | None = ...,
    concern: str | None = ...,
    _stats: dict[str, int] | None = ...,
    timeout: float | None = ...,
) -> list[tuple[Mutant, ast.Module]]:
    """Generate mutants from source code, filtering out noise.

    Skips mutations inside ``__repr__``, ``__str__``, and other display
    methods (they produce equivalent mutants that always survive).

    When *extra_mutants* is provided, the given source strings are
    validated (parse, compile, dedup) and appended after rule-based ones.
    This is the primary interface for AI assistants and humans to supply
    mutants they wrote directly — no API call needed::

        result = generate_mutants(source, extra_mutants=[
            "def compute(a, b):\\n    if a <= 0: return 0\\n    return a + b",
        ])

    When *llm* is provided, it is called to generate additional mutant
    source strings automatically.  This is a convenience for automated
    pipelines — under the hood it feeds the results through the same
    validation as *extra_mutants*.

    Args:
        source: Python source code to mutate.
        operators: Operator names to use (default: all rule-based operators).
        extra_mutants: Source strings (or ``(description, source)`` tuples)
            to validate and add alongside rule-based mutants.  Written by
            an AI assistant, a human, or any other author.
        llm: Optional callable ``(prompt: str) -> str`` for automated
            mutant generation.  ordeal crafts the prompt; the user
            provides any LLM backend.
        _stats: Optional mutable dict for diagnostic counters.  When
            provided, keys ``generated``, ``filtered_ast_equivalent``,
            and ``skipped_display_method`` are incremented in-place.
        timeout: Maximum seconds for mutant generation.  When exceeded,
            returns whatever mutants have been generated so far instead
            of hanging on complex AST expressions (numpy, cv2, etc.).

    Returns a list of ``(Mutant, mutated_AST)`` pairs.
    """
    ...

_LLM_MUTANT_PROMPT = ...
_LLM_EQUIVALENCE_PROMPT = ...
_CROSS_PROCESS_IMPORTS = ...
_CROSS_PROCESS_CALLS = ...

@dataclass(frozen=True)
class _EquivalenceSamplePlan:
    """Prepared argument tuples reused across runtime-equivalence checks."""

    samples: tuple[tuple[object, ...], ...]
    ...

@dataclass(frozen=True)
class _MutationTestSelection:
    """Pytest selection derived for a mutation target."""

    paths: tuple[str, ...]
    k_filter: str | None
    ast_scores: tuple[tuple[str, int], ...] = ...

    def pytest_args(self) -> list[str]:
        """Build positional pytest args plus any ``-k`` filter."""
        ...

@dataclass
class _MutationExecutionProfile:
    """Local hints for ordering tests and choosing mutation workers."""

    kill_counts: dict[str, int] = ...
    mutant_killers: dict[str, str] = ...
    coverage_hits: tuple[str, ...] = ...
    coverage_calibrated: bool = ...
    baseline_fingerprint: str = ...
    collected_tests: int = ...
    mutant_count: int = ...
    pytest_seconds: float = ...
    workers: int = ...

@dataclass(frozen=True)
class _ValidationSampleMatrix:
    """Immutable validation templates that are cloned before every replay."""

    samples: tuple[tuple[tuple[str, object], ...], ...]
    sha256: str

    def replay(self) -> list[dict[str, object]]:
        """Return isolated samples so one mutant cannot taint another."""
        ...

def mutate_and_test(
    target: str,
    test_fn: Callable[[], None] | None = ...,
    operators: list[str] | None = ...,
    *,
    preset: PresetName | None = ...,
    workers: int = ...,
    filter_equivalent: bool = ...,
    equivalence_samples: int = ...,
    extra_mutants: list[str | tuple[str, str]] | None = ...,
    llm: Callable[[str], str] | None = ...,
    llm_equivalence: bool = ...,
    concern: str | None = ...,
    test_filter: str | None = ...,
    mutant_timeout: float | None = ...,
    disk_mutation: bool | None = ...,
    promote_clusters_only: bool = ...,
    cluster_min_size: int = ...,
    contract_context: Mapping[str, Any] | None = ...,
) -> MutationResult:
    """Apply mutations to an entire module and run *test_fn* against each.

    A mutant is **killed** if *test_fn* raises.
    A mutant **survives** if *test_fn* passes — meaning your tests miss the bug.

    Note: this swaps ``sys.modules[target]``.  Code that cached individual
    functions via ``from target import func`` will not see the mutant.
    Prefer :func:`mutate_function_and_test` for precise single-function targeting.

    Args:
        target: Module path (e.g. ``"myapp.scoring"``).
        test_fn: Zero-arg callable; should raise on failure.  When ``None``
            (default), auto-discovers tests via pytest in-process.
        operators: Mutation operators to use (default: all).
        preset: Named operator group: ``"essential"``, ``"standard"``,
            or ``"thorough"``. Mutually exclusive with *operators*.
        workers: Parallel workers for testing mutants. ``0`` (default)
            selects adaptively; a positive value is an explicit override.
        filter_equivalent: Drop mutants that produce identical outputs on
            random inputs.  Default ``True``.
        equivalence_samples: Number of random inputs for equivalence
            filtering.  Default ``10``.
        extra_mutants: Source strings (or ``(description, source)`` tuples)
            to validate and add alongside rule-based mutants.
        llm: Optional callable for automated mutant generation.
        llm_equivalence: If ``True`` and *llm* is provided, use the LLM
            to filter surviving mutants for semantic equivalence.
        test_filter: Pytest ``-k`` expression to narrow which tests run
            against each mutant. When ``None`` (default), ranks likely killer
            tests and retains a broad fallback for surviving mutants.
        mutant_timeout: Maximum seconds for the mutant generation step.
            When exceeded, returns whatever mutants have been generated so
            far.  Prevents hanging on complex AST expressions (numpy, cv2).
    """
    ...

class _MinedPropertyFailure(AssertionError):
    """Internal failure carrying every mined property that rejected a mutant."""

    def __init__(self, property_names: list[str]) -> None: ...

def validate_mined_properties(
    target: str,
    max_examples: int = ...,
    operators: list[str] | None = ...,
    *,
    preset: PresetName | None = ...,
    mine_result: MineResult | None = ...,
    validation_mode: ValidationMode = ...,
    contract_context: Mapping[str, Any] | None = ...,
    _disk_mutation: bool | None = ...,
) -> MutationResult:
    """Mine properties of *target*, then mutate it and check the properties catch the mutations.

    This answers: "are the properties mine() found strong enough to detect real bugs?"
    Surviving mutants reveal properties that are too weak — the mined invariants
    pass even on broken code.

    Args:
        target: Dotted path to the function (e.g. ``"myapp.scoring.compute"``).
        max_examples: Examples for mine() property discovery.
        operators: Mutation operators to use (default: all).
        preset: Named operator group: ``"essential"``, ``"standard"``,
            or ``"thorough"``. Mutually exclusive with *operators*.
        mine_result: Optional precomputed ``mine()`` result for the original
            function. Reusing it avoids re-mining when a caller already has
            those properties (for example, inside ``ordeal.audit``).
        validation_mode: ``"fast"`` replays mined inputs against mutants.
            ``"deep"`` replays mined inputs, then re-runs ``mine()`` on each mutant.
    """
    ...

_BOUNDARY_VALUES: dict[type, list] = ...

def mutate_function_and_test(
    target: str,
    test_fn: Callable[[], None] | None = ...,
    operators: list[str] | None = ...,
    *,
    preset: PresetName | None = ...,
    workers: int = ...,
    filter_equivalent: bool = ...,
    equivalence_samples: int = ...,
    extra_mutants: list[str | tuple[str, str]] | None = ...,
    llm: Callable[[str], str] | None = ...,
    llm_equivalence: bool = ...,
    concern: str | None = ...,
    test_filter: str | None = ...,
    mutant_timeout: float | None = ...,
    disk_mutation: bool | None = ...,
    promote_clusters_only: bool = ...,
    cluster_min_size: int = ...,
    contract_context: Mapping[str, Any] | None = ...,
) -> MutationResult:
    """Mutate a single function and run tests against each mutant.

    This is the **recommended** entry point for mutation testing. It uses
    :class:`PatchFault` to swap the function at its module attribute, so any
    code that accesses it via ``mod.func()`` will see the mutant.

    Example — minimal (auto-discovers tests via pytest)::

        from ordeal import mutate_function_and_test

        result = mutate_function_and_test("myapp.scoring.compute", preset="standard")
        print(result.summary())

    Example — only run relevant tests (fast)::

        result = mutate_function_and_test(
            "myapp.scoring.compute",
            preset="standard",
            test_filter="test_compute",
        )

    Example — AI assistant writes extra mutants directly::

        result = mutate_function_and_test(
            "myapp.scoring.compute",
            preset="standard",
            extra_mutants=[
                ("off-by-one", "def compute(a, b):\\n    if a <= 0: ..."),
                ("wrong var", "def compute(a, b):\\n    if b < 0: ..."),
            ],
        )

    Example — custom operators + parallel::

        result = mutate_function_and_test(
            "myapp.scoring.compute",
            operators=["arithmetic", "comparison", "boundary"],
            workers=4,
        )

    Args:
        target: Dotted path to the function (e.g. ``"myapp.scoring.compute"``).
        test_fn: Zero-arg callable; should raise on failure.  When ``None``
            (default), auto-discovers and runs relevant tests via pytest
            in-process (``pytest -x -k <module_name>``).
        operators: Explicit list of operator names to apply. See
            ``OPERATORS.keys()`` for all available operators. Mutually
            exclusive with *preset*.
        preset: Named operator group — pick one:

            - ``"essential"`` — 4 operators, fast feedback.
            - ``"standard"`` — 8 operators, good CI default.
            - ``"thorough"`` — all 14 operators, comprehensive.

            Mutually exclusive with *operators*. When neither is given,
            all operators are used.
        workers: Number of parallel worker processes. ``0`` (default)
            selects from mutant count, collected tests, and prior observed
            timing. A positive value is an explicit override.
        filter_equivalent: If ``True`` (default), skip mutants that produce
            identical output to the original on random sample inputs.
            Reduces noise from equivalent mutants that always survive.
        equivalence_samples: Number of random inputs for equivalence
            filtering.  Default ``10``.
        extra_mutants: Source strings (or ``(description, source)`` tuples)
            written by an AI assistant, human, or any author.  Validated
            (parse, compile, dedup) and added alongside rule-based mutants.
            This is the primary way to supply custom mutants — no API call
            needed, just write the code.
        llm: Optional callable ``(prompt: str) -> str`` for automated
            mutant generation.  Convenience for pipelines — under the hood
            it feeds results through the same validation as *extra_mutants*.
        llm_equivalence: If ``True`` and *llm* is provided, use the LLM
            to filter surviving mutants that are semantically equivalent.
        test_filter: Pytest ``-k`` expression to narrow which tests run
            against each mutant. When ``None`` (default), ranks likely killer
            tests and retains a broad fallback for surviving mutants.
        mutant_timeout: Maximum seconds for the mutant generation step.
            When exceeded, returns whatever mutants have been generated so
            far.  Prevents hanging on complex AST expressions (numpy, cv2).
    """
    ...

def mutate(
    target: str,
    test_fn: Callable[[], None] | None = ...,
    operators: list[str] | None = ...,
    *,
    preset: PresetName | None = ...,
    workers: int = ...,
    filter_equivalent: bool = ...,
    equivalence_samples: int = ...,
    extra_mutants: list[str | tuple[str, str]] | None = ...,
    llm: Callable[[str], str] | None = ...,
    llm_equivalence: bool = ...,
    concern: str | None = ...,
    test_filter: str | None = ...,
    mutant_timeout: float | None = ...,
    disk_mutation: bool | None = ...,
    promote_clusters_only: bool = ...,
    cluster_min_size: int = ...,
    resume: bool = ...,
    contract_context: Mapping[str, Any] | None = ...,
) -> MutationResult:
    """Unified mutation testing entry point — auto-detects function vs module.

    Inspects *target* to decide whether it names a callable or a module,
    then delegates to :func:`mutate_function_and_test` or
    :func:`mutate_and_test` respectively.

    This is the function used by the ``@pytest.mark.mutate`` fixture and
    is the simplest way to run mutation testing programmatically::

        from ordeal.mutations import mutate

        result = mutate("myapp.scoring.compute", preset="standard")
        print(result.summary())

    Run only relevant tests per mutant (fast)::

        result = mutate("myapp.scoring.compute", test_filter="test_compute")

    With extra mutants written by an AI assistant or human::

        result = mutate("myapp.scoring.compute", preset="standard", extra_mutants=[
            ("off-by-one", "def compute(a, b):\\n    if a <= 0: ..."),
        ])

    Args:
        target: Dotted path to a function (e.g. ``"myapp.scoring.compute"``)
            or module (e.g. ``"myapp.scoring"``).
        test_fn: Zero-arg callable; should raise on failure.  When ``None``
            (default), auto-discovers tests via pytest in-process.
        operators: Explicit list of operator names. Mutually exclusive with
            *preset*.
        preset: Named operator group: ``"essential"``, ``"standard"``,
            or ``"thorough"``. Mutually exclusive with *operators*.
        workers: Parallel worker processes. ``0`` (default) selects
            adaptively; a positive value is an explicit override.
        filter_equivalent: Skip equivalent mutants. Default ``True``.
        equivalence_samples: Samples for equivalence filtering. Default ``10``.
        extra_mutants: Source strings (or ``(description, source)`` tuples)
            to validate and add alongside rule-based mutants.
        llm: Optional callable for automated mutant generation.
        llm_equivalence: If ``True`` and *llm* is provided, use the LLM
            to filter surviving mutants for semantic equivalence.
        test_filter: Pytest ``-k`` expression to narrow which tests run
            against each mutant. When ``None`` (default), ranks likely killer
            tests and retains a broad fallback for surviving mutants.
        mutant_timeout: Maximum seconds for the mutant generation step.
            Prevents hanging on complex AST expressions (numpy, cv2).
        disk_mutation: Write the mutated source to disk so subprocesses
            (Ray workers, ``multiprocessing`` spawn) see the mutation.
            Default ``False`` (in-memory only, safe for parallel tests).
        resume: Reuse cached results when nothing has changed.  Cache is
            invalidated when **any** of these change:

            - Module source (any line)
            - Test files (``tests/test_<module>.py``, ``test_<module>_*.py``)
            - ``tests/conftest.py`` or ``conftest.py``
            - Lockfile (``uv.lock``, ``poetry.lock``, ``requirements.txt``)
            - Preset or operators
            - Test-selection and equivalence settings
            - Extra mutants or the custom test callable fingerprint

            Mine oracle results (``killed_by='mine()'``) are **never**
            cached because mine uses random inputs — re-running can
            discover more properties.

            LLM-generated mutants are also not cached because the supplied
            generator may return a different set of mutants on each run.

            **Caveat**: test files that don't follow ``test_<module>*.py``
            naming (e.g. ``test_battle.py``) are not tracked.  If you use
            ``test_filter`` to run non-standard test files, pass
            ``resume=False``.

            Default ``False`` (always run fresh).
    """
    ...

def mutation_faults(
    target: str, operators: list[str] | None = ..., *, preset: PresetName | None = ...
) -> list[tuple[Mutant, PatchFault]]:
    """Generate :class:`PatchFault` objects for each mutant of a function.

    Each fault, when activated, replaces the target function with a mutated
    version.  Use with the Explorer to let the nemesis toggle mutations
    during coverage-guided exploration::

        explorer = Explorer(MyTest, mutation_targets=["myapp.scoring.compute"])

    Args:
        target: Dotted path to the function (e.g. ``"myapp.scoring.compute"``).
        operators: Mutation operators to use (default: all).
        preset: Named operator group: ``"essential"``, ``"standard"``,
            or ``"thorough"``. Mutually exclusive with *operators*.

    Returns:
        List of ``(Mutant, PatchFault)`` pairs.
    """
    ...
