# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import pytest
from collections.abc import Generator
from typing import Any

"\nThis type stub file was generated by pyright.\n"

def pytest_addoption(parser: pytest.Parser) -> None:
    """Register ``--chaos``, ``--chaos-seed``, and ``--buggify-prob`` CLI flags."""
    ...

_seed_replay_results: list[dict[str, Any]] = ...

def pytest_configure(config: pytest.Config) -> None:
    """Activate assertions + buggify when ``--chaos`` is passed."""
    ...

def pytest_unconfigure(config: pytest.Config) -> None:
    """Deactivate assertions and buggify on session teardown."""
    ...

def pytest_sessionfinish(session: pytest.Session, exitstatus: int) -> None:
    """Publish reliability rows from an xdist worker to its controller."""
    ...

@pytest.hookimpl(optionalhook=True)
def pytest_testnodedown(node: Any, error: object | None) -> None:
    """Merge one completed xdist worker's reliability evidence."""
    ...

def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    """Skip @pytest.mark.chaos and @pytest.mark.mutate tests unless flags are passed.

    When chaos tests are skipped, a warning is emitted in the terminal
    summary so CI pipelines don't silently pass with zero chaos coverage.
    """
    ...

@pytest.fixture
def chaos_enabled() -> Generator[None, None, None]:
    """Activate chaos mode (assertions + buggify) for a single test."""
    ...

_mutation_results: list[tuple[str, Any]] = ...

@pytest.fixture
def mutate_target(request: pytest.FixtureRequest):
    """Run mutation testing on the target specified in @pytest.mark.mutate.

    Usage::

        @pytest.mark.mutate("myapp.scoring.compute", preset="standard")
        def test_scoring(mutate_target):
            result = mutate_target  # MutationResult
            assert result.score >= 0.8

    The mutation result is also collected for the terminal summary.
    """
    ...

class OrdealScanItem(pytest.Item):
    """A single auto-scanned function test item."""

    def __init__(
        self,
        name: str,
        parent: pytest.Collector,
        module_name: str = ...,
        func_name: str = ...,
        max_examples: int = ...,
        fixtures: dict[str, object] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def runtest(self) -> None: ...
    def repr_failure(
        self, excinfo: pytest.ExceptionInfo[BaseException], style: str | None = ...
    ) -> str: ...
    def reportinfo(self) -> tuple[str, int | None, str]: ...

class OrdealScanError(Exception):
    """Raised when an auto-scanned function fails."""

    ...

class OrdealScanCollector(pytest.Collector):
    """Collects scan items for one [[scan]] entry."""

    def __init__(
        self,
        name: str,
        parent: pytest.Collector,
        module_name: str = ...,
        max_examples: int = ...,
        fixtures: dict[str, object] | None = ...,
        expected_failures: list[str] | None = ...,
        **kwargs: Any,
    ) -> None: ...
    def collect(self) -> list[pytest.Item]: ...

def pytest_collect_file(parent: pytest.Collector, file_path: Any) -> OrdealScanCollector | None:
    """Auto-collect scan tests from ordeal.toml if present."""
    ...

class _OrdealTomlCollector(pytest.File):
    """Collects all [[scan]] entries from ordeal.toml."""

    def __init__(
        self, *args: Any, scan_configs: list[Any] | None = ..., **kwargs: Any
    ) -> None: ...
    def collect(self) -> list[pytest.Item | pytest.Collector]: ...

def pytest_terminal_summary(
    terminalreporter: pytest.TerminalReporter, exitstatus: int, config: pytest.Config
) -> None:
    """Print Ordeal Property Results and Mutation Results at the end."""
    ...
