# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import functools
import hypothesis.strategies as st
from typing import Any, Callable

"\nThis type stub file was generated by pyright.\n"

class biased:
    """Namespace for boundary-biased strategies."""

    @staticmethod
    def integers(
        min_value: int | None = ..., max_value: int | None = ...
    ) -> st.SearchStrategy[int]:
        """Integers biased toward 0, +/-1, range endpoints, powers of 2.

        Built-in boundaries: 0, ±1, ±2, ±10, ±100, 255, 256, ±2^15,
        ±2^31, ±2^63. When *min_value* or *max_value* are given, their
        immediate neighbors are added too.
        """
        ...

    @staticmethod
    def floats(
        min_value: float | None = ...,
        max_value: float | None = ...,
        *,
        allow_nan: bool = ...,
        allow_infinity: bool = ...,
    ) -> st.SearchStrategy[float]:
        """Floats biased toward 0, +/-1, epsilon, range endpoints.

        Built-in boundaries: 0.0, -0.0, ±1.0, ±0.5, ±1e-10, ±1e10.
        When *min_value* or *max_value* are given, they are added too.
        """
        ...

    @staticmethod
    def strings(min_size: int = ..., max_size: int = ...) -> st.SearchStrategy[str]:
        """Strings biased toward empty, single-char, max-length, unicode edges."""
        ...

    @staticmethod
    def bytes_(min_size: int = ..., max_size: int = ...) -> st.SearchStrategy[bytes]:
        """Bytes biased toward empty, all-zero, all-0xFF, boundary lengths."""
        ...

    @staticmethod
    def lists(
        elements: st.SearchStrategy, min_size: int = ..., max_size: int = ...
    ) -> st.SearchStrategy[list]:
        """Lists biased toward empty, singleton, and near-max lengths."""
        ...

@functools.lru_cache(maxsize=256)
def strategy_for_type(tp: Any, *, _depth: int = ...) -> st.SearchStrategy:
    """Derive a boundary-biased strategy from a type hint.

    Handles: int, float, str, bool, bytes, None, list[T], dict[K,V],
    tuple[T,...], set[T], Optional[T], Union[T,U], dataclasses,
    TypedDict, NewType/type aliases, and falls back to
    ``hypothesis.strategies.from_type()`` for the rest.

    Results are cached by ``(tp, _depth)`` — the same type at the same
    recursion depth always returns the same strategy object.
    """
    ...

def quickcheck(
    fn: Callable | None = ..., *, max_examples: int = ..., **overrides: st.SearchStrategy
) -> Callable:
    """Run *fn* as a property test, deriving strategies from type hints.

    Strategies are boundary-biased by default.  Pass keyword arguments
    to override specific parameters::

        @quickcheck
        def test_add_commutative(a: int, b: int):
            assert a + b == b + a

        @quickcheck(xs=st.lists(st.integers(min_value=0), max_size=5))
        def test_custom(xs: list[int], y: int):
            ...   # xs uses the override, y uses biased auto-derivation

    Works with plain functions and class methods (``self`` is skipped).
    """
    ...

from_type = ...
