# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

"\nThis type stub file was generated by pyright.\n"

def usl(n: float, sigma: float, kappa: float) -> float:
    """Universal Scaling Law: ``C(N) = N / [1 + sigma*(N-1) + kappa*N*(N-1)]``.

    Args:
        n: Number of workers/processors.
        sigma: Contention coefficient (0 <= sigma < 1). Fraction of work
            that must be serialized.
        kappa: Coherence coefficient (kappa >= 0). Cost of maintaining
            consistency across workers — grows quadratically with N.

    Returns:
        Relative throughput normalized so that C(1) = 1.
    """
    ...

def amdahl(n: float, sigma: float) -> float:
    """Amdahl's Law — USL with kappa=0 (no coherence penalty).

    Throughput is bounded by ``1/sigma`` as N grows.
    """
    ...

def optimal_n(sigma: float, kappa: float) -> float:
    """Worker count at peak throughput: ``N* = sqrt((1 - sigma) / kappa)``.

    Beyond this point, adding workers *decreases* throughput
    (retrograde scaling from coherence costs).

    Returns ``float('inf')`` when kappa=0 (Amdahl regime).
    """
    ...

def peak_throughput(sigma: float, kappa: float) -> float:
    """Maximum achievable throughput ``C(N*)``.

    Returns ``1/sigma`` when kappa=0 (Amdahl asymptote).
    """
    ...

def fit_usl(measurements: list[tuple[int | float, float]]) -> tuple[float, float]:
    """Fit non-negative sigma and kappa from (N, throughput) pairs.

    Linearizes the USL equation::

        N/C(N) - 1 = sigma*(N-1) + kappa*N*(N-1)

    The constrained least-squares optimum is selected from the feasible
    interior and the ``sigma=0``, ``sigma=1``, and ``kappa=0`` boundaries.
    Boundary coefficients are refitted instead of independently clamping an
    unconstrained solution.

    Requires at least 3 data points (including N=1).
    Throughput should be normalized so C(1) ~ 1.0.

    Returns:
        ``(sigma, kappa)`` tuple.

    Raises:
        ValueError: If fewer than 3 usable measurements or degenerate data.
    """
    ...

@dataclass(frozen=True)
class _USLFit:
    """Internal constrained USL fit in the linearized response space."""

    sigma: float
    kappa: float
    points: list[tuple[float, float, float, float]]
    residual_sum_squares: float
    sigma_ci: tuple[float, float] | None
    kappa_ci: tuple[float, float] | None
    ...

_T_975 = ...

@dataclass
class ScalingAnalysis:
    """Results from USL analysis of scaling measurements."""

    sigma: float
    kappa: float
    n_optimal: float
    peak: float
    measurements: list[tuple[float, float]]
    regime: str
    residuals: list[tuple[float, float]] = ...
    r_squared: float = ...
    rmse: float = ...
    max_relative_error: float = ...
    sigma_ci: tuple[float, float] | None = ...
    kappa_ci: tuple[float, float] | None = ...
    fit_status: str = ...
    fit_reason: str | None = ...

    def summary(self) -> str:
        """Human-readable scaling report with diagnosis."""
        ...

    def efficiency(self, n: int) -> float:
        """Parallel efficiency at N workers: C(N)/N."""
        ...

    def throughput(self, n: int) -> float:
        """Predicted relative throughput at N workers."""
        ...

@dataclass
class MutationBenchmarkTrial:
    """One fresh-process mutation benchmark run."""

    seconds: float
    total: int
    killed: int
    score: float
    timings: dict[str, float] = ...
    diagnostics: dict[str, Any] = ...

@dataclass
class MutationBenchmarkCase:
    """Aggregated timings for one mutation target."""

    target: str
    trials: list[MutationBenchmarkTrial]

    @builtins.property
    def median_seconds(self) -> float:
        """Median wall time across fresh subprocess runs."""
        ...

    @builtins.property
    def phase_medians(self) -> dict[str, float]:
        """Median per-phase wall times across trials."""
        ...

    @builtins.property
    def median_selected_test_files(self) -> int:
        """Median count of heuristic test files handed to pytest."""
        ...

    @builtins.property
    def median_collected_tests(self) -> int:
        """Median collected pytest item count across trials."""
        ...

    def summary(self) -> str:
        """Human-readable mutation latency report."""
        ...

@dataclass
class MutationBenchmarkSuite:
    """Benchmark results for one or more mutation targets."""

    cases: list[MutationBenchmarkCase]
    repeats: int
    workers: int
    preset: str | None

    def summary(self) -> str:
        """Human-readable summary for the whole mutation suite."""
        ...

@dataclass(frozen=True)
class PerfContractSpec:
    """One benchmark case from a checked-in perf/quality contract."""

    name: str
    kind: str
    tier: str = ...
    repeats: int = ...
    max_seconds: float | None = ...
    module: str | None = ...
    target: str | None = ...
    mode: str = ...
    validation_mode: str = ...
    compare_validation_mode: str | None = ...
    workers: int = ...
    preset: str | None = ...
    test_filter: str | None = ...
    filter_equivalent: bool = ...
    test_dir: str = ...
    max_examples: int = ...
    max_score_gap: float | None = ...
    min_score: float | None = ...

    def to_dict(self) -> dict[str, Any]:
        """JSON-friendly view of the contract case specification."""
        ...

@dataclass
class PerfContractCase:
    """Observed timings and quality metrics for one contract case."""

    spec: PerfContractSpec
    seconds: list[float]
    details: dict[str, Any] = ...

    @builtins.property
    def median_seconds(self) -> float:
        """Median wall time for the case."""
        ...

    @builtins.property
    def max_seconds(self) -> float | None:
        """Configured upper bound for this case."""
        ...

    @builtins.property
    def score_gap(self) -> float | None:
        """Observed score gap for differential audit cases."""
        ...

    @builtins.property
    def observed_score(self) -> float | None:
        """Return the quality score governed by ``min_score``."""
        ...

    @builtins.property
    def passed(self) -> bool:
        """Whether the observed median stayed within the configured budget."""
        ...

    def summary(self) -> str:
        """Human-readable one-line summary."""
        ...

    def to_dict(self) -> dict[str, Any]:
        """JSON-friendly view of one observed contract case."""
        ...

@dataclass
class PerfContractSuite:
    """Results for a checked-in perf/quality contract."""

    cases: list[PerfContractCase]
    contract_path: str

    @builtins.property
    def passed(self) -> bool:
        """True when every benchmark case stayed within budget."""
        ...

    @builtins.property
    def failures(self) -> list[PerfContractCase]:
        """Cases that exceeded their configured budget."""
        ...

    def summary(self) -> str:
        """Human-readable summary for the entire contract."""
        ...

    def to_dict(self) -> dict[str, Any]:
        """JSON-friendly view of the whole contract run."""
        ...

    def to_json(self) -> str:
        """Stable JSON encoding for artifact and trend storage."""
        ...

def analyze(measurements: list[tuple[int | float, float]]) -> ScalingAnalysis:
    """Fit USL from (N, throughput) measurements and return full analysis.

    Args:
        measurements: List of ``(worker_count, throughput)`` pairs.
            Throughput should be normalized so C(1) = 1.0.
    """
    ...

_MUTATION_BENCHMARK_MARKER = ...
_IMPORT_BENCHMARK_MARKER = ...
_AUDIT_DIFF_MARKER = ...

def benchmark_perf_contract(
    contract_path: str,
    *,
    python_executable: str | None = ...,
    cwd: str | None = ...,
    tier: str | None = ...,
) -> PerfContractSuite:
    """Run a checked-in perf/quality contract and return the observed medians.

    Parameters
    ----------
    tier:
        When set, only run cases whose ``tier`` matches.  ``"pr"`` for the
        lean PR gate, ``"nightly"`` for the full matrix.  ``None`` runs all.
    """
    ...

def benchmark(
    test_class: type | None = ...,
    *,
    target_modules: list[str] | None = ...,
    max_workers: int | None = ...,
    time_per_trial: float = ...,
    seed: int = ...,
    steps_per_run: int = ...,
    metric: str = ...,
    mutate_targets: list[str] | None = ...,
    repeats: int = ...,
    workers: int = ...,
    preset: str | None = ...,
    filter_equivalent: bool = ...,
    test_filter: str | None = ...,
    python_executable: str | None = ...,
    cwd: str | None = ...,
) -> ScalingAnalysis | MutationBenchmarkSuite:
    """Benchmark exploration scaling or mutation latency.

    Runs exploration at N=1, 2, 4, ... workers, measures throughput,
    normalizes to C(1)=1, and fits sigma/kappa.

    Args:
        test_class: A ChaosTest subclass to benchmark.
        target_modules: Modules for coverage tracking.
        max_workers: Cap on worker count (default: CPU count).
        time_per_trial: Seconds per trial at each N.
        seed: Base RNG seed.
        steps_per_run: Steps per exploration run.
        metric: ``"runs"`` (runs/sec) or ``"edges"`` (unique edges/sec).
        mutate_targets: Mutation targets to benchmark in fresh subprocesses.
            When provided, mutation latency benchmarking runs instead of
            explorer scaling analysis.
        repeats: Fresh subprocess runs per mutation target.
        workers: Worker count for mutation benchmarking.
        preset: Mutation preset for mutation benchmarking.
        filter_equivalent: Whether to keep equivalence filtering enabled.
        test_filter: Optional pytest ``-k`` expression for mutation runs.
        python_executable: Python interpreter to use for fresh subprocess trials.
        cwd: Working directory for mutation benchmark subprocesses.

    Returns:
        A :class:`ScalingAnalysis` for exploration benchmarks, or a
        :class:`MutationBenchmarkSuite` when *mutate_targets* is provided.
    """
    ...

def scales_linearly(
    fn: Callable[..., Any] | None = ...,
    *,
    n_range: tuple[int, int] = ...,
    max_kappa: float = ...,
    max_sigma: float = ...,
    samples: int = ...,
    time_per_sample: float = ...,
) -> Callable[..., Any]:
    """Decorator: assert that a function scales linearly with concurrency.

    Runs the function with increasing worker counts, fits the USL model,
    and fails if contention (sigma) or coherence (kappa) exceed thresholds::

        from ordeal.scaling import scales_linearly

        @scales_linearly(n_range=(1, 8), max_kappa=0.01)
        def process_batch(items):
            ...

    Args:
        n_range: ``(min_workers, max_workers)`` to test.
        max_kappa: Fail if coherence exceeds this (quadratic overhead).
        max_sigma: Fail if contention exceeds this (serial bottleneck).
        samples: Number of worker counts to test between min and max.
        time_per_sample: Seconds to run at each worker count.
    """
    ...
