# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from dataclasses import dataclass
from typing import Any

"\nThis type stub file was generated by pyright.\n"
_ALL_EXPLORATION_DIMENSIONS = ...

@dataclass
class FunctionState:
    """Exploration state for a single function."""

    name: str
    source_hash: str | None = ...
    mined: bool = ...
    properties: list[dict[str, Any]] = ...
    property_violations: list[str] = ...
    property_violation_details: list[dict[str, Any]] = ...
    edges_discovered: int = ...
    saturated: bool = ...
    mutated: bool = ...
    mutation_score: float | None = ...
    survived_mutants: int = ...
    killed_mutants: int = ...
    hardened: bool = ...
    hardened_kills: int = ...
    scanned: bool = ...
    crash_free: bool | None = ...
    scan_error: str | None = ...
    failing_args: dict[str, Any] | None = ...
    scan_crash_category: str | None = ...
    scan_replayable: bool | None = ...
    scan_replay_attempts: int = ...
    scan_replay_matches: int = ...
    scan_minimization: dict[str, Any] | None = ...
    scan_contract_fit: float | None = ...
    scan_reachability: float | None = ...
    scan_realism: float | None = ...
    scan_sink_signal: float | None = ...
    scan_sink_categories: list[str] = ...
    scan_input_sources: list[dict[str, str]] = ...
    scan_input_source: str | None = ...
    scan_proof_bundle: dict[str, Any] | None = ...
    scan_limitation_kind: str | None = ...
    scan_blocking_reason: str | None = ...
    fuzz_examples: int = ...
    contract_violations: list[str] = ...
    contract_violation_details: list[dict[str, Any]] = ...
    chaos_tested: bool = ...
    faults_tested: list[str] = ...

    @builtins.property
    def confidence(self) -> float: ...
    def confidence_for(self, dimensions: set[str] | tuple[str, ...] | list[str]) -> float:
        """Per-function exploration confidence [0, 1].

        Combines coverage across dimensions. Each dimension contributes
        independently — more exploration = higher confidence.
        """
        ...

    def reset(self) -> None:
        """Clear all exploration results.  Called when source changes."""
        ...

    @builtins.property
    def frontier(self) -> list[str]: ...
    def frontier_for(self, dimensions: set[str] | tuple[str, ...] | list[str]) -> list[str]:
        """What's unexplored for this function."""
        ...

@dataclass
class ExplorationState:
    """Unified exploration state for a module.

    Accumulates results from all ordeal tools. JSON-serializable
    for persistence across sessions.
    """

    module: str
    functions: dict[str, FunctionState] = ...
    skipped: list[tuple[str, str]] = ...
    refreshed: list[str] = ...
    edge_coverage: float | None = ...
    exploration_time: float = ...
    supervisor_info: dict[str, Any] = ...
    tree: Any = ...
    scan_mode: str = ...
    active_dimensions: tuple[str, ...] = ...

    def function(self, name: str) -> FunctionState:
        """Get or create state for a function."""
        ...

    def refresh(self) -> list[str]:
        """Invalidate functions whose source code changed since last exploration.

        Compares stored ``source_hash`` on each function against the
        current source.  Changed functions are :meth:`reset` — all
        prior results are discarded so the next exploration redoes them
        from scratch.  Fresh source hashes are stamped on every
        function that can be resolved.

        Returns the names of functions that were invalidated.
        """
        ...

    @builtins.property
    def confidence(self) -> float:
        """Aggregate confidence across all functions."""
        ...

    @builtins.property
    def frontier(self) -> dict[str, list[str]]:
        """Per-function gaps — what's unexplored."""
        ...

    @builtins.property
    def findings(self) -> list[str]:
        """Promoted findings worth treating as primary scan output."""
        ...

    @builtins.property
    def exploratory_findings(self) -> list[str]:
        """Exploratory scan output that should not fail the run by default."""
        ...

    @builtins.property
    def finding_details(self) -> list[dict[str, Any]]:
        """Structured finding details for reports and AI handoff."""
        ...

    def summary(self) -> str:
        """Human-readable exploration report."""
        ...

    def to_json(self) -> str:
        """Serialize to JSON for persistence."""
        ...

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-friendly dict for persistence and agents.

        The state tree's snapshots are excluded (not JSON-serializable).
        The tree structure is preserved via ``tree.to_json()``.
        """
        ...

    @classmethod
    def from_json(cls, data: str) -> ExplorationState:
        """Deserialize from JSON."""
        ...

def explore_mine(
    state: ExplorationState,
    *,
    max_examples: int = ...,
    include_private: bool = ...,
    targets: list[str] | None = ...,
    object_factories: dict[str, Any] | None = ...,
    object_setups: dict[str, Any] | None = ...,
    object_scenarios: dict[str, Any] | None = ...,
    object_state_factories: dict[str, Any] | None = ...,
    object_teardowns: dict[str, Any] | None = ...,
    object_harnesses: dict[str, str] | None = ...,
    ignore_properties: list[str] | None = ...,
    ignore_relations: list[str] | None = ...,
    property_overrides: dict[str, list[str]] | None = ...,
    relation_overrides: dict[str, list[str]] | None = ...,
) -> ExplorationState:
    """Mine all functions in the module and update state."""
    ...

def explore_scan(
    state: ExplorationState,
    *,
    max_examples: int = ...,
    targets: list[str] | None = ...,
    fixtures: dict[str, Any] | None = ...,
    object_factories: dict[str, Any] | None = ...,
    object_setups: dict[str, Any] | None = ...,
    object_scenarios: dict[str, Any] | None = ...,
    object_state_factories: dict[str, Any] | None = ...,
    object_teardowns: dict[str, Any] | None = ...,
    object_harnesses: dict[str, str] | None = ...,
    expected_failures: list[str] | None = ...,
    expected_preconditions: dict[str, list[str]] | None = ...,
    ignore_contracts: list[str] | None = ...,
    ignore_properties: list[str] | None = ...,
    ignore_relations: list[str] | None = ...,
    contract_overrides: dict[str, list[str]] | None = ...,
    expected_properties: dict[str, list[str]] | None = ...,
    expected_relations: dict[str, list[str]] | None = ...,
    property_overrides: dict[str, list[str]] | None = ...,
    relation_overrides: dict[str, list[str]] | None = ...,
    contract_checks: dict[str, list[Any]] | None = ...,
    mode: str = ...,
    seed_from_tests: bool = ...,
    seed_from_fixtures: bool = ...,
    seed_from_docstrings: bool = ...,
    seed_from_code: bool = ...,
    seed_from_call_sites: bool = ...,
    treat_any_as_weak: bool = ...,
    proof_bundles: bool = ...,
    auto_contracts: list[str] | None = ...,
    require_replayable: bool = ...,
    min_contract_fit: float = ...,
    min_reachability: float = ...,
    min_realism: float = ...,
    security_focus: bool = ...,
    minimize_findings: bool = ...,
) -> ExplorationState:
    """Scan module for crashes and update state."""
    ...

def explore_mutate(
    state: ExplorationState,
    *,
    workers: int = ...,
    extra_mutants: dict[str, list[str | tuple[str, str]]] | None = ...,
    concern: str | None = ...,
    llm: Any | None = ...,
) -> ExplorationState:
    """Mutation-test all mined functions and update state.

    Scales with *workers*: more CPUs = more mutants tested in parallel.

    Args:
        state: Exploration state to enrich.
        workers: Parallel workers for mutation testing.
        extra_mutants: Per-function extra mutant source strings, keyed by
            function name.  Written by the AI assistant or human.
        concern: Free-text concern for targeted mutation generation.
        llm: Optional LLM callable for automated mutant generation.
    """
    ...

def explore_harden(state: ExplorationState, extra_tests: dict[str, list[str]]) -> ExplorationState:
    """Verify tests against surviving mutants and update state (Meta ACH pattern).

    For each function in *extra_tests*, re-runs mutation testing to get
    surviving mutants, then verifies each test with the three-assurance
    loop: buildable, valid regression, kills mutant.

    This is the step where an AI assistant closes the loop: it reads
    ``state.frontier`` to find unhardened survivors, writes tests, and
    calls ``explore_harden`` to verify them.

    Args:
        state: Exploration state with prior mutation results.
        extra_tests: Per-function test source strings, keyed by function
            name.  Each test should import the target and assert behavior.

    Returns:
        Updated state with hardening results.
    """
    ...

def explore_chaos(
    state: ExplorationState,
    *,
    max_examples: int = ...,
    object_factories: dict[str, Any] | None = ...,
    object_setups: dict[str, Any] | None = ...,
    object_scenarios: dict[str, Any] | None = ...,
    object_state_factories: dict[str, Any] | None = ...,
    object_teardowns: dict[str, Any] | None = ...,
    object_harnesses: dict[str, str] | None = ...,
) -> ExplorationState:
    """Auto-generate and run chaos tests, update state."""
    ...

def explore(
    module: str,
    *,
    state: ExplorationState | None = ...,
    time_limit: float | None = ...,
    workers: int = ...,
    max_examples: int = ...,
    seed: int = ...,
    patch_io: bool = ...,
    include_private: bool = ...,
    scan_targets: list[str] | None = ...,
    scan_fixtures: dict[str, Any] | None = ...,
    scan_object_factories: dict[str, Any] | None = ...,
    scan_object_setups: dict[str, Any] | None = ...,
    scan_object_scenarios: dict[str, Any] | None = ...,
    scan_object_state_factories: dict[str, Any] | None = ...,
    scan_object_teardowns: dict[str, Any] | None = ...,
    scan_object_harnesses: dict[str, str] | None = ...,
    scan_expected_failures: list[str] | None = ...,
    scan_expected_preconditions: dict[str, list[str]] | None = ...,
    scan_ignore_contracts: list[str] | None = ...,
    scan_ignore_properties: list[str] | None = ...,
    scan_ignore_relations: list[str] | None = ...,
    scan_contract_overrides: dict[str, list[str]] | None = ...,
    scan_expected_properties: dict[str, list[str]] | None = ...,
    scan_expected_relations: dict[str, list[str]] | None = ...,
    scan_property_overrides: dict[str, list[str]] | None = ...,
    scan_relation_overrides: dict[str, list[str]] | None = ...,
    scan_contract_checks: dict[str, list[Any]] | None = ...,
    scan_mode: str = ...,
    scan_seed_from_tests: bool = ...,
    scan_seed_from_fixtures: bool = ...,
    scan_seed_from_docstrings: bool = ...,
    scan_seed_from_code: bool = ...,
    scan_seed_from_call_sites: bool = ...,
    scan_treat_any_as_weak: bool = ...,
    scan_proof_bundles: bool = ...,
    scan_auto_contracts: list[str] | None = ...,
    scan_require_replayable: bool = ...,
    scan_min_contract_fit: float = ...,
    scan_min_reachability: float = ...,
    scan_min_realism: float = ...,
    scan_security_focus: bool = ...,
    scan_minimize_findings: bool = ...,
    run_mine: bool = ...,
    run_scan: bool = ...,
    run_mutate: bool = ...,
    run_chaos: bool = ...,
) -> ExplorationState:
    """Run all exploration strategies on a module.

    Assembles mine → scan → mutate → chaos into one pass.
    Each step enriches the shared ``ExplorationState``.  The entire
    exploration runs inside a ``DeterministicSupervisor`` for
    reproducibility, and checkpoints into a ``StateTree`` so the
    AI can navigate the exploration trajectory.

    Scales with compute: more *workers* → more mutations tested
    in parallel, more *max_examples* → more input space sampled.
    Confidence grows with both.

    Deterministic: same *seed* + same code = same exploration.
    Different seeds explore different regions of the state space.
    The trajectory is logged in ``state.supervisor`` and the
    state tree is in ``state.tree``.

    The AI assistant can also run steps individually via
    ``explore_mine``, ``explore_scan``, ``explore_mutate``,
    ``explore_harden``, ``explore_chaos`` for finer control.

    Args:
        module: Dotted module path.
        state: Resume from a previous exploration. ``None`` starts fresh.
        time_limit: Optional time budget in seconds (soft limit).
        workers: Parallel workers for mutation testing. More CPUs = more
            state space explored per unit time.
        max_examples: Hypothesis examples for mining and scanning. More
            examples = more input space sampled = higher confidence.
        seed: RNG seed for deterministic exploration. Same seed = same
            trajectory. Default 42.
        patch_io: If ``True``, enable deterministic file/network/subprocess
            I/O inside the supervisor while exploring.
    """
    ...
