# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from collections.abc import Callable, Generator
from dataclasses import dataclass
from typing import Any

"\nThis type stub file was generated by pyright.\n"

@dataclass
class Transition:
    """One step in the exploration trajectory."""

    state_before: int
    action: str
    state_after: int
    step: int = ...

    def __str__(self) -> str: ...

@dataclass(frozen=True)
class _RegisteredSubprocess:
    """One deterministic subprocess registration."""

    command: str
    match: str
    stdout: bytes
    stderr: bytes
    returncode: int
    delay: float
    ...

class _DeterministicPopen:
    """Minimal in-memory ``Popen`` backed by the supervisor clock."""

    def __init__(
        self,
        supervisor: DeterministicSupervisor,
        args: Any,
        registration: _RegisteredSubprocess,
        *,
        text: bool,
        encoding: str | None,
        errors: str | None,
        stdout_pipe: bool,
        stderr_pipe: bool,
    ) -> None: ...
    def poll(self) -> int | None:
        """Return the process return code if it has completed."""
        ...

    def wait(self, timeout: float | None = ...) -> int:
        """Wait for deterministic completion, advancing simulated time."""
        ...

    def communicate(
        self, input: Any = ..., timeout: float | None = ...
    ) -> tuple[str | bytes | None, str | bytes | None]:
        """Wait for completion and return deterministic stdout/stderr."""
        ...

    def kill(self) -> None:
        """Terminate the simulated subprocess immediately."""
        ...

    def terminate(self) -> None:
        """Terminate the simulated subprocess gracefully."""
        ...

    def __enter__(self) -> _DeterministicPopen: ...
    def __exit__(self, *exc: object) -> None: ...

@dataclass(frozen=True)
class _SchedulerInstruction:
    """One instruction yielded by a cooperative scheduled task."""

    kind: str
    delay: float = ...

@dataclass
class _ScheduledTask:
    """Mutable state for one cooperative scheduled task."""

    name: str
    coroutine: Generator[_SchedulerInstruction, None, Any]
    wake_at: float = ...
    done: bool = ...
    result: Any = ...
    steps: int = ...

class DeterministicSupervisor:
    """Control all sources of non-determinism for reproducible exploration.

    A context manager that:

    1. Seeds every RNG in the process (``random``, ``buggify``, ``numpy``)
    2. Replaces ``time.time()``/``time.sleep()`` with a deterministic ``Clock``
    3. Can run cooperative tasks under a deterministic scheduler
    4. Logs every state transition as a Markov chain
    5. Records ``PYTHONHASHSEED`` for full reproduction

    The same seed produces the same exploration trajectory.  Different
    seeds explore different regions.  The trajectory can be replayed
    from any point.

    Attributes:
        seed: The RNG seed controlling this execution.
        clock: The deterministic ``Clock`` replacing ``time.time()``.
        trajectory: List of ``(state_before, action, state_after)`` transitions.
        hash_seed: The ``PYTHONHASHSEED`` value (for reproduction notes).
    """

    ...

    def __init__(self, seed: int = ..., *, patch_io: bool = ...) -> None:
        """Create a deterministic supervisor.

        Args:
            seed: RNG seed for all entropy sources.
            patch_io: If True, also patch ``open()``, ``socket``, and
                ``threading.Thread.start`` for full I/O determinism.
                Default False — only RNGs and time are patched.
                Set True when testing I/O-heavy or multithreaded code.
        """
        ...

    def register_subprocess(
        self,
        command: str | list[str] | tuple[str, ...],
        *,
        stdout: str | bytes = ...,
        stderr: str | bytes = ...,
        returncode: int = ...,
        delay: float = ...,
        match: str = ...,
    ) -> None:
        """Register a deterministic subprocess result for ``patch_io=True``.

        This is the first step from process-local determinism toward a
        system substrate: code under test can cross a process boundary
        and still remain reproducible.  Registered commands run against
        the supervisor clock, never the OS scheduler.

        Args:
            command: Exact command or argv to match.
            stdout: Simulated standard output.
            stderr: Simulated standard error.
            returncode: Exit status returned by the child.
            delay: Simulated runtime in seconds.
            match: ``"exact"`` or ``"contains"``.
        """
        ...

    def clear_subprocesses(self) -> None:
        """Remove all deterministic subprocess registrations."""
        ...

    def yield_now(self) -> _SchedulerInstruction:
        """Yield control back to the deterministic cooperative scheduler."""
        ...

    def sleep(self, seconds: float) -> _SchedulerInstruction:
        """Suspend the running cooperative task for *seconds* of simulated time."""
        ...

    def spawn(
        self,
        name: str,
        task: Callable[..., Any] | Generator[_SchedulerInstruction, None, Any] | Any,
        *args: Any,
        **kwargs: Any,
    ) -> None:
        """Register a cooperative task with the deterministic scheduler.

        ``task`` may be either:

        - a generator function that yields ``yield_now()`` / ``sleep()``
        - an already-created generator
        - a plain callable (runs to completion on its first schedule slot)
        """
        ...

    @builtins.property
    def task_results(self) -> dict[str, Any]:
        """Results of cooperative tasks that have completed."""
        ...

    @builtins.property
    def pending_tasks(self) -> list[str]:
        """Names of cooperative tasks that have not finished yet."""
        ...

    def run_until_idle(self, *, max_steps: int | None = ...) -> dict[str, Any]:
        """Run scheduled tasks until all are done or *max_steps* is reached.

        The scheduler is cooperative: tasks run until they yield one of the
        scheduler instructions returned by :meth:`yield_now` or :meth:`sleep`.
        When no tasks are runnable, the supervisor clock advances to the next
        wake-up time deterministically.
        """
        ...

    def __enter__(self) -> DeterministicSupervisor:
        """Activate deterministic mode: seed RNGs, patch I/O, start logging.

        Controls every entropy source a Python library can reach:

        **RNG seeding** (same seed = identical random sequences):
        - ``random`` module — all functions
        - buggify — thread-local fault RNG
        - numpy — if installed
        - Hypothesis — database disabled (no cross-run leakage),
          but internal RNG uses source hash, not our seed.
          Mine() property confidence is APPROXIMATE, not exact.

        **I/O patching** (deterministic, no real disk/network/time):
        - ``time.time()`` / ``time.sleep()`` → ``simulate.Clock``
        - ``builtins.open()`` → ``simulate.FileSystem`` (in-memory)
        - ``socket.create_connection`` → raises ``ConnectionRefusedError``
        - ``subprocess.run`` / ``check_output`` / ``Popen`` → deterministic,
          registered child processes on the supervisor clock

        **Thread tracking** (observable, logged):
        - ``threading.Thread.start`` → wrapped to log thread creation
          in the trajectory. Thread scheduling is still OS-controlled
          but thread creation is deterministic and visible.
        - ``spawn()`` / ``yield_now()`` / ``sleep()`` → cooperative tasks
          scheduled deterministically from a seed-derived scheduler RNG

        **What remains non-deterministic** (OS-level, cannot control):
        - Thread interleaving ORDER within the OS scheduler (unless you
          model the work as cooperative scheduled tasks)
        - GC finalization timing
        - ``ctypes`` / C extension side effects
        """
        ...

    def __exit__(self, *exc: object) -> None:
        """Restore all patched functions and RNG states."""
        ...

    def log_transition(self, action: str, *, state_hash: int | None = ...) -> None:
        """Record a state transition in the exploration trajectory.

        Args:
            action: Human-readable description of what happened
                (e.g. ``"toggle timeout fault"``, ``"call process()"``)
            state_hash: Hash of the current state after the action.
                If ``None``, auto-increments from the previous state.
        """
        ...

    def fork(self, new_seed: int | None = ...) -> DeterministicSupervisor:
        """Create a new supervisor forked from the current state.

        The forked supervisor:
        - Starts from the current state (not from zero)
        - Uses a different seed (for exploring a different branch)
        - Inherits the trajectory up to this point

        This is how the Explorer can branch from a checkpoint:
        fork with a different seed → each fork explores a different
        path from the same known state.
        """
        ...

    @builtins.property
    def state(self) -> int:
        """Current state hash."""
        ...

    @builtins.property
    def visited_states(self) -> set[int]:
        """All states visited in this trajectory."""
        ...

    @builtins.property
    def unique_transitions(self) -> int:
        """Number of unique (state, action) pairs explored."""
        ...

    def summary(self) -> str:
        """Human-readable exploration trajectory summary."""
        ...

    def reproduction_info(self) -> dict[str, Any]:
        """Return everything needed to reproduce this exact execution.

        An AI assistant can save this and replay later::

            info = sup.reproduction_info()
            # Save to file, pass to another run, etc.
            # To reproduce: DeterministicSupervisor(seed=info["seed"])
        """
        ...

@dataclass
class StateNode:
    """A node in the exploration tree — one checkpointed state.

    Each node stores:
    - The state identity (hash) and a snapshot of the Python objects
    - Which actions have been taken from this state (children)
    - Which actions are POSSIBLE but untaken (the frontier)
    - The edge coverage at this point

    The tree grows as exploration proceeds.  The AI can navigate it:
    go deeper (explore a child), roll back (return to parent), or
    branch (try an untaken action from any visited node).
    """

    state_id: int
    parent_id: int | None = ...
    action_from_parent: str | None = ...
    depth: int = ...
    edges_at_checkpoint: int = ...
    children: dict[str, int] = ...
    snapshot: Any = ...
    seed_at_checkpoint: int = ...

class StateTree:
    """Navigable exploration tree with checkpoint, rollback, and branching.

    This is ordeal's answer to "remembering previous states."  The
    exploration is a tree, not a sequence.  At each state, multiple
    actions are possible.  The tree tracks which actions have been
    taken and which remain unexplored.

    The AI assistant navigates the tree::

        tree = StateTree()

        # Checkpoint the current state
        tree.checkpoint(state_id=0, snapshot=my_state)

        # Explore action A → reach state 1
        tree.checkpoint(state_id=1, parent=0, action="action_A",
                        snapshot=new_state)

        # Rollback to state 0
        old_state = tree.rollback(0)

        # Explore action B → reach state 2 (different branch)
        tree.checkpoint(state_id=2, parent=0, action="action_B",
                        snapshot=other_state)

        # What's unexplored?
        tree.frontier()  # states with untaken actions

    The tree is the single source of truth for the exploration.
    The AI reads it to decide where to go next.  ordeal provides
    the checkpoint/rollback/branch operations.  The AI is the
    search strategy.

    Integrates with DeterministicSupervisor: same seed at the same
    checkpoint → same exploration path.  Different seed → different
    branch.  The tree tracks which seeds have been tried at each node.
    """

    def __init__(self) -> None: ...
    def checkpoint(
        self,
        state_id: int,
        *,
        snapshot: Any = ...,
        parent: int | None = ...,
        action: str | None = ...,
        edges: int = ...,
        seed: int = ...,
    ) -> StateNode:
        """Save a state as a node in the tree.

        Args:
            state_id: Unique identifier for this state (e.g. hash).
            snapshot: The Python object to checkpoint (deepcopied).
                Can be a ChaosTest instance, a dict, or any picklable
                object.  ``rollback()`` returns a deepcopy of this.
            parent: The state_id of the parent node (where we came from).
            action: The action that led from parent to this state.
            edges: Edge coverage count at this checkpoint.
            seed: The RNG seed used to reach this state.
        """
        ...

    def rollback(self, state_id: int) -> Any:
        """Roll back to a previously checkpointed state.

        Returns a deepcopy of the snapshot saved at that checkpoint.
        The tree is not modified — you can rollback and branch as
        many times as you want from any node.

        Args:
            state_id: The state to roll back to.

        Returns:
            A deepcopy of the checkpointed snapshot, or ``None`` if
            no snapshot was saved.

        Raises:
            KeyError: If ``state_id`` was never checkpointed.
        """
        ...

    @builtins.property
    def current(self) -> StateNode | None:
        """The current node in the tree."""
        ...

    @builtins.property
    def size(self) -> int:
        """Number of checkpointed states."""
        ...

    @builtins.property
    def max_depth(self) -> int:
        """Deepest node in the tree."""
        ...

    def frontier(self) -> list[StateNode]:
        """Nodes that could be explored further.

        A node is on the frontier if:
        - It has a snapshot (can be rolled back to)
        - It's a leaf (no children yet) OR hasn't been fully explored

        The AI reads this to decide where to branch next.
        """
        ...

    def leaves(self) -> list[StateNode]:
        """Leaf nodes — deepest explored states."""
        ...

    def path_to(self, state_id: int) -> list[StateNode]:
        """Return the path from root to the given state.

        Useful for reproducing: the path is the sequence of actions
        that leads to this state.
        """
        ...

    def summary(self) -> str:
        """Human-readable tree summary."""
        ...

    def to_json(self) -> str:
        """Serialize the tree structure (without snapshots) for persistence."""
        ...
