# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Literal
from ordeal._observation import CanonicalObservation

"\nThis type stub file was generated by pyright.\n"

@dataclass(frozen=True)
class Operation:
    """Call one named method on both systems at the same timeline position.

    ``args`` and ``kwargs`` are deep-copied independently so mutations in the
    old version cannot change what the new version receives.

    Example::

        Operation("create_order", args=("A7",), kwargs={"quantity": 2})
    """

    name: str
    args: tuple[Any, ...] = ...
    kwargs: Mapping[str, Any] = ...

    def __post_init__(self) -> None:
        """Validate the operation and detach its argument containers."""
        ...

@dataclass(frozen=True)
class FaultEvent:
    """Apply the same named fault transition to both system versions.

    Interleave these with ``Operation`` objects. Actions named ``deactivate``,
    ``recover``, ``restart``, or ``clear`` begin the measured recovery phase.

    Example::

        FaultEvent("backend_timeout", "activate", {"after_ms": 50})
    """

    name: str
    action: str = ...
    parameters: Mapping[str, Any] = ...

    def __post_init__(self) -> None:
        """Validate the event and detach its parameter container."""
        ...

SystemEvent = Operation | FaultEvent

@dataclass(frozen=True)
class PerformanceBudget:
    """Set a latency limit without turning slowness into behavior divergence.

    At least one of ``max_slowdown`` or ``max_candidate_seconds`` is required.
    Ordeal records repeated samples and medians for the original sequence;
    ``within_budget`` lives on the separate ``PerformanceResult``.
    """

    max_slowdown: float | None = ...
    max_candidate_seconds: float | None = ...
    samples: int = ...
    warmup: int = ...

    def __post_init__(self) -> None:
        """Reject thresholds that cannot express a useful budget."""
        ...

@dataclass(frozen=True)
class InterfaceReport:
    """Explain missing public names and changed callable signatures."""

    exports_a: Mapping[str, str]
    exports_b: Mapping[str, str]
    missing_from_a: tuple[str, ...]
    missing_from_b: tuple[str, ...]
    signature_mismatches: tuple[str, ...]

    @builtins.property
    def matches(self) -> bool:
        """Whether both public surfaces have the same exports and signatures."""
        ...

@dataclass(frozen=True)
class SystemMismatch:
    """One outcome, state, or side-effect difference at a specific event."""

    kind: Literal["outcome", "state", "side_effects", "fault_schedule"]
    step: int
    event: SystemEvent
    observed_a: Any
    observed_b: Any
    replay_observation: CanonicalObservation | None = ...
    observation_a: CanonicalObservation | None = ...
    observation_b: CanonicalObservation | None = ...

@dataclass(frozen=True)
class StepComparison:
    """Show both observations and parity flags for one timeline event."""

    index: int
    event: SystemEvent
    outcome_a: Any
    outcome_b: Any
    outcome_match: bool
    state_a: Any = ...
    state_b: Any = ...
    state_match: bool | None = ...
    side_effects_a: Any = ...
    side_effects_b: Any = ...
    side_effects_match: bool | None = ...
    recovery_phase: bool = ...

    @builtins.property
    def matches(self) -> bool:
        """Whether every measured semantic contract matched at this step."""
        ...

@dataclass(frozen=True)
class PerformanceResult:
    """Repeated timings, medians, slowdown, and the separate budget verdict."""

    baseline_seconds: tuple[float, ...]
    candidate_seconds: tuple[float, ...]
    baseline_median_seconds: float
    candidate_median_seconds: float
    slowdown: float
    within_budget: bool
    budget: PerformanceBudget
    ...

@dataclass
class SystemDiffResult:
    """Report interface, behavior, recovery, replay, and speed independently.

    ``sequence`` is the minimized shared story and ``fault_schedule`` is its
    fault-only view. Read ``status`` for semantic parity, replay counts for
    stability, and ``performance.within_budget`` for speed.
    """

    system_a: str
    system_b: str
    interface: InterfaceReport
    sequence: tuple[SystemEvent, ...]
    steps: list[StepComparison]
    mismatches: list[SystemMismatch]
    original_length: int
    state_checked: bool
    side_effects_checked: bool
    fault_schedule_replayed: bool
    recovery_parity: bool | None
    replay_attempts: int
    replay_matches: int
    minimization_performed: bool = ...
    performance: PerformanceResult | None = ...
    expected_signature: str | None = ...
    observed_signatures: tuple[str | None, ...] = ...
    reason: str | None = ...
    harness_errors: tuple[str, ...] = ...
    original_sequence: tuple[SystemEvent, ...] = ...
    original_mismatch: SystemMismatch | None = ...
    artifact: dict[str, Any] | None = ...
    artifact_path: str | None = ...
    regression_path: str | None = ...
    manifest_path: str | None = ...
    finding_id: str | None = ...
    regression_error: str | None = ...

    @builtins.property
    def status(self) -> Literal["divergent", "no_divergence_observed", "inconclusive"]:
        """Return the evidence-scoped semantic status."""
        ...

    @builtins.property
    def divergent(self) -> bool:
        """Whether stable evidence disproved a measured semantic contract."""
        ...

    @builtins.property
    def no_divergence_found(self) -> bool:
        """Whether every measured semantic contract matched in this run."""
        ...

    @builtins.property
    def equivalent(self) -> bool | None:
        """False when disproved, otherwise unknown beyond the measured sequence."""
        ...

    @builtins.property
    def minimized_length(self) -> int:
        """Number of events in the reported counterexample sequence."""
        ...

    @builtins.property
    def fault_schedule(self) -> tuple[FaultEvent, ...]:
        """The exact minimized fault plan replayed against both systems."""
        ...

    @builtins.property
    def replay_verified(self) -> bool | None:
        """Whether every exact replay reproduced the runtime divergence."""
        ...

    @builtins.property
    def artifacts(self) -> tuple[dict[str, Any], ...]:
        """Return the shared source-bound change artifact when one exists."""
        ...

    def summary(self) -> str:
        """Return a compact report with behavior and performance kept separate."""
        ...

@dataclass(frozen=True)
class _Outcome:
    """A return value or ordinary exception captured from one event."""

    value: Any = ...
    exception: Exception | None = ...
    value_observation: CanonicalObservation | None = ...
    replay_observation: CanonicalObservation | None = ...

    @builtins.property
    def public_value(self) -> Any:
        """Return the value exposed in reports."""
        ...

@dataclass(frozen=True)
class _ObservedValue:
    """One detached probe value and its structural observation."""

    value: Any
    observation: CanonicalObservation

    @builtins.property
    def public_value(self) -> Any:
        """Return the report-facing view without target-defined repr."""
        ...

_RECOVERY_ACTIONS = ...
_UNMEASURED = ...
