# ruff: noqa
import builtins

"""
This type stub file was generated by pyright.
"""
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, TYPE_CHECKING

"\nThis type stub file was generated by pyright.\n"
if TYPE_CHECKING: ...

@dataclass
class TraceStep:
    """A single step in an exploration trace.

    ``active_faults`` is populated on ``fault_toggle`` steps (the
    snapshot after the toggle).  On ``rule`` steps it defaults to
    ``[]`` — the active set is derivable from the preceding
    ``fault_toggle`` steps in the trace.
    """

    kind: str
    name: str
    params: dict[str, Any] = ...
    active_faults: list[str] = ...
    edge_count: int = ...
    timestamp_offset: float = ...
    properties_observed: list[str] = ...
    native_boundary: dict[str, Any] | None = ...
    status_code: int | None = ...
    endpoint: str | None = ...

@dataclass
class TraceFailure:
    """Serializable failure info (no live Exception reference)."""

    error_type: str
    error_message: str
    step: int
    native_boundary: dict[str, Any] | None = ...

@dataclass
class Trace:
    """Complete trace of one exploration run."""

    run_id: int
    seed: int
    test_class: str
    from_checkpoint: int | None
    steps: list[TraceStep] = ...
    failure: TraceFailure | None = ...
    edges_discovered: int = ...
    duration: float = ...

    def content_hash(self) -> str:
        """Stable SHA256 hash of trace content for dedup-safe filenames."""
        ...

    def to_dict(self) -> dict[str, Any]:
        """Convert to a JSON-serializable dict."""
        ...

    def save(self, path: str | Path) -> None:
        """Write trace to a JSON file.

        If *path* ends with ``.gz`` (e.g. ``trace.json.gz``), the
        output is gzip-compressed — typically 5-10x smaller than
        plain JSON, useful for long exploration runs.
        """
        ...

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Trace:
        """Reconstruct a Trace from a dict (loaded from JSON)."""
        ...

    @classmethod
    def load(cls, path: str | Path) -> Trace:
        """Load a trace from a JSON file.

        Automatically detects gzip-compressed files (``.gz`` suffix).
        """
        ...

_ENCODE_DISPATCH: dict[type, Callable[[Any], dict]] = ...

class _TraceEncoder(json.JSONEncoder):
    def default(self, o: Any) -> Any: ...

class _TraceDecoder(json.JSONDecoder):
    def __init__(self, **kwargs: Any) -> None: ...

def replay(trace: Trace, test_class: type | None = ...) -> Exception | None:
    """Replay a trace, returning the exception if it reproduces.

    Args:
        trace: The trace to replay.
        test_class: Override the class (default: import from trace metadata).

    Returns:
        The exception if the failure reproduces, or ``None``.
    """
    ...

def shrink(trace: Trace, test_class: type | None = ..., *, max_time: float = ...) -> Trace:
    """Shrink a failing trace to the minimal reproducing sequence.

    Three phases, applied iteratively until fixpoint:

    1. **Delta debugging**: remove large chunks (halves, quarters, ...)
    2. **Single-step elimination**: try removing each step individually
    3. **Fault simplification**: remove unnecessary fault toggle pairs

    Args:
        trace: A trace whose failure should reproduce.
        test_class: Override the class (default: import from trace metadata).
        max_time: Wall-clock time limit for shrinking.

    Returns:
        A new Trace with the minimal step sequence.
    """
    ...

def ablate_faults(trace: Trace, test_class: type | None = ...) -> dict[str, bool]:
    """Determine which faults are individually necessary for a failure.

    **Phase 1 — individual ablation**: for each fault in the trace,
    replays without that fault's toggles (all other faults remain).
    If the failure disappears, the fault is *individually necessary*.

    **Phase 2 — pairwise ablation**: if multiple faults appear
    individually unnecessary (removing either one still fails because
    the other compensates), tests removing them in pairs.  A pair
    where the failure disappears means those faults are *jointly
    necessary* — neither alone is sufficient, but together they are.

    This answers the Antithesis root-cause question: *"Is it possible
    to find the bug without fiddling with the clock?"*

    **Epistemic note**: this finds faults that are necessary *for this
    specific trace*.  A different execution path might reproduce the
    same bug with a different fault set.

    Args:
        trace: A failing trace (typically already shrunk).
        test_class: Override the class (default: import from trace metadata).

    Returns:
        ``{fault_name: True}`` if the fault is necessary (removing it
        prevents reproduction), ``{fault_name: False}`` if it is not
        (failure still reproduces without it).  Empty dict if the trace
        has no fault toggles.
    """
    ...

def generate_tests(traces: list[Trace], *, class_path: str | None = ...) -> str:
    """Generate pytest test functions from exploration traces.

    Turns the most valuable traces into standalone, replayable tests.
    Each test recreates the exact rule/fault sequence that the explorer
    found.

    Args:
        traces: Traces to convert (typically from ``ExplorationResult``).
        class_path: Override the test class import path.

    Returns:
        Python source code for a test module.
    """
    ...
