"""Generated by `ordeal scan --write-regression`.

Target: ordeal.demo
"""

from ordeal.demo import decode, normalize


def test_decode_crash_regression() -> None:
    args = {"s": "utf-8", "errors": "backslashreplace"}
    decode(**args)


def test_normalize_idempotent_regression() -> None:
    args = {
        "xs": [
            -0.5,
            -1e-10,
            1e-10,
            -1e-10,
            4.144458155102842e156,
            -6.6963419951248536e16,
            1.7976931348623157e308,
            -3.616486811991499e101,
            -0.5,
            1.0,
            -4.068483339364122e16,
            1.0,
            0.5,
            10000000000.0,
            9.86824931803198e-277,
            -0.5,
            -1.0,
            -0.5,
            -0.5,
            6.547575912135547e16,
            -1.9198634850646304e173,
            1.0,
            1.7976931348623157e308,
            -3.636904938664375e16,
            1.0,
            -0.5,
            4.5747212034095016e16,
            3.888417926073227e16,
            0.5,
            0.5,
            0.5,
            0.5,
            -2.225073858507e-311,
            3.961967807725296e16,
            -3.5795266015245828e249,
            1.0,
            1.1065494390694392e244,
            10000000000.0,
            -1.0,
            -6.995147908889531e16,
            2.2651147357678012e216,
            -10000000000.0,
            1e-10,
            -1e-10,
            -1.0336413497027154e-241,
            -10000000000.0,
            -1e-10,
            -1.2317946419553132e262,
        ]
    }
    first = normalize(**args)
    replay_args = dict(args)
    replay_args["xs"] = first
    second = normalize(**replay_args)
    assert second == first
