from __future__ import annotations
# ruff: noqa
import copy
import hashlib
import importlib
import inspect
import json
import re
from collections.abc import Callable, Collection, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal
from ordeal._observation import observe
from ordeal.audit import ModuleAudit
from ordeal.audit import audit as _audit
from ordeal.auto import (
    ContractCheck,
    ScanResult,
    _call_contract_predicate,
    _call_sync,
    _get_public_functions,
)
from ordeal.auto import (
    scan_module as _scan_module,
)
from ordeal.diff import (
    DiffResult,
    DiffWitness,
    Mismatch,
    _approx_equal,
    _bind_named_arguments,
)
from ordeal.diff import diff as _diff
from ordeal.finding_evidence import _json_ready
from ordeal.mine import (
    STRUCTURAL_LIMITATIONS,
    MineModuleResult,
)
from ordeal.mine import (
    mine_module as _mine_module,
)
from ordeal.mutations import MutationResult
from ordeal.mutations import mutate as _mutate
from ordeal.regression_evidence import _decode_replay_value, _encode_replay_value
StageStatus = Literal["passed", "failed", "blocked"]
ChangeKind = Literal["behavior", "signature", "added", "removed"]
ChangeClassification = Literal["intended", "unexpected"]
ChangeClassifier = Callable[
    ["MigrationChange"],
    ChangeClassification | tuple[ChangeClassification, str],
]
_SCHEMA_VERSION = 1
_GENERATED_HEADER = '"""Generated by `ordeal migrate`.'
@dataclass(frozen=True)
class MigrationStage:
    """One ordered stage and its evidence status."""

    name: str
    status: StageStatus
    summary: str
@dataclass(frozen=True)
class CandidateContract:
    """A property observed while mining the candidate implementation."""

    function: str
    property: str
    holds: int
    total: int
    confidence: float
    source: str = "mined_hypothesis"
@dataclass
class MigrationChange:
    """One behavioral or public-surface change between base and candidate."""

    id: str
    function: str
    kind: ChangeKind
    mismatch: Mismatch | None = None
    witness: DiffWitness | None = None
    base_signature: str | None = None
    candidate_signature: str | None = None
    regression_options: dict[str, object] = field(default_factory=dict)
    classification: ChangeClassification = "unexpected"
    reason: str = "not declared as intended"

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe evidence record for this change."""
        record: dict[str, object] = {
            "id": self.id,
            "function": self.function,
            "kind": self.kind,
            "classification": self.classification,
            "reason": self.reason,
        }
        if self.mismatch is not None:
            record.update(
                {
                    "args": _display_value(self.mismatch.args),
                    "base_outcome": _display_value(self.mismatch.output_a),
                    "candidate_outcome": _display_value(self.mismatch.output_b),
                }
            )
        if self.witness is not None:
            record["witness"] = {
                "differences": list(self.witness.differences),
                "replay_attempts": self.witness.replay_attempts,
                "replay_matches": self.witness.replay_matches,
                "replay_verified": self.witness.replay_verified,
                "artifact_id": self.witness.artifact.get("artifact_id"),
                "artifact_path": self.witness.artifact_path,
            }
        if self.kind == "signature":
            record["base_signature"] = self.base_signature
            record["candidate_signature"] = self.candidate_signature
        if self.regression_options:
            record["regression_options"] = dict(self.regression_options)
        return record
@dataclass(frozen=True)
class RegressionArtifacts:
    """Paths and persistence evidence for unexpected divergences."""

    evidence_path: Path
    regression_path: Path
    regression_cases: tuple[dict[str, object], ...] = ()
    unsupported_change_ids: tuple[str, ...] = ()
    error: str | None = None
    manifest_path: Path | None = None
    finding_id: str | None = None
@dataclass(frozen=True)
class MutationGate:
    """Mutation result or the exact reason mutation evidence is unavailable."""

    status: StageStatus
    threshold: float
    result: MutationResult | None = None
    reason: str | None = None
@dataclass
class MigrationResult:
    """Structured evidence from a complete base-to-candidate workflow."""

    base: str
    candidate: str
    stages: list[MigrationStage]
    base_audit: ModuleAudit
    candidate_mining: MineModuleResult
    candidate_contracts: list[CandidateContract]
    changes: list[MigrationChange]
    artifacts: RegressionArtifacts
    mutation: MutationGate
    candidate_scan: ScanResult
    diff_errors: dict[str, str] = field(default_factory=dict)
    explicit_invariant_count: int = 0
    explicit_invariant_functions: tuple[str, ...] = ()
    mining_limitations: list[str] = field(default_factory=lambda: list(STRUCTURAL_LIMITATIONS))

    @property
    def unexpected_changes(self) -> list[MigrationChange]:
        """Return divergences not explicitly classified as intended."""
        return [change for change in self.changes if change.classification == "unexpected"]

    @property
    def intended_changes(self) -> list[MigrationChange]:
        """Return divergences explicitly classified as intended."""
        return [change for change in self.changes if change.classification == "intended"]

    @property
    def measured_regression_callables(self) -> tuple[str, ...]:
        """Return callables whose measured mutants were all killed by resulting tests."""
        mutation_result = self.mutation.result
        if mutation_result is None:
            return ()
        by_callable: dict[str, list[bool]] = {}
        for mutant in mutation_result.mutants:
            if mutant.qualname:
                by_callable.setdefault(mutant.qualname, []).append(mutant.killed)
        return tuple(
            sorted(
                function
                for function, outcomes in by_callable.items()
                if outcomes and all(outcomes)
            )
        )

    @property
    def unprotected_changed_callables(self) -> tuple[str, ...]:
        """Return intended behavior changes lacking callable-scoped protection."""
        intended_behavior = {
            change.function for change in self.intended_changes if change.kind == "behavior"
        }
        protected = set(self.explicit_invariant_functions) | set(
            self.measured_regression_callables
        )
        return tuple(sorted(intended_behavior - protected))

    @property
    def protected_within_measured_scope(self) -> bool:
        """Whether every required evidence gate passed within configured scope."""
        audit_blocked = bool(getattr(self.base_audit, "blocking_reason", None))
        mutation_result = self.mutation.result
        mutation_fully_killed = bool(
            mutation_result is not None
            and mutation_result.total > 0
            and mutation_result.killed == mutation_result.total
        )
        return (
            not audit_blocked
            and not self.unexpected_changes
            and not self.diff_errors
            and not self.artifacts.unsupported_change_ids
            and self.artifacts.error is None
            and self.explicit_invariant_count > 0
            and not self.unprotected_changed_callables
            and self.mutation.status == "passed"
            and mutation_fully_killed
            and self.candidate_scan.total > 0
            and self.candidate_scan.passed
        )

    @property
    def ready(self) -> bool:
        """Alias for :attr:`protected_within_measured_scope`."""
        return self.protected_within_measured_scope

    def summary(self) -> str:
        """Render the workflow in stage order without overstating evidence."""
        lines = [f"ordeal migrate {self.base} -> {self.candidate}"]
        for stage in self.stages:
            lines.append(f"  {stage.status.upper():7} {stage.name}: {stage.summary}")
        lines.append(
            "  RESULT  "
            + (
                "PROTECTIVE_WITHIN_MEASURED_SCOPE"
                if self.protected_within_measured_scope
                else "INCOMPLETE"
            )
        )
        lines.append(
            "  NOTE    mined properties are hypotheses; explicit invariants, mutation, "
            "and candidate scan carry correctness/protection evidence"
        )
        if self.unprotected_changed_callables:
            lines.append(
                "  NOTE    intended behavior lacks callable-scoped protection: "
                + ", ".join(self.unprotected_changed_callables)
            )
        return "\n".join(lines)

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-safe result for CLI and agent consumers."""
        mutation_result = self.mutation.result
        return {
            "schema_version": _SCHEMA_VERSION,
            "base": self.base,
            "candidate": self.candidate,
            "protected_within_measured_scope": self.protected_within_measured_scope,
            "stages": [
                {"name": stage.name, "status": stage.status, "summary": stage.summary}
                for stage in self.stages
            ],
            "candidate_contracts": [
                {
                    "function": contract.function,
                    "property": contract.property,
                    "holds": contract.holds,
                    "total": contract.total,
                    "confidence": contract.confidence,
                    "source": contract.source,
                }
                for contract in self.candidate_contracts
            ],
            "changes": [change.to_dict() for change in self.changes],
            "diff_errors": dict(self.diff_errors),
            "explicit_invariant_count": self.explicit_invariant_count,
            "explicit_invariant_functions": list(self.explicit_invariant_functions),
            "measured_regression_callables": list(self.measured_regression_callables),
            "unprotected_changed_callables": list(self.unprotected_changed_callables),
            "artifacts": {
                "evidence_path": self.artifacts.evidence_path.as_posix(),
                "regression_path": self.artifacts.regression_path.as_posix(),
                "regression_cases": len(self.artifacts.regression_cases),
                "unsupported_change_ids": list(self.artifacts.unsupported_change_ids),
                "error": self.artifacts.error,
                "manifest_path": (
                    self.artifacts.manifest_path.as_posix()
                    if self.artifacts.manifest_path is not None
                    else None
                ),
                "finding_id": self.artifacts.finding_id,
            },
            "mutation": {
                "status": self.mutation.status,
                "threshold": self.mutation.threshold,
                "reason": self.mutation.reason,
                "test_basis": (
                    mutation_result.contract_context.get("test_basis")
                    if mutation_result is not None
                    else None
                ),
                "killed": mutation_result.killed if mutation_result is not None else None,
                "total": mutation_result.total if mutation_result is not None else None,
                "score": mutation_result.score if mutation_result is not None else None,
            },
            "candidate_scan": {
                "passed": self.candidate_scan.total > 0 and self.candidate_scan.passed,
                "total": self.candidate_scan.total,
                "failed": self.candidate_scan.failed,
                "verdict_counts": self.candidate_scan.verdict_counts,
            },
            "mining_limitations": list(self.mining_limitations),
        }
def _slug(value: str) -> str:
    """Return a stable path-safe module slug."""
    return re.sub(r"[^A-Za-z0-9_]+", "_", value).strip("_") or "module"
def _default_evidence_path(base: str, candidate: str) -> Path:
    """Return the per-pair evidence path."""
    return Path(".ordeal/migrations") / f"{_slug(base)}_to_{_slug(candidate)}.json"
def _default_regression_path(candidate: str) -> Path:
    """Return the generated pytest path for a candidate module."""
    return Path("tests") / f"test_ordeal_migration_{_slug(candidate)}.py"
def _display_value(value: object) -> dict[str, object]:
    """Represent an arbitrary outcome without claiming it is replayable."""
    if isinstance(value, BaseException):
        return {
            "kind": "exception",
            "type": f"{type(value).__module__}.{type(value).__qualname__}",
            "message": str(value),
        }
    return {
        "kind": "return",
        "type": f"{type(value).__module__}.{type(value).__qualname__}",
        "repr": repr(value),
    }
def _encode_value(value: object) -> object:
    """Encode common witness values into JSON-safe, exactly replayable data."""
    return _encode_replay_value(value)
def _decode_value(value: object) -> object:
    """Decode data written by :func:`_encode_value`."""
    return _decode_replay_value(value)
def _canonical_state(value: object) -> object:
    """Canonicalize replay state the same way immutable diff witnesses do."""
    return observe(value, label="migration replay state").payload
def replay_migration_case(case: Mapping[str, object]) -> None:
    """Replay one saved unexpected divergence against its candidate module."""
    candidate = str(case["candidate"])
    function = str(case["function"])
    kind = str(case["kind"])
    module = importlib.import_module(candidate)

    if kind == "added":
        if hasattr(module, function):
            raise AssertionError(f"unexpected public callable still present: {function}")
        return
    if kind == "removed":
        if not hasattr(module, function):
            raise AssertionError(f"expected public callable is still missing: {function}")
        return
    if kind == "signature":
        func = getattr(module, function)
        expected_signature = str(case["expected_signature"])
        try:
            observed_signature = str(inspect.signature(func))
        except (TypeError, ValueError) as exc:
            raise AssertionError(
                f"candidate public signature is not inspectable: {function}"
            ) from exc
        if observed_signature != expected_signature:
            raise AssertionError(
                f"candidate public signature for {function} is {observed_signature}; "
                f"expected {expected_signature}"
            )
        return
    if kind != "behavior":
        raise ValueError(f"unknown migration regression kind: {kind!r}")

    func = getattr(module, function)
    kwargs_value = _decode_value(case["kwargs"])
    if not isinstance(kwargs_value, dict):
        raise TypeError("migration regression kwargs must decode to a dict")
    expected = case["expected"]
    if not isinstance(expected, Mapping):
        raise TypeError("migration regression expected outcome must be a mapping")

    observed_error: BaseException | None = None
    actual: object = None
    try:
        call_args, call_kwargs = _bind_named_arguments(func, kwargs_value)
        actual = _call_sync(func, *call_args, **call_kwargs)
    except BaseException as exc:
        observed_error = exc

    expected_kind = expected.get("kind")
    if expected_kind == "exception":
        expected_type = f"{expected['type_module']}.{expected['type_qualname']}"
        if observed_error is None:
            raise AssertionError(f"candidate did not raise {expected_type}: {expected['message']}")
        observed_type = f"{type(observed_error).__module__}.{type(observed_error).__qualname__}"
        if observed_type != expected_type or str(observed_error) != str(expected["message"]):
            raise AssertionError(
                "candidate raised a different exception: "
                f"{type(observed_error).__name__}: {observed_error}"
            ) from observed_error
    elif expected_kind == "canonical_return":
        if observed_error is not None:
            raise observed_error
        expected_observation = expected.get("observation")
        if not isinstance(expected_observation, Mapping):
            raise TypeError("canonical migration outcome must contain an observation graph")
        actual_observation = observe(
            actual,
            label="migration candidate return value",
        ).payload
        if actual_observation != expected_observation:
            raise AssertionError(
                "candidate returned a structurally different value from the preserved base outcome"
            )
    elif expected_kind == "return":
        if observed_error is not None:
            raise observed_error
        expected_value = _decode_value(expected["value"])
        comparison_options = case.get("comparison", {})
        if not isinstance(comparison_options, Mapping):
            raise TypeError("migration regression comparison must be a mapping")
        rtol_value = comparison_options.get("rtol")
        atol_value = comparison_options.get("atol")
        if rtol_value is not None or atol_value is not None:
            matches = _approx_equal(
                actual,
                expected_value,
                float(rtol_value or 1e-9),
                float(atol_value or 0.0),
            )
        else:
            comparison = actual == expected_value
            try:
                matches = bool(comparison)
            except (TypeError, ValueError):
                matches = False
        if not matches:
            raise AssertionError(
                f"candidate returned {actual!r}; expected preserved base outcome "
                f"{expected_value!r}"
            )
    else:
        raise ValueError(f"unknown migration expected outcome kind: {expected_kind!r}")

    if "expected_mutated_arguments_observation" in case:
        expected_arguments_observation = case["expected_mutated_arguments_observation"]
        if not isinstance(expected_arguments_observation, Mapping):
            raise TypeError("canonical migration argument state must contain an observation graph")
        actual_arguments_observation = observe(
            kwargs_value,
            label="migration candidate mutated arguments",
        ).payload
        if actual_arguments_observation != expected_arguments_observation:
            raise AssertionError(
                "candidate arguments have structurally different state from the preserved "
                "base outcome"
            )
    elif "expected_mutated_arguments" in case:
        expected_arguments = _decode_value(case["expected_mutated_arguments"])
        if _canonical_state(kwargs_value) != _canonical_state(expected_arguments):
            raise AssertionError(
                f"candidate mutated arguments to {kwargs_value!r}; expected preserved "
                f"base state {expected_arguments!r}"
            )
