from __future__ import annotations
# ruff: noqa
def _encode_system_replay_event(event: SystemEvent) -> dict[str, object]:
    """Encode one system event without invoking target-defined repr methods."""
    if isinstance(event, Operation):
        return {
            "kind": "operation",
            "name": event.name,
            "args": _encode_replay_value(event.args),
            "kwargs": _encode_replay_value(event.kwargs),
        }
    return {
        "kind": "fault",
        "name": event.name,
        "action": event.action,
        "parameters": _encode_replay_value(event.parameters),
    }
def _decode_system_replay_event(payload: Mapping[str, object]) -> SystemEvent:
    """Decode one exact system regression event."""
    if payload.get("kind") == "operation":
        args = _decode_replay_value(payload.get("args", ()))
        kwargs = _decode_replay_value(payload.get("kwargs", {}))
        if not isinstance(args, tuple) or not isinstance(kwargs, Mapping):
            raise TypeError("system operation replay data has invalid args or kwargs")
        return Operation(str(payload["name"]), args=args, kwargs=kwargs)
    if payload.get("kind") == "fault":
        parameters = _decode_replay_value(payload.get("parameters", {}))
        if not isinstance(parameters, Mapping):
            raise TypeError("system fault replay data has invalid parameters")
        return FaultEvent(
            str(payload["name"]),
            str(payload.get("action", "activate")),
            parameters,
        )
    raise ValueError(f"unknown system replay event kind: {payload.get('kind')!r}")
def replay_diff_regression_case(case: Mapping[str, object]) -> None:
    """Replay one saved function or system divergence until it stays fixed."""
    fn_a = _resolve_replay_callable(case["callable_a"])
    fn_b = _resolve_replay_callable(case["callable_b"])
    assert fn_a is not None and fn_b is not None
    compare = _resolve_replay_callable(case.get("compare"))
    normalize = _resolve_replay_callable(case.get("normalize"))
    options: dict[str, Any] = {
        "compare": compare,
        "normalize": normalize,
        "rtol": case.get("rtol"),
        "atol": case.get("atol"),
        "replay_attempts": 1,
    }
    mode = str(case["mode"])
    if mode == "function":
        kwargs = _decode_replay_value(case["kwargs"])
        if not isinstance(kwargs, Mapping) or not all(isinstance(key, str) for key in kwargs):
            raise TypeError("function regression kwargs must be a string-keyed mapping")
        result = diff(fn_a, fn_b, max_examples=1, **options, **dict(kwargs))
    elif mode == "system":
        encoded_sequence = case.get("sequence")
        if not isinstance(encoded_sequence, list):
            raise TypeError("system regression sequence must be a list")
        sequence = [
            _decode_system_replay_event(item)
            for item in encoded_sequence
            if isinstance(item, Mapping)
        ]
        if len(sequence) != len(encoded_sequence):
            raise TypeError("system regression sequence contains an invalid event")
        result = diff(
            fn_a,
            fn_b,
            sequence=sequence,
            state=_resolve_replay_callable(case.get("state")),
            side_effects=_resolve_replay_callable(case.get("side_effects")),
            apply_fault=_resolve_replay_callable(case.get("apply_fault")),
            minimize=False,
            **options,
        )
    else:
        raise ValueError(f"unknown diff regression mode: {mode!r}")
    if not result.no_divergence_found:
        raise AssertionError(
            f"saved {mode} divergence is not fixed: {result.status}"
            + (f" ({result.reason})" if result.reason else "")
        )
def _render_diff_regression(case: Mapping[str, object]) -> str:
    """Render one standalone, source-bindable diff regression."""
    return "\n".join(
        [
            '"""Generated by `ordeal diff`.',
            "",
            f"Target ID: {case['id']}",
            '"""',
            "",
            "from ordeal.diff import replay_diff_regression_case",
            "",
            f"CASE = {dict(case)!r}",
            "",
            "",
            f"def {_DIFF_REGRESSION_TEST}() -> None:",
            '    """Keep the minimized paired divergence fixed."""',
            "    replay_diff_regression_case(CASE)",
            "",
        ]
    )
def _persist_diff_regression(
    *,
    mode: Literal["function", "system"],
    fn_a: Callable[..., Any],
    fn_b: Callable[..., Any],
    artifact: Mapping[str, Any],
    artifact_path: str | None,
    regression_path: str | Path,
    manifest_path: str | Path,
    compare: Callable[[Any, Any], bool] | None,
    normalize: Callable[[Any], Any] | None,
    rtol: float | None,
    atol: float | None,
    kwargs: Mapping[str, Any] | None = None,
    sequence: Sequence[SystemEvent] | None = None,
    state: Callable[[Any], Any] | None = None,
    side_effects: object = None,
    apply_fault: Callable[[Any, FaultEvent], None] | None = None,
) -> tuple[str | None, str | None, str | None, str | None]:
    """Persist one generated diff regression and register it for CI."""
    try:
        if artifact.get("status") != "supported":
            raise ValueError(
                "durable diff regressions require supported replay and minimization evidence"
            )
        if artifact_path is None:
            raise ValueError("durable diff regressions require artifact_dir")
        if mode == "function" and side_effects:
            raise TypeError("function side-effect bindings are not yet persistable")
        callable_a = _callable_import_path(fn_a, label="baseline")
        callable_b = _callable_import_path(fn_b, label="candidate")
        assert callable_a is not None and callable_b is not None
        identity = hashlib.sha256(
            f"{mode}\0{callable_a}\0{callable_b}".encode("utf-8")
        ).hexdigest()[:16]
        case: dict[str, object] = {
            "id": f"{mode}:{identity}",
            "mode": mode,
            "callable_a": callable_a,
            "callable_b": callable_b,
            "compare": _callable_import_path(compare, label="compare"),
            "normalize": _callable_import_path(normalize, label="normalize"),
            "rtol": rtol,
            "atol": atol,
        }
        if mode == "function":
            case["kwargs"] = _encode_replay_value(dict(kwargs or {}))
        else:
            case.update(
                {
                    "sequence": [_encode_system_replay_event(event) for event in sequence or ()],
                    "state": _callable_import_path(state, label="state probe"),
                    "side_effects": _callable_import_path(
                        side_effects if callable(side_effects) else None,
                        label="side-effect probe",
                    ),
                    "apply_fault": _callable_import_path(
                        apply_fault,
                        label="fault adapter",
                    ),
                }
            )
        output_path = Path(regression_path)
        if output_path.exists():
            existing = output_path.read_text(encoding="utf-8")
            if not existing.startswith('"""Generated by `ordeal diff`.'):
                raise ValueError(f"refusing to overwrite non-generated regression: {output_path}")
            if f"Target ID: {case['id']}" not in existing:
                raise ValueError(f"regression path already belongs to another diff: {output_path}")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(_render_diff_regression(case), encoding="utf-8")
        finding_id = f"fnd_diff_{identity}"
        comparison_artifact = artifact.get("comparison", {})
        revisions_artifact = artifact.get("revisions", {})
        source_guards: list[dict[str, str]] = []

        def guard(path: object, binding: object) -> None:
            """Record one import path and measured source hash for CI."""
            if path is None or not isinstance(binding, Mapping):
                return
            source_sha256 = str(binding.get("source_sha256") or "")
            if source_sha256:
                source_guards.append({"callable": str(path), "source_sha256": source_sha256})

        guard(
            callable_a,
            revisions_artifact.get("a") if isinstance(revisions_artifact, Mapping) else None,
        )
        if isinstance(comparison_artifact, Mapping):
            guard(case.get("compare"), comparison_artifact.get("comparator"))
            guard(case.get("normalize"), comparison_artifact.get("normalizer"))
            guard(case.get("state"), comparison_artifact.get("state_probe"))
            guard(case.get("side_effects"), comparison_artifact.get("side_effect_probe"))
            guard(case.get("apply_fault"), comparison_artifact.get("fault_adapter"))
        registered, error = _register_python_regression(
            manifest_path=Path(manifest_path),
            finding_id=finding_id,
            change_kind=mode,
            target=f"{callable_a} -> {callable_b}",
            test_path=output_path,
            test_name=_DIFF_REGRESSION_TEST,
            evidence_path=Path(artifact_path),
            change_artifact_ids=[str(artifact.get("artifact_id"))],
            test_basis="paired_minimized_witness",
            extra={"source_guards": source_guards},
        )
        if error is not None:
            return output_path.as_posix(), None, None, error
        assert registered is not None
        return output_path.as_posix(), registered.as_posix(), finding_id, None
    except (AttributeError, ImportError, OSError, TypeError, ValueError) as exc:
        return None, None, None, str(exc)
